- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardBrigmedic
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       brigmedic
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardCadet
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       cadet
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardDetective
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       detective
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardSecurityOfficer
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       security_officer
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardSeniorOfficer
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       senior_officer
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardWarden
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       warden
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardInternalControlExecutor
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       internal_control_executor
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardHosMilitia
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       warden
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardMilitia
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       security_officer
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardSeniorMilitia
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       senior_officer
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardMedOfficer
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       security_officer
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardLrrChief
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       warden
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardPilot
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       security_officer
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardIVK
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       senior_officer
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi

- type: entity
  parent: IS14_IdCardBase
  id: IS14_IdCardInvestigator
  name: identification card
  description: A card necessary to access various areas aboard the station.
  components:
  - type: Appearance
    appearanceDataInit:
     enum.IdCardVisualLayers.Base:
       !type:String
       detective
  - type: Sprite
    sprite: /Textures/_IS14/Objects/Devices/id_cards/security.rsi
