- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaBrigmedic
  name: brigmedic's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardBrigmedic

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaCadet
  name: cadet's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardCadet

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaDetective
  name: detective's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardDetective

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaSecurityOfficer
  name: security officer's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardSecurityOfficer

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaSeniorOfficer
  name: senior officer's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardSeniorOfficer

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaWarden
  name: warden's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardWarden

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaInternalControlExecutor
  name: internal control executor's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardInternalControlExecutor

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaHosMilitia
  name: head of security's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardHosMilitia

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaMilitia
  name: militia officer's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardMilitia

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaSeniorMilitia
  name: senior militia officer's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardSeniorMilitia

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaMedOfficer
  name: medical officer's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardMedOfficer

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaLrrChief
  name: LRR chief's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardLrrChief

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaPilot
  name: pilot's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardPilot

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaIVK
  name: IVK officer's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardIVK

- type: entity
  parent: IS14_PdaBase
  id: IS14_PdaInvestigator
  name: investigator's PDA
  components:
  - type: Sprite
    sprite: _IS14/Objects/Devices/pda/Security/security.rsi
  - type: Pda
    id: IS14_IdCardInvestigator
