// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._IS14.Medical.BloodDonation;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Medical.BloodDonation;

[GenerateTypedNameReferences]
public sealed partial class BloodDonationConsoleWindow : FancyWindow
{
    public event Action? OnStop;
    public event Action? OnPayout;
    public event Action<int>? OnSetRate;
    public event Action<bool>? OnAutoStop;

    /// <summary>Set while the window is writing server values into its own controls.</summary>
    private bool _applyingState;

    public BloodDonationConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        StopBtn.OnPressed += _ => OnStop?.Invoke();
        PayBtn.OnPressed += _ => OnPayout?.Invoke();
        AutoStopCheck.OnToggled += args => OnAutoStop?.Invoke(args.Pressed);

        RateSpin.SetButtons(new List<int> { -1 }, new List<int> { 1 });
        RateSpin.ValueChanged += args =>
        {
            // Guarded so that redrawing the window from a server state does not bounce that
            // same value straight back as a fresh command.
            if (!_applyingState)
                OnSetRate?.Invoke(args.Value);
        };

        BloodBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = TrackColor };
        PackBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = TrackColor };
        PackBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = PackFill };
    }

    public void UpdateState(BloodDonationConsoleUiState state)
    {
        _applyingState = true;
        ApplyState(state);
        _applyingState = false;
    }

    private void ApplyState(BloodDonationConsoleUiState state)
    {
        // Settings are the console's own and stay live whether or not anybody is on the bed,
        // so they are written before the early return for an empty one.
        RateSpin.IsValid = value => value >= state.MinRate && value <= state.MaxRate;
        RateSpin.OverrideValue(Math.Clamp(state.Rate, state.MinRate, state.MaxRate));

        AutoStopCheck.Pressed = state.AutoStop;
        AutoStopHint.Text = state.AutoStop
            ? Loc.GetString(
                "is14-blood-donation-console-autostop-on",
                ("percent", (int) MathF.Round(state.WarnLevel * 100f)))
            : Loc.GetString("is14-blood-donation-console-autostop-off");

        var hasDonor = state.State is not (BloodDonationState.Unlinked or BloodDonationState.Empty);

        ReadoutPanel.Visible = hasDonor;
        PlaceholderLabel.Visible = !hasDonor;

        if (!hasDonor)
        {
            DonorLabel.Text = Loc.GetString("is14-blood-donation-console-no-donor");
            PlaceholderLabel.Text = Loc.GetString(state.State == BloodDonationState.Unlinked
                ? "is14-blood-donation-console-unlinked"
                : "is14-blood-donation-console-empty");

            SetStatus(
                state.State == BloodDonationState.Unlinked
                    ? "is14-blood-donation-console-status-unlinked"
                    : "is14-blood-donation-console-status-empty",
                Idle);

            StopBtn.Disabled = true;
            PayBtn.Disabled = true;
            BlockedLabel.Visible = false;
            return;
        }

        DonorLabel.Text = state.Donor;

        var (statusKey, statusColor) = state.State switch
        {
            BloodDonationState.Drawing => ("is14-blood-donation-console-status-drawing", Active),
            BloodDonationState.Stalled => ("is14-blood-donation-console-status-stalled", Warning),
            _ => ("is14-blood-donation-console-status-waiting", Idle),
        };

        SetStatus(statusKey, statusColor);

        // The one reading worth shouting about: under the warning line the donor is taking
        // bloodloss damage, and the doctor is the only thing that will stop it.
        var bloodColor = state.BloodLow ? Danger : Good;

        BloodBar.Value = Math.Clamp(state.BloodLevel, 0f, 1f);
        BloodBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = bloodColor };
        BloodLabel.FontColorOverride = bloodColor;
        BloodLabel.Text = Loc.GetString(
            "is14-blood-donation-console-percent",
            ("percent", (int) MathF.Round(state.BloodLevel * 100f)));

        var fill = state.PackCapacity > 0f ? state.PackVolume / state.PackCapacity : 0f;

        PackBar.Value = Math.Clamp(fill, 0f, 1f);
        PackLabel.Text = Loc.GetString(
            "is14-blood-donation-console-units-of",
            ("volume", MathF.Round(state.PackVolume, 1)),
            ("max", MathF.Round(state.PackCapacity, 1)));

        DrawnLabel.Text = Loc.GetString(
            "is14-blood-donation-console-units",
            ("volume", MathF.Round(state.Drawn, 1)));

        QuotaLabel.Text = Loc.GetString(
            "is14-blood-donation-console-units",
            ("volume", MathF.Round(state.QuotaLeft, 1)));

        PurityLabel.Text = Loc.GetString(state.Clean
            ? "is14-blood-donation-console-purity-clean"
            : "is14-blood-donation-console-purity-tainted");
        PurityLabel.FontColorOverride = state.Clean ? Good : Danger;

        PayoutLabel.Text = Loc.GetString("is14-blood-donation-console-credits", ("credits", state.Payout));
        PayoutLabel.FontColorOverride = state.Payout > 0 ? Good : Muted;

        StopBtn.Disabled = !state.CanStop;
        PayBtn.Disabled = !state.CanPay;

        BlockedLabel.Visible = !state.CanPay && state.PayBlockedReason != string.Empty;
        BlockedLabel.Text = state.PayBlockedReason;
    }

    /// <summary>The pill in the patient bar: one word and a colour, readable across the room.</summary>
    private void SetStatus(string locId, Color color)
    {
        StatusLabel.Text = Loc.GetString(locId);
        StatusLabel.FontColorOverride = color;
        StatusPill.PanelOverride = new StyleBoxFlat { BackgroundColor = color.WithAlpha(0.16f) };
    }

    private static readonly Color TrackColor = Color.FromHex("#0D141A");
    private static readonly Color PackFill = Color.FromHex("#8C3F3F");
    private static readonly Color Muted = Color.FromHex("#7A8B99");
    private static readonly Color Idle = Color.FromHex("#7A8B99");
    private static readonly Color Active = Color.FromHex("#3ABB6A");
    private static readonly Color Warning = Color.FromHex("#BB8A3A");
    private static readonly Color Good = Color.FromHex("#3ABB6A");
    private static readonly Color Danger = Color.FromHex("#C4564E");
}
