// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Globalization;
using System.Linq;
using Content.Shared._IS14.Research;
using Content.Shared.Lathe;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._IS14.Research.Editor;

/// <summary>
/// Everything about one topic, in fields: what it is called, what it costs, what it opens, what
/// object it demands first.
/// </summary>
/// <remarks>
/// The panel edits the draft object in place and shouts <see cref="OnChanged"/>; the window owns
/// redrawing the map and re-running the rules. Lists of prototypes are never typed by hand —
/// every id comes out of a picker, because a typo in a recipe id is invisible until the console
/// shows an empty card.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class IS14NodeInspector : BoxContainer
{
    private readonly IPrototypeManager _protoManager;
    private readonly IResourceManager _resources;
    private readonly IResourceCache _cache;
    private readonly SpriteSystem _sprites;

    private readonly List<string> _branches = new();
    private readonly List<LineEdit> _costEdits = new();
    private readonly List<string> _currencies = new();

    private IS14DraftNode? _node;
    private IS14TreeDraft? _draft;
    private int _effect = -1;
    private bool _loading;

    /// <summary>A field changed: the map and the rule check are out of date.</summary>
    public event Action? OnChanged;

    /// <summary>The topic was given a new id; references to the old one have to follow.</summary>
    public event Action<string, string>? OnRenamed;

    public IS14NodeInspector()
    {
        RobustXamlLoader.Load(this);

        var entManager = IoCManager.Resolve<IEntityManager>();

        _protoManager = IoCManager.Resolve<IPrototypeManager>();
        _resources = IoCManager.Resolve<IResourceManager>();
        _cache = IoCManager.Resolve<IResourceCache>();
        _sprites = entManager.System<SpriteSystem>();

        BuildBranches();
        BuildTiers();
        BuildCosts();
        BuildEffectKinds();
        BuildPointTypes();
        Wire();
    }

    public void Clear()
    {
        _node = null;
        Body.Visible = false;
        HintLabel.Visible = true;
    }

    public void Show(IS14DraftNode node, IS14TreeDraft draft)
    {
        _node = node;
        _draft = draft;
        _effect = -1;
        _loading = true;

        Body.Visible = true;
        HintLabel.Visible = false;

        IdEdit.Text = node.Id;
        NameEdit.Text = node.Name;
        SummaryEdit.Text = node.Summary;
        ExclusiveEdit.Text = node.ExclusiveGroup ?? string.Empty;
        PositionXEdit.Text = node.Position.X.ToString();
        PositionYEdit.Text = node.Position.Y.ToString();
        HiddenCheck.Pressed = node.Hidden;

        BranchButton.SelectId(Math.Max(0, _branches.IndexOf(node.Discipline)));
        TierButton.SelectId(Math.Clamp(node.Tier, 1, 5));

        for (var index = 0; index < _currencies.Count; index++)
        {
            _costEdits[index].Text = node.Costs.GetValueOrDefault(_currencies[index]).ToString();
        }

        RefreshIcon();
        RefreshLists();
        RefreshBreakthrough();
        RefreshEffects();

        _loading = false;
    }

    private void Wire()
    {
        Apply(IdEdit, text =>
        {
            if (_node == null || string.IsNullOrWhiteSpace(text) || text == _node.Id)
                return;

            var old = _node.Id;
            _node.Id = text.Trim();
            OnRenamed?.Invoke(old, _node.Id);
        });

        Apply(NameEdit, text => Set(node => node.Name = text));
        Apply(SummaryEdit, text => Set(node => node.Summary = text));
        Apply(ExclusiveEdit, text => Set(node =>
            node.ExclusiveGroup = string.IsNullOrWhiteSpace(text) ? null : text.Trim()));

        Apply(PositionXEdit, text => Set(node =>
            node.Position = new Vector2i(Parse(text, node.Position.X), node.Position.Y)));
        Apply(PositionYEdit, text => Set(node =>
            node.Position = new Vector2i(node.Position.X, Parse(text, node.Position.Y))));

        HiddenCheck.OnToggled += args => Set(node => node.Hidden = args.Pressed);

        BranchButton.OnItemSelected += args =>
        {
            BranchButton.SelectId(args.Id);
            Set(node => node.Discipline = _branches[args.Id]);
        };

        TierButton.OnItemSelected += args =>
        {
            TierButton.SelectId(args.Id);
            Set(node => node.Tier = args.Id);
        };

        IconButton.OnPressed += _ => PickIcon();
        PrereqButton.OnPressed += _ => PickPrerequisites();
        RecipeButton.OnPressed += _ => PickRecipes();

        BreakthroughCheck.OnToggled += args => Set(node =>
        {
            node.Breakthrough = args.Pressed ? node.Breakthrough ?? new IS14DraftSample() : null;
            RefreshBreakthrough();
        });

        Apply(SampleNameEdit, text => Set(node => Sample(node).Name = text));
        Apply(SampleHintEdit, text => Set(node => Sample(node).Hint = text));
        Apply(SamplePayoutEdit, text => Set(node => Sample(node).Payout = Parse(text, 40)));

        SamplePointButton.OnItemSelected += args =>
        {
            SamplePointButton.SelectId(args.Id);
            Set(node => Sample(node).PointType = _currencies[args.Id]);
        };

        SampleButton.OnPressed += _ => PickSamples();

        EffectAddButton.OnPressed += _ => Set(node =>
        {
            node.Effects.Add(new IS14DraftEffect());
            _effect = node.Effects.Count - 1;
            RefreshEffects();
        });

        EffectRemoveButton.OnPressed += _ => Set(node =>
        {
            if (_effect < 0 || _effect >= node.Effects.Count)
                return;

            node.Effects.RemoveAt(_effect);
            _effect = -1;
            RefreshEffects();
        });

        EffectList.SelectMode = ItemList.ItemListSelectMode.Button;
        EffectList.OnItemSelected += args =>
        {
            _effect = args.ItemIndex;
            RefreshEffects();
        };

        EffectKindButton.OnItemSelected += args =>
        {
            EffectKindButton.SelectId(args.Id);
            Set(_ =>
            {
                if (Effect() is not { } effect)
                    return;

                effect.Kind = (IS14DraftEffectKind) args.Id;
                effect.Target = effect.Kind switch
                {
                    IS14DraftEffectKind.Points => "Science",
                    IS14DraftEffectKind.Modifier => "ResearchPayout",
                    _ => "IS14PathologyScanner",
                };

                RefreshEffects();
            });
        };

        Apply(EffectValueEdit, text => Set(_ =>
        {
            if (Effect() is { } effect)
                effect.Value = ParseFloat(text, effect.Value);
        }));

        Apply(EffectDescriptionEdit, text => Set(_ =>
        {
            if (Effect() is { } effect)
                effect.Description = text;
        }));

        EffectTargetButton.OnPressed += _ => PickEffectTarget();
    }

    /// <summary>Text fields commit on Enter and on losing focus, never on every keystroke.</summary>
    private void Apply(LineEdit edit, Action<string> action)
    {
        edit.OnTextEntered += args => action(args.Text);
        edit.OnFocusExit += args => action(args.Text);
    }

    private void Set(Action<IS14DraftNode> action)
    {
        if (_loading || _node == null)
            return;

        action(_node);
        OnChanged?.Invoke();
    }

    private IS14DraftSample Sample(IS14DraftNode node) => node.Breakthrough ??= new IS14DraftSample();

    private IS14DraftEffect? Effect()
        => _node != null && _effect >= 0 && _effect < _node.Effects.Count ? _node.Effects[_effect] : null;

    private void BuildBranches()
    {
        foreach (var discipline in _protoManager.EnumeratePrototypes<TechDisciplinePrototype>()
                     .Where(discipline => discipline.ID.StartsWith("IS14"))
                     .OrderBy(discipline => discipline.ID))
        {
            BranchButton.AddItem(Loc.GetString(discipline.Name), _branches.Count);
            _branches.Add(discipline.ID);
        }
    }

    private void BuildTiers()
    {
        for (var tier = 1; tier <= 5; tier++)
        {
            TierButton.AddItem(tier.ToString(), tier);
        }
    }

    private void BuildCosts()
    {
        foreach (var type in _protoManager.EnumeratePrototypes<ResearchPointTypePrototype>()
                     .OrderBy(type => type.SortOrder))
        {
            var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            var label = new Label
            {
                Text = Loc.GetString(type.ShortName),
                HorizontalExpand = true,
                StyleClasses = { "LabelSubText" },
            };

            var edit = new LineEdit { SetWidth = 90 };
            var currency = type.ID;

            Apply(edit, text => Set(node =>
            {
                var amount = Parse(text, 0);

                if (amount <= 0)
                    node.Costs.Remove(currency);
                else
                    node.Costs[currency] = amount;
            }));

            row.AddChild(label);
            row.AddChild(edit);
            CostContainer.AddChild(row);

            _costEdits.Add(edit);
            _currencies.Add(currency);
        }
    }

    private void BuildPointTypes()
    {
        for (var index = 0; index < _currencies.Count; index++)
        {
            var type = _protoManager.Index<ResearchPointTypePrototype>(_currencies[index]);

            SamplePointButton.AddItem(Loc.GetString(type.ShortName), index);
        }
    }

    private void BuildEffectKinds()
    {
        EffectKindButton.AddItem("Разово очки", (int) IS14DraftEffectKind.Points);
        EffectKindButton.AddItem("Модификатор", (int) IS14DraftEffectKind.Modifier);
        EffectKindButton.AddItem("Выдать предмет", (int) IS14DraftEffectKind.Entity);
    }

    private void RefreshIcon()
    {
        if (_node == null)
            return;

        // Only the tail of the path fits beside the button; the whole of it lives in the
        // tooltip, because a path is what the editor is asked about and not what it shows off.
        IconLabel.Text = Shorten(_node.IconSprite, _node.IconState);
        IconLabel.ToolTip = $"{_node.IconSprite} : {_node.IconState}";

        try
        {
            IconPreview.Texture = _sprites.Frame0(_node.Icon);
        }
        catch (Exception)
        {
            IconPreview.Texture = null;
        }
    }

    private void RefreshLists()
    {
        if (_node == null)
            return;

        PrereqLabel.SetMessage(Dim(_node.Prerequisites.Count > 0
            ? string.Join(", ", _node.Prerequisites)
            : "нет — тема доступна сразу"));

        RecipeLabel.SetMessage(Dim(_node.Recipes.Count > 0
            ? string.Join(", ", _node.Recipes)
            : "ничего не открывает"));
    }

    private void RefreshBreakthrough()
    {
        if (_node == null)
            return;

        var sample = _node.Breakthrough;

        BreakthroughCheck.Pressed = sample != null;
        BreakthroughBox.Visible = sample != null;

        if (sample == null)
            return;

        SampleNameEdit.Text = sample.Name;
        SampleHintEdit.Text = sample.Hint;
        SamplePayoutEdit.Text = sample.Payout.ToString();
        SampleLabel.SetMessage(Dim(sample.Samples.Count > 0
            ? string.Join(", ", sample.Samples)
            : "не выбраны"));
        SamplePointButton.SelectId(Math.Max(0, _currencies.IndexOf(sample.PointType)));
    }

    private void RefreshEffects()
    {
        if (_node == null)
            return;

        EffectList.Clear();

        foreach (var effect in _node.Effects)
        {
            EffectList.AddItem(Describe(effect));
        }

        var current = Effect();

        EffectBox.Visible = current != null;

        if (current == null)
            return;

        EffectKindButton.SelectId((int) current.Kind);
        EffectValueEdit.Text = current.Value.ToString("0.###", CultureInfo.InvariantCulture);
        EffectDescriptionEdit.Text = current.Description;
        EffectTargetLabel.Text = current.Target;
    }

    private static string Describe(IS14DraftEffect effect) => effect.Kind switch
    {
        IS14DraftEffectKind.Points => $"+{(int) effect.Value} {effect.Target}",
        IS14DraftEffectKind.Modifier => $"{effect.Target} {effect.Value:+0.##;-0.##}",
        _ => $"выдать {effect.Target} ×{(int) effect.Value}",
    };

    private void PickIcon()
    {
        if (_node == null)
            return;

        var picker = new IS14SpritePickerWindow(_resources, _cache, _sprites, _node.IconSprite);

        picker.OnPicked += (sprite, state) => Set(node =>
        {
            node.IconSprite = sprite;
            node.IconState = state;
            RefreshIcon();
        });

        picker.OpenCentered();
    }

    private void PickPrerequisites()
    {
        if (_node == null || _draft == null)
            return;

        var entries = _draft.Nodes
            .Where(node => node.Id != _node.Id)
            .Select(node => new IS14PickerEntry(node.Id, node.Name));

        var picker = new IS14ListPickerWindow("Предпосылки", entries, true, _node.Prerequisites);

        picker.OnConfirmed += picked => Set(node =>
        {
            node.Prerequisites = picked;
            RefreshLists();
        });

        picker.OpenCentered();
    }

    private void PickRecipes()
    {
        if (_node == null)
            return;

        var lathe = IoCManager.Resolve<IEntityManager>().System<SharedLatheSystem>();

        var entries = _protoManager.EnumeratePrototypes<LatheRecipePrototype>()
            .Select(recipe => new IS14PickerEntry(
                recipe.ID,
                lathe.GetRecipeName(recipe),
                () => recipe.Result is { } result && _protoManager.TryIndex(result, out EntityPrototype? proto)
                    ? _sprites.Frame0(proto)
                    : null));

        var picker = new IS14ListPickerWindow("Рецепты латов", entries, true, _node.Recipes);

        picker.OnConfirmed += picked => Set(node =>
        {
            node.Recipes = picked;
            RefreshLists();
        });

        picker.OpenCentered();
    }

    private void PickSamples()
    {
        if (_node?.Breakthrough is not { } sample)
            return;

        var picker = new IS14ListPickerWindow("Образцы прорыва", Entities(), true, sample.Samples);

        picker.OnConfirmed += picked => Set(node =>
        {
            Sample(node).Samples = picked;
            RefreshBreakthrough();
        });

        picker.OpenCentered();
    }

    private void PickEffectTarget()
    {
        if (Effect() is not { } effect)
            return;

        IEnumerable<IS14PickerEntry> entries = effect.Kind switch
        {
            IS14DraftEffectKind.Points => _protoManager
                .EnumeratePrototypes<ResearchPointTypePrototype>()
                .Select(type => new IS14PickerEntry(type.ID, Loc.GetString(type.Name))),
            IS14DraftEffectKind.Modifier => _protoManager
                .EnumeratePrototypes<IS14ResearchModifierPrototype>()
                .Select(modifier => new IS14PickerEntry(modifier.ID, modifier.ID)),
            _ => Entities(),
        };

        var picker = new IS14ListPickerWindow("Цель эффекта", entries, false, new[] { effect.Target });

        picker.OnConfirmed += picked => Set(_ =>
        {
            if (picked.Count > 0)
                effect.Target = picked[0];

            RefreshEffects();
        });

        picker.OpenCentered();
    }

    private IEnumerable<IS14PickerEntry> Entities()
    {
        return _protoManager.EnumeratePrototypes<EntityPrototype>()
            .Where(proto => !proto.Abstract && proto.Name.Length > 0)
            .Select(proto => new IS14PickerEntry(proto.ID, proto.Name, () => _sprites.Frame0(proto)));
    }

    /// <summary>
    /// Last two segments of an rsi path plus the state: <c>…/Machines/rnd.rsi : tdoppler</c>.
    /// Enough to recognise the sprite, short enough to leave room for the button.
    /// </summary>
    private static string Shorten(string sprite, string state)
    {
        var parts = sprite.Split('/');
        var tail = parts.Length <= 2 ? sprite : $"…/{parts[^2]}/{parts[^1]}";

        return $"{tail} : {state}";
    }

    /// <summary>
    /// Lists wrap instead of stretching the panel, and wrapping needs rich text — so the grey
    /// of a sub-text label has to come from markup. Brackets in an id would be markup, hence
    /// the escape.
    /// </summary>
    private static FormattedMessage Dim(string text)
        => FormattedMessage.FromMarkupOrThrow($"[color=#9a9a9a]{text.Replace("[", "[[")}[/color]");

    private static int Parse(string text, int fallback)
        => int.TryParse(text.Trim(), out var value) ? value : fallback;

    private static float ParseFloat(string text, float fallback)
        => float.TryParse(text.Trim().Replace(',', '.'), NumberStyles.Float, CultureInfo.InvariantCulture,
            out var value)
            ? value
            : fallback;
}
