// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Utility;

namespace Content.Client._IS14.Research.Editor;

/// <summary>
/// Picks an icon the way a spriter thinks about it: find the <c>.rsi</c> by path, then look at
/// its states and take the one that reads best at 32 pixels.
/// </summary>
/// <remarks>
/// The list is built from the content tree itself (<see cref="IResourceManager.ContentFindFiles"/>
/// over every <c>meta.json</c>), so it shows exactly what this build has — upstream, Goob and our
/// own <c>_IS14</c> folders — and nothing has to be registered anywhere for a new sprite to turn
/// up here. States are drawn through the sprite system, which means what the picker shows is what
/// the console will draw.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class IS14SpritePickerWindow : FancyWindow
{
    private SpriteSystem _sprites = default!;
    private IResourceCache _cache = default!;

    private readonly List<ResPath> _paths = new();

    private ResPath? _path;
    private string? _state;

    /// <summary>Chosen sprite: the rsi path as written in YAML, and the state inside it.</summary>
    public event Action<string, string>? OnPicked;

    /// <summary>
    /// Exists because the XAML compiler demands a parameterless constructor for the root type.
    /// The window is inert until the real constructor hands it the content tree.
    /// </summary>
    public IS14SpritePickerWindow()
    {
        RobustXamlLoader.Load(this);

        Paths.SelectMode = ItemList.ItemListSelectMode.Button;
        States.SelectMode = ItemList.ItemListSelectMode.Button;

        Paths.OnItemSelected += args =>
        {
            if (Paths[args.ItemIndex].Metadata is ResPath path)
                ShowStates(path);
        };

        States.OnItemSelected += args =>
        {
            if (States[args.ItemIndex].Metadata is string state)
                Pick(state);
        };

        PathEdit.OnTextChanged += _ => RefreshPaths();

        ConfirmButton.OnPressed += _ =>
        {
            if (_path == null || _state == null)
                return;

            OnPicked?.Invoke(Relative(_path.Value), _state);
            Close();
        };

        SelectedLabel.Text = "Выберите .rsi слева.";
    }

    public IS14SpritePickerWindow(
        IResourceManager resources,
        IResourceCache cache,
        SpriteSystem sprites,
        string? current = null) : this()
    {
        _sprites = sprites;
        _cache = cache;

        foreach (var file in resources.ContentFindFiles(new ResPath("/Textures/")))
        {
            if (file.Filename != "meta.json")
                continue;

            var directory = file.Directory;

            if (directory.Extension == "rsi")
                _paths.Add(directory);
        }

        _paths.Sort((left, right) => string.Compare(left.ToString(), right.ToString(), StringComparison.Ordinal));

        // Opened from a node that already has a sprite: start where that sprite lives.
        if (current != null)
            PathEdit.Text = current;

        RefreshPaths();
    }

    private void RefreshPaths()
    {
        var filter = PathEdit.Text.Trim();

        Paths.Clear();

        var shown = 0;

        foreach (var path in _paths)
        {
            var text = Relative(path);

            if (filter.Length > 0 && !text.Contains(filter, StringComparison.OrdinalIgnoreCase))
                continue;

            if (shown++ >= 300)
                break;

            Paths.AddItem(text, metadata: path);
        }

        PathCountLabel.Text = shown >= 300
            ? $"Показаны первые 300 из {_paths.Count}: уточните путь."
            : $"Найдено: {shown} из {_paths.Count}";
    }

    private void ShowStates(ResPath path)
    {
        _path = path;
        _state = null;
        ConfirmButton.Disabled = true;
        States.Clear();
        SelectedLabel.Text = Relative(path);

        foreach (var state in StatesOf(path))
        {
            var specifier = new SpriteSpecifier.Rsi(path, state);

            try
            {
                States.AddItem(state, _sprites.Frame0(specifier), metadata: state, iconScale: 2f);
            }
            catch (Exception)
            {
                // A state the renderer refuses (wrong directions, broken meta) is still worth
                // listing by name, just without a picture.
                States.AddItem(state, metadata: state);
            }
        }

        if (States.Count == 0)
            SelectedLabel.Text = $"{Relative(path)} — состояний не найдено";
    }

    private void Pick(string state)
    {
        if (_path == null)
            return;

        _state = state;
        ConfirmButton.Disabled = false;
        ResultLabel.Text = $"{Relative(_path.Value)} : {state}";

        try
        {
            PreviewRect.Texture = _sprites.Frame0(new SpriteSpecifier.Rsi(_path.Value, state));
        }
        catch (Exception)
        {
            PreviewRect.Texture = null;
        }
    }

    private IEnumerable<string> StatesOf(ResPath path)
    {
        if (!_cache.TryGetResource<RSIResource>(path, out var resource))
            return Array.Empty<string>();

        return resource.RSI
            .Select(state => state.StateId.Name)
            .Where(name => name != null)
            .Cast<string>()
            .Order();
    }

    /// <summary>Path as YAML wants it: without the leading <c>/Textures/</c>.</summary>
    private static string Relative(ResPath path)
    {
        var text = path.ToString().Replace('\\', '/').TrimStart('/');

        return text.StartsWith("Textures/") ? text["Textures/".Length..] : text;
    }
}
