// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Research.Editor;

/// <summary>
/// One thing that can be picked: its id, what to call it in the list, and how to draw it.
/// </summary>
/// <remarks>
/// The icon is a function, not a texture: these lists run to thousands of prototypes and loading
/// every sprite to show forty rows would stall the window. Only the rows actually drawn ask.
/// </remarks>
public readonly record struct IS14PickerEntry(string Id, string Label, Func<Texture?>? Icon = null);

/// <summary>
/// The searchable list everything in the editor is chosen from: a lathe recipe, a breakthrough
/// sample, a modifier, a prerequisite.
/// </summary>
/// <remarks>
/// One window for all of them on purpose. The lists are long — hundreds of recipes, thousands of
/// prototypes — so the only usable interface is "type three letters and look at the icons", and
/// writing that once means every field in the editor gets it.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class IS14ListPickerWindow : FancyWindow
{
    private List<IS14PickerEntry> _entries = new();
    private HashSet<string> _selected = new();
    private bool _multiple;

    /// <summary>Confirmed selection. Empty is a legitimate answer: it clears the field.</summary>
    public event Action<List<string>>? OnConfirmed;

    /// <summary>
    /// Exists for the XAML compiler, which insists on a parameterless constructor for the root
    /// type. A picker built this way is empty until the real constructor fills it.
    /// </summary>
    public IS14ListPickerWindow()
    {
        RobustXamlLoader.Load(this);

        Items.SelectMode = ItemList.ItemListSelectMode.Button;
        Items.OnItemSelected += OnItemPressed;

        SearchEdit.OnTextChanged += _ => Refresh();
        ClearButton.OnPressed += _ =>
        {
            _selected.Clear();
            Refresh();
        };

        ConfirmButton.OnPressed += _ =>
        {
            OnConfirmed?.Invoke(_selected.ToList());
            Close();
        };

        Refresh();
    }

    public IS14ListPickerWindow(
        string title,
        IEnumerable<IS14PickerEntry> entries,
        bool multiple = false,
        IEnumerable<string>? selected = null) : this()
    {
        Title = title;
        // Sorted by the lowercased id rather than through a StringComparer: the sandbox does
        // not allow that type in content assemblies.
        _entries = entries.OrderBy(entry => entry.Id.ToLowerInvariant()).ToList();
        _selected = new HashSet<string>(selected ?? Array.Empty<string>());
        _multiple = multiple;

        HintLabel.Text = multiple
            ? "Клик переключает. Можно выбрать несколько."
            : "Клик выбирает один вариант.";

        Refresh();
    }

    private void OnItemPressed(ItemList.ItemListSelectedEventArgs args)
    {
        if (Items[args.ItemIndex].Metadata is not string id)
            return;

        if (!_multiple)
        {
            _selected.Clear();
            _selected.Add(id);
            OnConfirmed?.Invoke(_selected.ToList());
            Close();
            return;
        }

        if (!_selected.Add(id))
            _selected.Remove(id);

        Refresh();
    }

    private void Refresh()
    {
        var filter = SearchEdit.Text.Trim();

        Items.Clear();

        var shown = 0;

        foreach (var entry in _entries)
        {
            var picked = _selected.Contains(entry.Id);

            if (!picked && filter.Length > 0 && !Matches(entry, filter))
                continue;

            // Chosen entries stay visible whatever the filter says, so a long multi-select is
            // not a memory game.
            if (shown++ > 400)
                break;

            var mark = picked ? "✔ " : string.Empty;
            var label = entry.Label == entry.Id ? entry.Id : $"{entry.Label}  ({entry.Id})";

            Texture? icon = null;

            try
            {
                icon = entry.Icon?.Invoke();
            }
            catch (Exception)
            {
                // A prototype with a broken or missing sprite still belongs in the list.
            }

            Items.AddItem($"{mark}{label}", icon, metadata: entry.Id);
        }

        CountLabel.Text = _selected.Count > 0
            ? $"Выбрано: {_selected.Count}"
            : $"Всего: {_entries.Count}";
    }

    private static bool Matches(IS14PickerEntry entry, string filter)
    {
        return entry.Id.Contains(filter, StringComparison.OrdinalIgnoreCase)
               || entry.Label.Contains(filter, StringComparison.OrdinalIgnoreCase);
    }
}
