# base clothing

- type: entity
  abstract: true
  parent: ClothingOuterBase
  id: ClothingOuterIS14Base
  components:
  - type: EmitSoundOnPickup
    sound:
      path: /Audio/_Goobstation/Items/handling/cloth_pickup.ogg
      params:
        volume: -4
  - type: EmitSoundOnDrop
    sound:
      path: /Audio/_Goobstation/Items/handling/cloth_drop.ogg
      params:
        volume: -4

- type: entity
  abstract: true
  parent: ClothingOuterStorageBase
  id: ClothingOuterIS14LabCoatBase
  components:
  - type: Armor
    coverage:
    - Chest
    - Groin
    - Tail
    - Arm
    - Leg
    modifiers:
      coefficients:
        Caustic: 0.65

- type: entity
  abstract: true
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtIS14Base
  components:
  - type: EmitSoundOnPickup
    sound:
      path: /Audio/_Goobstation/Items/handling/cloth_pickup.ogg
      params:
        volume: -4
  - type: EmitSoundOnDrop
    sound:
      path: /Audio/_Goobstation/Items/handling/cloth_drop.ogg
      params:
        volume: -4
  - type: EmitSoundOnLand
    sound:
      path: /Audio/_Goobstation/Items/handling/cloth_drop.ogg
      params:
        volume: -4

- type: entity
  abstract: true
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitIS14Base
  components:
  - type: EmitSoundOnPickup
    sound:
      path: /Audio/_Goobstation/Items/handling/cloth_pickup.ogg
      params:
        volume: -4
  - type: EmitSoundOnDrop
    sound:
      path: /Audio/_Goobstation/Items/handling/cloth_drop.ogg
      params:
        volume: -4
  - type: EmitSoundOnLand
    sound:
      path: /Audio/_Goobstation/Items/handling/cloth_drop.ogg
      params:
        volume: -4

- type: entity
  abstract: true
  parent: [ClothingOuterIS14Base, BaseFoldable]
  id: ClothingOuterIS14FoldableBase
  components:
  - type: Appearance
  - type: Foldable
    canFoldInsideContainer: true
    unfoldVerbText: fold-zip-verb
    foldVerbText: fold-unzip-verb
  - type: FoldableClothing
    foldedEquippedPrefix: open
    foldedHeldPrefix: open
  - type: Sprite
    layers:
    - state: icon
      map: [ "unfoldedLayer" ]
    - state: icon-open
      map: [ "foldedLayer" ]
      visible: false
