using System.Globalization;
using Content.Client._IS14.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Apps;

/// <summary>
///     Calculator. Marked ClientOnly in its prototype: it never asks the server for anything,
///     which is the point — an app that needs no data should cost no traffic (Docs §4.5).
/// </summary>
public sealed class CalculatorAppUi : IS14OsAppUi
{
    private CalculatorAppFragment? _fragment;

    private CalculatorAppFragment Fragment => _fragment ??= new CalculatorAppFragment();

    public override string AppId => "AppCalculator";

    public override Control Root => Fragment;

    public override void ApplyTheme(IS14ThemePalette palette)
    {
        Fragment.ApplyTheme(palette);
    }
}

[GenerateTypedNameReferences]
public sealed partial class CalculatorAppFragment : BoxContainer
{
    private static readonly string[] Layout =
    {
        "C", "±", "%", "÷",
        "7", "8", "9", "×",
        "4", "5", "6", "−",
        "1", "2", "3", "+",
        "0", ".", "⌫", "=",
    };

    private IS14ThemePalette _palette = IS14ThemePalette.Default;

    private double _accumulator;
    private string _pending = string.Empty;
    private string _entry = "0";
    private bool _fresh = true;

    public CalculatorAppFragment()
    {
        RobustXamlLoader.Load(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        BuildKeys();
        Refresh();
    }

    private void BuildKeys()
    {
        foreach (var key in Layout)
        {
            var tile = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Caption = key,
                HorizontalExpand = true,
                VerticalExpand = true,
                MinSize = new System.Numerics.Vector2(0, 26),
            };

            var captured = key;
            tile.OnPressed += _ => Press(captured);
            Keys.AddChild(tile);
        }
    }

    private void Press(string key)
    {
        switch (key)
        {
            case "C":
                _accumulator = 0;
                _pending = string.Empty;
                _entry = "0";
                _fresh = true;
                break;

            case "⌫":
                _entry = _entry.Length > 1 ? _entry[..^1] : "0";
                break;

            case "±":
                _entry = _entry.StartsWith('-') ? _entry[1..] : "-" + _entry;
                break;

            case "%":
                _entry = Format(Parse(_entry) / 100d);
                break;

            case "+" or "−" or "×" or "÷":
                Apply(key);
                break;

            case "=":
                Apply(string.Empty);
                break;

            case ".":
                if (!_entry.Contains('.'))
                    _entry = _fresh ? "0." : _entry + ".";

                _fresh = false;
                break;

            default:
                _entry = _fresh || _entry == "0" ? key : _entry + key;
                _fresh = false;
                break;
        }

        Refresh();
    }

    private void Apply(string next)
    {
        var value = Parse(_entry);

        _accumulator = _pending switch
        {
            "+" => _accumulator + value,
            "−" => _accumulator - value,
            "×" => _accumulator * value,
            "÷" => value == 0 ? double.NaN : _accumulator / value,
            _ => value,
        };

        _entry = Format(_accumulator);
        _pending = next;
        _fresh = true;
    }

    private static double Parse(string text)
    {
        return double.TryParse(text, CultureInfo.InvariantCulture, out var value) ? value : 0d;
    }

    private static string Format(double value)
    {
        if (double.IsNaN(value) || double.IsInfinity(value))
            return "ERR";

        return Math.Round(value, 6).ToString(CultureInfo.InvariantCulture);
    }

    private void Refresh()
    {
        DisplayLabel.Text = _entry;
        ExpressionLabel.Text = _pending.Length == 0
            ? string.Empty
            : $"{Format(_accumulator)} {_pending}";
    }

    public void ApplyTheme(IS14ThemePalette palette)
    {
        _palette = palette;

        DisplayPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.Backdrop,
            BorderColor = palette.Border,
            BorderThickness = new Thickness(1),
        };

        DisplayLabel.FontColorOverride = palette.Accent;
        ExpressionLabel.FontColorOverride = palette.Muted;

        foreach (var child in Keys.Children)
        {
            if (child is IconTile tile)
                tile.Palette = palette;
        }
    }
}
