using System.Linq;
using System.IO;
using Content.Client._IS14.Controls;
using Content.Client._IS14.OS.Shell;
using Content.Shared._IS14.OS.Files;
using Content.Shared._IS14.OS.Prototypes;
using Content.Shared._IS14.OS.UI;
using Content.Shared._IS14.OS.UI.Apps;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Apps;

/// <summary>
///     Files: installed software and stored files, and what each costs in memory. Memory is the
///     platform's main constraint, so this app is where the player actually feels it (Docs §7.2).
/// </summary>
public sealed class FilesAppUi : IS14OsAppUi
{
    private FilesAppFragment? _fragment;

    private FilesAppFragment Fragment => _fragment ??= new FilesAppFragment();

    public override string AppId => "AppFiles";

    public override Control Root => Fragment;

    public override void Setup(IS14OsBui bui)
    {
        base.Setup(bui);

        Fragment.OnUninstall += app => Bui.SendUninstall(app);
        Fragment.OnOpenFile += file => SendAppEvent(AppId, new OsFileOpenEvent(file));
        Fragment.OnDeleteFile += file => SendAppEvent(AppId, new OsFileDeleteEvent(file));
        Fragment.OnRenameFile += (file, name) => SendAppEvent(AppId, new OsFileRenameEvent(file, name));
        Fragment.OnDiskInstall += app => SendAppEvent(AppId, new OsDiskInstallEvent(app));
        Fragment.OnDiskCopy += (file, toDisk) => SendAppEvent(AppId, new OsDiskCopyEvent(file, toDisk));
        Fragment.OnDiskDelete += file => SendAppEvent(AppId, new OsDiskDeleteEvent(file));
        Fragment.OnDismissError += () => SendAppEvent(AppId, new OsFilesDismissErrorEvent());
    }

    public override void UpdateShell(OsShellState shell)
    {
        Fragment.UpdateShell(shell);
    }

    public override void UpdateState(IS14OsAppState state)
    {
        if (state is OsFilesState files)
            Fragment.UpdateState(files);
    }

    public override void ApplyTheme(IS14ThemePalette palette)
    {
        Fragment.ApplyTheme(palette);
    }
}

[GenerateTypedNameReferences]
public sealed partial class FilesAppFragment : BoxContainer
{
    private const string SectionApps = "apps";
    private const string SectionFiles = "files";
    private const string SectionDisk = "disk";

    /// <summary>Above this share of memory the readout warns; above the second it shouts.</summary>
    private const float WarnAt = 0.7f;
    private const float FullAt = 0.9f;

    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private readonly SpriteSystem _sprites;
    private readonly Texture? _deleteIcon;
    private readonly Texture? _openIcon;
    private readonly Texture? _renameIcon;
    private readonly Texture? _toDeviceIcon;
    private readonly Texture? _toDiskIcon;
    private readonly Texture? _diskIcon;

    /// <summary>The file whose name is being edited in the rename bar, if any.</summary>
    private int? _renaming;

    private IS14ThemePalette _palette = IS14ThemePalette.Default;
    private OsShellState? _shell;
    private OsFilesState? _files;
    private string _section = SectionApps;

    private int _previewedId = -1;

    public event Action<string>? OnUninstall;
    public event Action<int?>? OnOpenFile;
    public event Action<int>? OnDeleteFile;
    public event Action<int, string>? OnRenameFile;
    public event Action<string>? OnDiskInstall;
    public event Action<int, bool>? OnDiskCopy;
    public event Action<int>? OnDiskDelete;
    public event Action? OnDismissError;

    public FilesAppFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _sprites = _sysMan.GetEntitySystem<SpriteSystem>();
        _deleteIcon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Delete);
        _openIcon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Open);
        _renameIcon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Rename);
        _toDeviceIcon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Download);
        _toDiskIcon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.SaveFile);
        _diskIcon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Disk);

        RenameEdit.PlaceHolder = Loc.GetString("is14-os-files-rename-placeholder");
        RenameEdit.OnTextEntered += _ => ConfirmRename();

        RenameConfirmButton.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Save);
        RenameConfirmButton.ToolTip = Loc.GetString("is14-os-files-rename-confirm");
        RenameConfirmButton.OnPressed += _ => ConfirmRename();

        RenameCancelButton.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Close);
        RenameCancelButton.ToolTip = Loc.GetString("is14-os-files-rename-cancel");
        RenameCancelButton.OnPressed += _ => EndRename();

        MemoryIcon.Texture = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Memory);
        MemoryCaption.Text = Loc.GetString("is14-os-files-memory-caption");

        // Used memory is the bad direction, so the usual "low is bad" colours are flipped.
        MemoryBar.LowThreshold = WarnAt;
        MemoryBar.WarnThreshold = FullAt;

        DismissButton.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Close);
        DismissButton.ToolTip = Loc.GetString("is14-os-hub-dismiss");
        DismissButton.OnPressed += _ => OnDismissError?.Invoke();

        PreviewCloseButton.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Close);
        PreviewCloseButton.ToolTip = Loc.GetString("is14-os-files-close-preview");
        PreviewCloseButton.OnPressed += _ => OnOpenFile?.Invoke(null);

        Sections.OnChoiceSelected += id =>
        {
            _section = id;
            EndRename();
            Rebuild();
        };
    }

    public void UpdateShell(OsShellState shell)
    {
        _shell = shell;

        var used = shell.MemorySystem + shell.MemoryUsed;
        var total = Math.Max(1, shell.MemoryTotal);
        var free = Math.Max(0, shell.MemoryTotal - used);

        MemoryValue.Text = Loc.GetString("is14-os-files-memory", ("used", used), ("total", shell.MemoryTotal));
        MemoryBreakdown.Text = Loc.GetString("is14-os-files-memory-breakdown",
            ("system", shell.MemorySystem),
            ("apps", Math.Max(0, shell.MemoryUsed - shell.MemoryFiles - shell.MemoryData)),
            ("data", shell.MemoryData),
            ("files", shell.MemoryFiles));
        MemoryFree.Text = Loc.GetString("is14-os-files-memory-free", ("free", free));

        var fill = Math.Clamp((float) used / total, 0f, 1f);
        MemoryBar.Fraction = fill;

        var color = fill > FullAt ? _palette.Bad : fill > WarnAt ? _palette.Warn : _palette.Good;
        MemoryValue.FontColorOverride = color;
        MemoryFree.FontColorOverride = color;

        Rebuild();
    }

    public void UpdateState(OsFilesState state)
    {
        _files = state;

        ErrorPanel.Visible = state.Error != null;
        if (state.Error != null)
            ErrorLabel.Text = Loc.GetString(state.Error);

        UpdatePreview(state);
        Rebuild();
    }

    #region Preview

    private void UpdatePreview(OsFilesState state)
    {
        var open = state.Open;
        var showing = open != null;

        PreviewBox.Visible = showing;
        ListScroll.Visible = !showing;
        Sections.Visible = !showing;

        if (showing)
            EndRename();

        if (open == null)
        {
            _previewedId = -1;
            return;
        }

        var meta = state.Files.FirstOrDefault(f => f.Id == open.Id);
        PreviewTitle.Text = meta?.Name ?? string.Empty;
        PreviewMeta.Text = meta == null
            ? string.Empty
            : Loc.GetString("is14-os-files-preview-meta",
                ("size", meta.Size),
                ("author", meta.Author ?? Loc.GetString("is14-os-status-unknown")));

        // Decoding a PNG is not free, so only do it when the payload actually changed.
        if (_previewedId == open.Id)
            return;

        _previewedId = open.Id;

        PreviewImage.Visible = false;
        PreviewTextScroll.Visible = false;

        if (open.Data is { Length: > 0 } bytes)
        {
            try
            {
                using var stream = new MemoryStream(bytes);
                PreviewImage.Texture = Texture.LoadFromPNGStream(stream);
                PreviewImage.Visible = true;
            }
            catch (Exception)
            {
                // A corrupt or hostile payload must not take the whole UI down with it.
                PreviewText.SetMessage(Loc.GetString("is14-os-files-preview-broken"));
                PreviewTextScroll.Visible = true;
            }

            return;
        }

        // Documents carry their formatting as markup, so a file written in the editor has to
        // read here the way it looked there. Permissive: the text may be anything at all.
        var text = open.Text ?? string.Empty;

        FormattedMessage message;
        try
        {
            message = FormattedMessage.FromMarkupPermissive(text);
        }
        catch (Exception)
        {
            message = FormattedMessage.FromUnformatted(text);
        }

        PreviewText.SetMessage(message, IS14DocumentText.Tags, _palette.Text);
        PreviewTextScroll.Visible = true;
    }

    #endregion

    #region Lists

    private void Rebuild()
    {
        if (_shell == null)
            return;

        // The file can go away underneath the rename bar: deleted from the gallery, or the
        // memory wiped. Editing the name of something that no longer exists is a dead end.
        if (_renaming is { } renaming && _files?.Files.All(f => f.Id != renaming) != false)
        {
            _renaming = null;
            RenamePanel.Visible = false;
            RenameEdit.Text = string.Empty;
        }

        RebuildSections();

        if (PreviewBox.Visible)
            return;

        EntryList.RemoveAllChildren();

        if (_section == SectionApps)
            RebuildApps(_shell);
        else if (_section == SectionDisk)
            RebuildDisk();
        else
            RebuildFiles();
    }

    private void RebuildSections()
    {
        var fileCount = _files?.Files.Count ?? 0;

        var items = new List<ChoiceStripItem>
        {
            new(SectionApps, Loc.GetString("is14-os-files-section-apps")),
            new(SectionFiles, Loc.GetString("is14-os-files-section-files", ("count", fileCount))),
        };

        if (_files?.Disk != null)
            items.Add(new ChoiceStripItem(SectionDisk, Loc.GetString("is14-os-files-section-disk"), _diskIcon));
        else if (_section == SectionDisk)
            _section = SectionFiles;   // the disk was pulled out from under the tab

        Sections.SetItems(items, _section);
    }

    /// <summary>
    ///     What is on the disk, and the two things worth doing with it: install the software,
    ///     take the files. Copying the other way lives on the device file rows instead, next to
    ///     the file being copied, because that is where the player is looking at it.
    /// </summary>
    private void RebuildDisk()
    {
        if (_files?.Disk is not { } disk)
            return;

        EntryList.AddChild(new StatRow
        {
            Palette = _palette,
            Icon = _diskIcon,
            Caption = disk.Name,
            Value = Loc.GetString("is14-os-files-memory", ("used", disk.Used), ("total", disk.Capacity)),
            Margin = new Thickness(0, 0, 0, 3),
        });

        if (disk.Apps.Count == 0 && disk.Files.Count == 0)
        {
            EntryList.AddChild(new Label
            {
                Text = Loc.GetString("is14-os-files-disk-empty"),
                FontColorOverride = _palette.Muted,
            });

            return;
        }

        foreach (var appId in disk.Apps)
        {
            if (appId.Id is not { } id || !_proto.TryIndex<IS14OsAppPrototype>(id, out var app))
                continue;

            var row = new StatRow
            {
                Palette = _palette,
                Framed = true,
                Icon = IS14OsStyle.Resolve(_sprites, app.Icon ?? IS14OsStyle.Fallback),
                Caption = Loc.GetString(app.Name),
                Value = Loc.GetString("is14-os-files-size", ("size", app.Size)),
                Margin = new Thickness(0, 0, 0, 2),
                ToolTip = app.Description == null ? null : Loc.GetString(app.Description),
            };

            var already = _shell?.Installed.Any(a => a.Id == id) == true;
            var incompatible = disk.Incompatible.Any(a => a.Id == id);

            // A program that cannot run here is not a button worth pressing: say so on the row
            // rather than letting the press be the way the player finds out.
            if (incompatible)
                row.ModulateSelfOverride = _palette.Muted;

            var install = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = _toDeviceIcon,
                IconSize = 12,
                Disabled = already || incompatible,
                ToolTip = Loc.GetString(incompatible
                    ? "is14-os-disk-error-device"
                    : already
                        ? "is14-os-hub-installed"
                        : "is14-os-files-disk-install"),
            };

            install.OnPressed += _ =>
            {
                install.Disabled = true;
                OnDiskInstall?.Invoke(id);
            };

            row.SetTrailing(install);
            EntryList.AddChild(row);
        }

        foreach (var file in disk.Files)
        {
            var row = new StatRow
            {
                Palette = _palette,
                Framed = true,
                Icon = IS14OsStyle.Resolve(_sprites,
                    file.Kind == OsFileKind.Photo ? IS14OsStyle.Photo : IS14OsStyle.Note),
                Caption = file.Name,
                Value = Loc.GetString("is14-os-files-size", ("size", file.Size)),
                Margin = new Thickness(0, 0, 0, 2),
            };

            var buttons = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            var id = file.Id;

            var copy = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = _toDeviceIcon,
                IconSize = 12,
                ToolTip = Loc.GetString("is14-os-files-disk-copy-in"),
                Margin = new Thickness(0, 0, 3, 0),
            };
            copy.OnPressed += _ => OnDiskCopy?.Invoke(id, false);
            buttons.AddChild(copy);

            if (disk.Writable)
            {
                var erase = new IconTile
                {
                    Palette = _palette,
                    Compact = true,
                    Icon = _deleteIcon,
                    IconSize = 12,
                    ToolTip = Loc.GetString("is14-os-files-disk-erase"),
                };

                erase.OnPressed += _ =>
                {
                    erase.Disabled = true;
                    OnDiskDelete?.Invoke(id);
                };

                buttons.AddChild(erase);
            }

            row.SetTrailing(buttons);
            EntryList.AddChild(row);
        }
    }

    private void RebuildApps(OsShellState shell)
    {
        EntryList.AddChild(new StatRow
        {
            Palette = _palette,
            Caption = Loc.GetString("is14-os-files-system"),
            Value = Loc.GetString("is14-os-files-size", ("size", shell.MemorySystem)),
            Margin = new Thickness(0, 0, 0, 3),
        });

        foreach (var appId in shell.Installed)
        {
            if (appId.Id is not { } id || !_proto.TryIndex<IS14OsAppPrototype>(id, out var app))
                continue;

            if (app.Undeletable)
                continue;

            var row = new StatRow
            {
                Palette = _palette,
                Framed = true,
                Icon = IS14OsStyle.Resolve(_sprites, app.Icon ?? IS14OsStyle.Fallback),
                Caption = Loc.GetString(app.Name),
                Value = Loc.GetString("is14-os-files-size", ("size", app.Size)),
                Margin = new Thickness(0, 0, 0, 2),
                ToolTip = app.Description == null ? null : Loc.GetString(app.Description),
            };

            var button = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = _deleteIcon,
                IconSize = 12,
                ToolTip = Loc.GetString("is14-os-files-uninstall"),
            };

            button.OnPressed += _ =>
            {
                // The list only refreshes on the next state push, so lock the button now —
                // otherwise a second click asks to remove something already gone.
                button.Disabled = true;
                OnUninstall?.Invoke(id);
            };

            row.SetTrailing(button);
            EntryList.AddChild(row);
        }
    }

    private void RebuildFiles()
    {
        if (_files == null || _files.Files.Count == 0)
        {
            EntryList.AddChild(new Label
            {
                Text = Loc.GetString("is14-os-files-empty"),
                FontColorOverride = _palette.Muted,
            });

            return;
        }

        foreach (var file in _files.Files)
        {
            var row = new StatRow
            {
                Palette = _palette,
                Framed = true,
                Icon = IS14OsStyle.Resolve(_sprites,
                    file.Kind == OsFileKind.Photo ? IS14OsStyle.Photo : IS14OsStyle.Note),
                Caption = file.Name,
                Value = Loc.GetString("is14-os-files-size", ("size", file.Size)),
                Margin = new Thickness(0, 0, 0, 2),
            };

            var buttons = new BoxContainer { Orientation = LayoutOrientation.Horizontal };

            var open = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = _openIcon,
                IconSize = 12,
                ToolTip = Loc.GetString("is14-os-files-open"),
                Margin = new Thickness(0, 0, 3, 0),
            };
            open.OnPressed += _ => OnOpenFile?.Invoke(file.Id);

            var rename = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = _renameIcon,
                IconSize = 12,
                Selected = _renaming == file.Id,
                ToolTip = Loc.GetString("is14-os-files-rename"),
                Margin = new Thickness(0, 0, 3, 0),
            };

            var id = file.Id;
            var name = file.Name;
            rename.OnPressed += _ => BeginRename(id, name);

            var delete = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = _deleteIcon,
                IconSize = 12,
                ToolTip = Loc.GetString("is14-os-files-delete"),
            };
            delete.OnPressed += _ =>
            {
                delete.Disabled = true;
                OnDeleteFile?.Invoke(file.Id);
            };

            buttons.AddChild(open);

            // Only offered when a writable disk is actually in the drive: a button that is
            // always there and usually does nothing teaches the player to ignore it.
            if (_files.Disk is { Writable: true })
            {
                var toDisk = new IconTile
                {
                    Palette = _palette,
                    Compact = true,
                    Icon = _toDiskIcon,
                    IconSize = 12,
                    ToolTip = Loc.GetString("is14-os-files-disk-copy-out"),
                    Margin = new Thickness(0, 0, 3, 0),
                };

                var copyId = file.Id;
                toDisk.OnPressed += _ => OnDiskCopy?.Invoke(copyId, true);
                buttons.AddChild(toDisk);
            }

            buttons.AddChild(rename);
            buttons.AddChild(delete);
            row.SetTrailing(buttons);

            EntryList.AddChild(row);
        }
    }

    #endregion

    #region Renaming

    private void BeginRename(int file, string name)
    {
        _renaming = file;

        RenamePanel.Visible = true;
        RenameEdit.Text = name;
        RenameEdit.GrabKeyboardFocus();

        // Select the old name so the first keystroke replaces it, as any rename box does.
        RenameEdit.CursorPosition = name.Length;
        RenameEdit.SelectionStart = 0;

        Rebuild();
    }

    private void ConfirmRename()
    {
        if (_renaming is { } file && RenameEdit.Text.Trim().Length > 0)
            OnRenameFile?.Invoke(file, RenameEdit.Text);

        EndRename();
    }

    private void EndRename()
    {
        if (_renaming == null)
            return;

        _renaming = null;
        RenamePanel.Visible = false;
        RenameEdit.Text = string.Empty;

        Rebuild();
    }

    #endregion

    public void ApplyTheme(IS14ThemePalette palette)
    {
        _palette = palette;

        DismissButton.Palette = palette;
        ErrorLabel.FontColorOverride = palette.Bad;
        ErrorPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.Panel,
            BorderColor = palette.Bad,
            BorderThickness = new Thickness(1),
        };

        MemoryPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.PanelRaised,
            BorderColor = palette.Border,
            BorderThickness = new Thickness(1),
        };

        PreviewPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.Backdrop,
            BorderColor = palette.Border,
            BorderThickness = new Thickness(1),
        };

        MemoryIcon.ModulateSelfOverride = palette.Accent;
        MemoryCaption.FontColorOverride = palette.Text;
        MemoryBreakdown.FontColorOverride = palette.Muted;
        PreviewTitle.FontColorOverride = palette.Accent;
        PreviewMeta.FontColorOverride = palette.Muted;

        Sections.Palette = palette;
        PreviewCloseButton.Palette = palette;
        RenameConfirmButton.Palette = palette;
        RenameCancelButton.Palette = palette;

        RenamePanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.PanelRaised,
            BorderColor = palette.Accent,
            BorderThickness = new Thickness(1),
        };

        RenameEdit.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.Backdrop,
            BorderColor = palette.Border,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginTopOverride = 2,
            ContentMarginBottomOverride = 2,
        };

        MemoryBar.BackgroundColor = palette.Backdrop;
        MemoryBar.TickColor = palette.Border;
        MemoryBar.LowColor = palette.Good;
        MemoryBar.WarnColor = palette.Warn;
        MemoryBar.FullColor = palette.Bad;

        if (_shell != null)
            UpdateShell(_shell);
    }
}
