using System.IO;
using System.Linq;
using Content.Client._IS14.Controls;
using Content.Client._IS14.OS.Shell;
using Content.Shared._IS14.OS.Files;
using Content.Shared._IS14.OS.UI;
using Content.Shared._IS14.OS.UI.Apps;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Apps;

/// <summary>
///     Gallery: the device's photos as a contact sheet, and one of them at full size.
/// </summary>
public sealed class GalleryAppUi : IS14OsAppUi
{
    private GalleryAppFragment? _fragment;

    private GalleryAppFragment Fragment => _fragment ??= new GalleryAppFragment();

    public override string AppId => "AppGallery";

    public override Control Root => Fragment;

    public override void Setup(IS14OsBui bui)
    {
        base.Setup(bui);

        Fragment.OnView += file => SendAppEvent(AppId, new OsGalleryViewEvent(file));
        Fragment.OnDelete += file => SendAppEvent(AppId, new OsGalleryDeleteEvent(file));
    }

    public override void UpdateShell(OsShellState shell)
    {
        Fragment.UpdateShell(shell);
    }

    public override void UpdateState(IS14OsAppState state)
    {
        if (state is OsGalleryState gallery)
            Fragment.UpdateState(gallery);
    }

    public override void ApplyTheme(IS14ThemePalette palette)
    {
        Fragment.ApplyTheme(palette);
    }
}

[GenerateTypedNameReferences]
public sealed partial class GalleryAppFragment : BoxContainer
{
    /// <summary>Side of a contact-sheet thumbnail, in virtual pixels.</summary>
    private const float ThumbSize = 78f;

    /// <summary>Decoded photos held at once. Textures are not free and a device can hold many.</summary>
    private const int MaxCached = 24;

    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private readonly SpriteSystem _sprites;

    /// <summary>Decoded photos by file id. A null value means the payload was unreadable.</summary>
    private readonly Dictionary<int, Texture?> _photos = new();

    private IS14ThemePalette _palette = IS14ThemePalette.Default;
    private OsGalleryState? _state;

    private int? _open;
    private int? _request;
    private int _misses;
    private OsGalleryState? _accounted;

    public event Action<int?>? OnView;
    public event Action<int>? OnDelete;

    public GalleryAppFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _sprites = _sysMan.GetEntitySystem<SpriteSystem>();

        BackButton.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Back);
        BackButton.ToolTip = Loc.GetString("is14-os-gallery-back");
        BackButton.OnPressed += _ => Open(null);

        DeleteButton.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Delete);
        DeleteButton.ToolTip = Loc.GetString("is14-os-gallery-delete");
        DeleteButton.OnPressed += _ =>
        {
            if (_open is not { } id)
                return;

            // The list only refreshes on the next state push, so lock the button now.
            DeleteButton.Disabled = true;
            Open(null);
            OnDelete?.Invoke(id);
        };

        EmptyLabel.Text = Loc.GetString("is14-os-gallery-empty");
    }

    #region State

    public void UpdateShell(OsShellState shell)
    {
        MemoryLabel.Text = Loc.GetString("is14-os-gallery-memory", ("size", shell.MemoryFiles));
    }

    public void UpdateState(OsGalleryState state)
    {
        _state = state;

        TakePhoto(state);

        // A photo deleted from elsewhere — the Files app, a full memory — must not leave the
        // viewer staring at something that no longer exists.
        if (_open is { } open && state.Photos.All(p => p.Id != open))
            _open = null;

        CountLabel.Text = Loc.GetString("is14-os-gallery-count", ("count", state.Photos.Count));

        RebuildGrid(state);
        UpdateView(state);
        RequestNext(state);
    }

    /// <summary>Decodes whatever payload came with this update, if any.</summary>
    private void TakePhoto(OsGalleryState state)
    {
        if (state.Photo is { } payload)
        {
            _misses = 0;

            if (_request == payload.Id)
                _request = null;

            if (_photos.ContainsKey(payload.Id))
                return;

            if (_photos.Count >= MaxCached)
                _photos.Clear();

            try
            {
                using var stream = new MemoryStream(payload.Data ?? Array.Empty<byte>());
                _photos[payload.Id] = Texture.LoadFromPNGStream(stream);
            }
            catch (Exception)
            {
                // A corrupt payload must not take the app down with it.
                _photos[payload.Id] = null;
            }

            return;
        }

        if (_request is not { } pending || ReferenceEquals(state, _accounted))
            return;

        _accounted = state;

        // Asked and got nothing back twice running: the file is gone. Remember that, or the
        // app would ask for it again on every single update.
        if (++_misses < 2)
            return;

        _photos[pending] = null;
        _request = null;
        _misses = 0;
    }

    /// <summary>
    ///     Pulls the sheet down one picture at a time. Asking for all of them at once would
    ///     mean a megabyte of PNG in a single state push (Docs §4.5).
    /// </summary>
    private void RequestNext(OsGalleryState state)
    {
        if (_request != null)
            return;

        // Whatever is open is worth having first.
        if (_open is { } open && !_photos.ContainsKey(open))
        {
            Request(open);
            return;
        }

        foreach (var photo in state.Photos)
        {
            if (_photos.ContainsKey(photo.Id))
                continue;

            Request(photo.Id);
            return;
        }

        // Everything is on hand: drop the server's request so it stops attaching the last
        // photo to every update from here on.
        if (state.Photo != null)
            OnView?.Invoke(null);
    }

    private void Request(int id)
    {
        _request = id;
        _misses = 0;
        OnView?.Invoke(id);
    }

    #endregion

    #region Screens

    private void Open(int? id)
    {
        _open = id;

        if (_state == null)
            return;

        UpdateView(_state);
        RebuildGrid(_state);
        RequestNext(_state);
    }

    private void RebuildGrid(OsGalleryState state)
    {
        GridBox.Visible = _open == null;

        if (_open != null)
            return;

        Grid.RemoveAllChildren();
        EmptyLabel.Visible = state.Photos.Count == 0;

        foreach (var photo in state.Photos)
        {
            var tile = new PictureTile
            {
                Palette = _palette,
                PictureSize = ThumbSize,
                Caption = photo.Name,
                Placeholder = Loc.GetString("is14-os-gallery-loading"),
                Margin = new Thickness(0, 0, 3, 3),
            };

            if (_photos.TryGetValue(photo.Id, out var texture))
            {
                tile.Picture = texture;

                if (texture == null)
                    tile.Placeholder = Loc.GetString("is14-os-gallery-broken");
            }

            var id = photo.Id;
            tile.OnPressed += _ => Open(id);

            Grid.AddChild(tile);
        }
    }

    private void UpdateView(OsGalleryState state)
    {
        ViewBox.Visible = _open != null;

        if (_open is not { } id)
            return;

        DeleteButton.Disabled = false;

        var meta = state.Photos.FirstOrDefault(p => p.Id == id);
        TitleLabel.Text = meta?.Name ?? string.Empty;
        MetaLabel.Text = meta == null
            ? string.Empty
            : Loc.GetString("is14-os-gallery-meta",
                ("author", meta.Author ?? Loc.GetString("is14-os-status-unknown")),
                ("size", meta.Size));

        var texture = _photos.GetValueOrDefault(id);
        FullImage.Texture = texture;
        FullImage.Visible = texture != null;

        if (texture == null)
        {
            MetaLabel.Text = Loc.GetString(_photos.ContainsKey(id)
                ? "is14-os-gallery-broken"
                : "is14-os-gallery-loading");
        }
    }

    #endregion

    public void ApplyTheme(IS14ThemePalette palette)
    {
        _palette = palette;

        CountLabel.FontColorOverride = palette.Text;
        MemoryLabel.FontColorOverride = palette.Muted;
        EmptyLabel.FontColorOverride = palette.Muted;
        TitleLabel.FontColorOverride = palette.Accent;
        MetaLabel.FontColorOverride = palette.Muted;

        BackButton.Palette = palette;
        DeleteButton.Palette = palette;

        ViewPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.Backdrop,
            BorderColor = palette.Border,
            BorderThickness = new Thickness(1),
        };

        if (_state != null)
            RebuildGrid(_state);
    }
}
