using System.Linq;
using Content.Client._IS14.Controls;
using Content.Client._IS14.OS.Shell;
using Content.Shared._IS14.OS.Prototypes;
using Content.Shared._IS14.OS.UI;
using Content.Shared._IS14.OS.UI.Apps;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Shared.Timing;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Apps;

/// <summary>
///     The app store. Everything the player weighs here is memory: the free-space readout sits
///     above the catalogue, and an app that will not fit says so on its own row instead of
///     failing after the download (Docs §7.1).
/// </summary>
public sealed class HubAppUi : IS14OsAppUi
{
    private HubAppFragment? _fragment;

    private HubAppFragment Fragment => _fragment ??= new HubAppFragment();

    public override string AppId => "AppHub";

    public override Control Root => Fragment;

    public override void Setup(IS14OsBui bui)
    {
        base.Setup(bui);

        Fragment.OnDownload += app => SendAppEvent(AppId, new OsHubDownloadEvent(app));
        Fragment.OnCancel += () => SendAppEvent(AppId, new OsHubCancelEvent());
        Fragment.OnDismissError += () => SendAppEvent(AppId, new OsHubDismissErrorEvent());
    }

    public override void UpdateShell(OsShellState shell)
    {
        Fragment.UpdateShell(shell);
    }

    public override void UpdateState(IS14OsAppState state)
    {
        if (state is OsAppHubState hub)
            Fragment.UpdateState(hub);
    }

    public override void ApplyTheme(IS14ThemePalette palette)
    {
        Fragment.ApplyTheme(palette);
    }
}

[GenerateTypedNameReferences]
public sealed partial class HubAppFragment : BoxContainer
{
    private const string AllCategories = "*";

    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private readonly SpriteSystem _sprites;

    private IS14ThemePalette _palette = IS14ThemePalette.Default;
    private OsShellState? _shell;
    private OsAppHubState? _hub;
    private string _category = AllCategories;

    private float _shownProgress;
    private float _targetProgress;

    public event Action<string>? OnDownload;
    public event Action? OnCancel;
    public event Action? OnDismissError;

    public HubAppFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _sprites = _sysMan.GetEntitySystem<SpriteSystem>();

        MemoryRow.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Memory);
        MemoryRow.Caption = Loc.GetString("is14-os-hub-free");

        SearchlessCancelSetup();

        Categories.OnChoiceSelected += id =>
        {
            _category = id;
            Rebuild();
        };
    }

    private void SearchlessCancelSetup()
    {
        CancelButton.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Close);
        CancelButton.ToolTip = Loc.GetString("is14-os-hub-cancel");
        CancelButton.OnPressed += _ => OnCancel?.Invoke();

        DismissButton.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Close);
        DismissButton.ToolTip = Loc.GetString("is14-os-hub-dismiss");
        DismissButton.OnPressed += _ => OnDismissError?.Invoke();
    }

    public void UpdateShell(OsShellState shell)
    {
        _shell = shell;

        var used = shell.MemorySystem + shell.MemoryUsed;
        MemoryRow.Value = Loc.GetString("is14-os-hub-free-value",
            ("free", Math.Max(0, shell.MemoryTotal - used)),
            ("total", shell.MemoryTotal));

        Rebuild();
    }

    public void UpdateState(OsAppHubState hub)
    {
        _hub = hub;

        DownloadPanel.Visible = hub.Downloading != null;
        if (hub.Downloading is { } app && _proto.TryIndex<IS14OsAppPrototype>(app, out var proto))
        {
            DownloadLabel.Text = Loc.GetString("is14-os-hub-downloading", ("app", Loc.GetString(proto.Name)));
            _targetProgress = hub.Progress;
        }
        else
        {
            _shownProgress = 0f;
            _targetProgress = 0f;
            DownloadBar.Value = 0f;
        }

        ErrorPanel.Visible = hub.Error != null;
        if (hub.Error != null)
            ErrorLabel.Text = Loc.GetString(hub.Error);

        RebuildCategories(hub);
        Rebuild();
    }

    /// <summary>
    ///     The server only reports progress once a second, so the bar is eased toward the last
    ///     figure rather than jumping in visible steps.
    /// </summary>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!DownloadPanel.Visible)
            return;

        _shownProgress = MathHelper.Lerp(_shownProgress, _targetProgress, Math.Clamp(args.DeltaSeconds * 6f, 0f, 1f));
        DownloadBar.Value = _shownProgress;
    }

    private void RebuildCategories(OsAppHubState hub)
    {
        var present = new List<OsAppCategory>();

        foreach (var appId in hub.Catalog)
        {
            if (appId.Id is { } id
                && _proto.TryIndex<IS14OsAppPrototype>(id, out var proto)
                && !present.Contains(proto.Category))
            {
                present.Add(proto.Category);
            }
        }

        present.Sort();

        var items = new List<ChoiceStripItem>
        {
            new(AllCategories, Loc.GetString("is14-os-hub-category-all")),
        };

        foreach (var category in present)
            items.Add(new ChoiceStripItem(category.ToString(), Loc.GetString($"is14-os-category-{category.ToString().ToLowerInvariant()}")));

        if (items.All(i => i.Id != _category))
            _category = AllCategories;

        Categories.SetItems(items, _category);
    }

    private void Rebuild()
    {
        if (_hub == null || _shell == null)
            return;

        Catalog.RemoveAllChildren();

        var free = _shell.MemoryTotal - _shell.MemorySystem - _shell.MemoryUsed;

        foreach (var appId in _hub.Catalog)
        {
            if (appId.Id is not { } id || !_proto.TryIndex<IS14OsAppPrototype>(id, out var app))
                continue;

            if (_category != AllCategories && app.Category.ToString() != _category)
                continue;

            Catalog.AddChild(BuildRow(app, free));
        }
    }

    private Control BuildRow(IS14OsAppPrototype app, int free)
    {
        var installed = _shell!.Installed.Any(a => a.Id == app.ID);
        var denied = _hub!.AccessDenied.Any(a => a.Id == app.ID);
        var busy = _hub.Downloading != null;
        var fits = app.Size <= free;

        var row = new StatRow
        {
            Palette = _palette,
            Framed = true,
            Icon = IS14OsStyle.Resolve(_sprites, app.Icon ?? IS14OsStyle.Fallback),
            Caption = Loc.GetString(app.Name),
            Value = Loc.GetString("is14-os-files-size", ("size", app.Size)),
            Margin = new Thickness(0, 0, 0, 2),
            ToolTip = app.Description == null ? null : Loc.GetString(app.Description),
        };

        // The row's own state tells the whole story, so the button never has to be a mystery.
        if (installed)
        {
            row.ValueColor = _palette.Good;
            row.SetTrailing(new Label
            {
                Text = Loc.GetString("is14-os-hub-installed"),
                FontColorOverride = _palette.Good,
                VerticalAlignment = VAlignment.Center,
            });

            return row;
        }

        if (denied || !fits)
        {
            row.ValueColor = _palette.Bad;
            row.SetTrailing(new Label
            {
                Text = Loc.GetString(denied ? "is14-os-hub-no-access" : "is14-os-hub-no-memory"),
                FontColorOverride = _palette.Bad,
                VerticalAlignment = VAlignment.Center,
            });

            return row;
        }

        var button = new IconTile
        {
            Palette = _palette,
            Compact = true,
            Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Download),
            Caption = Loc.GetString("is14-os-hub-download"),
            IconSize = 12,
            Disabled = busy,
        };

        button.OnPressed += _ => OnDownload?.Invoke(app.ID);
        row.SetTrailing(button);

        return row;
    }

    public void ApplyTheme(IS14ThemePalette palette)
    {
        _palette = palette;

        MemoryRow.Palette = palette;
        Categories.Palette = palette;
        CancelButton.Palette = palette;
        DismissButton.Palette = palette;

        DownloadPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.PanelRaised,
            BorderColor = palette.Accent,
            BorderThickness = new Thickness(1),
        };

        ErrorPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.Bad.WithAlpha(0.15f),
            BorderColor = palette.Bad,
            BorderThickness = new Thickness(1),
        };

        DownloadLabel.FontColorOverride = palette.Text;
        ErrorLabel.FontColorOverride = palette.Bad;

        Rebuild();
    }
}
