using Content.Client._IS14.Controls;
using Content.Client._IS14.OS.Shell;
using Content.Shared._IS14.OS.UI;
using Content.Shared._IS14.OS.UI.Apps;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Apps;

/// <summary>
///     Crew manifest with a search box, because the thing anyone actually wants from a manifest
///     is one name.
/// </summary>
public sealed class ManifestAppUi : IS14OsAppUi
{
    private ManifestAppFragment? _fragment;

    private ManifestAppFragment Fragment => _fragment ??= new ManifestAppFragment();

    public override string AppId => "AppManifest";

    public override Control Root => Fragment;

    public override void UpdateState(IS14OsAppState state)
    {
        if (state is OsManifestState manifest)
            Fragment.UpdateState(manifest);
    }

    public override void ApplyTheme(IS14ThemePalette palette)
    {
        Fragment.ApplyTheme(palette);
    }
}

[GenerateTypedNameReferences]
public sealed partial class ManifestAppFragment : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private readonly SpriteSystem _sprites;

    private IS14ThemePalette _palette = IS14ThemePalette.Default;
    private OsManifestState? _state;

    public ManifestAppFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _sprites = _sysMan.GetEntitySystem<SpriteSystem>();

        StationRow.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Station);
        StationRow.Caption = Loc.GetString("is14-os-status-station");

        SearchEdit.PlaceHolder = Loc.GetString("is14-os-manifest-search");
        SearchEdit.OnTextChanged += _ => Rebuild();
    }

    public void UpdateState(OsManifestState state)
    {
        _state = state;
        StationRow.Value = string.IsNullOrEmpty(state.StationName)
            ? Loc.GetString("is14-os-status-unknown")
            : state.StationName;

        Rebuild();
    }

    private void Rebuild()
    {
        CrewList.RemoveAllChildren();

        if (_state?.Entries == null)
            return;

        var filter = SearchEdit.Text.Trim();
        var shown = 0;

        foreach (var entry in _state.Entries.Entries)
        {
            if (filter.Length > 0
                && !entry.Name.Contains(filter, StringComparison.CurrentCultureIgnoreCase)
                && !entry.JobTitle.Contains(filter, StringComparison.CurrentCultureIgnoreCase))
            {
                continue;
            }

            var row = new StatRow
            {
                Palette = _palette,
                Caption = entry.Name,
                Value = entry.JobTitle,
                Margin = new Thickness(0, 0, 0, 1),
            };

            if (_proto.TryIndex<JobIconPrototype>(entry.JobIcon, out var icon))
                row.Icon = _sprites.Frame0(icon.Icon);

            CrewList.AddChild(row);
            shown++;
        }

        if (shown == 0)
        {
            CrewList.AddChild(new Label
            {
                Text = Loc.GetString("is14-os-manifest-empty"),
                FontColorOverride = _palette.Muted,
            });
        }
    }

    public void ApplyTheme(IS14ThemePalette palette)
    {
        _palette = palette;
        StationRow.Palette = palette;
        Rebuild();
    }
}
