using System.IO;
using System.Linq;
using System.Numerics;
using Content.Client._IS14.Controls;
using Content.Client._IS14.OS.Shell;
using Content.Shared._IS14.OS.Files;
using Content.Shared._IS14.OS.UI;
using Content.Shared._IS14.OS.UI.Apps;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Apps;

/// <summary>
///     Messenger. Three screens in one app — conversations, the station directory, and an open
///     chat — because a handheld has room for exactly one of them at a time.
/// </summary>
public sealed class MessengerAppUi : IS14OsAppUi
{
    private MessengerAppFragment? _fragment;

    private MessengerAppFragment Fragment => _fragment ??= new MessengerAppFragment();

    public override string AppId => "AppMessenger";

    public override Control Root => Fragment;

    public override void Setup(IS14OsBui bui)
    {
        base.Setup(bui);

        Fragment.OnOpenChat += address => SendAppEvent(AppId, new OsMessengerOpenChatEvent(address));
        Fragment.OnDirectory += show => SendAppEvent(AppId, new OsMessengerDirectoryEvent(show));
        Fragment.OnMute += () => SendAppEvent(AppId, new OsMessengerMuteEvent());
        Fragment.OnDeleteChat += address => SendAppEvent(AppId, new OsMessengerDeleteChatEvent(address));
        Fragment.OnSend += (address, text, file) =>
            SendAppEvent(AppId, new OsMessengerSendEvent(address, text, file));
        Fragment.OnViewPhoto += file => SendAppEvent(AppId, new OsMessengerViewPhotoEvent(file));
    }

    public override void UpdateState(IS14OsAppState state)
    {
        if (state is OsMessengerState messenger)
            Fragment.UpdateState(messenger);
    }

    public override void ApplyTheme(IS14ThemePalette palette)
    {
        Fragment.ApplyTheme(palette);
    }
}

[GenerateTypedNameReferences]
public sealed partial class MessengerAppFragment : BoxContainer
{
    /// <summary>Widest a photo may be drawn in a bubble, in virtual pixels.</summary>
    private const float PhotoWidth = 150f;

    /// <summary>Decoded photos held at once. Textures are not free, and a chat can be long.</summary>
    private const int MaxCachedPhotos = 24;

    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private readonly SpriteSystem _sprites;

    /// <summary>Decoded attachments by file id. A null value means the payload was unreadable.</summary>
    private readonly Dictionary<int, Texture?> _photos = new();

    private IS14ThemePalette _palette = IS14ThemePalette.Default;
    private OsMessengerState? _state;

    private int? _attachment;
    private bool _pickingAttachment;

    private int? _photoRequest;
    private int _photoMisses;
    private OsMessengerState? _photoAccounted;

    public event Action<string?>? OnOpenChat;
    public event Action<bool>? OnDirectory;
    public event Action? OnMute;
    public event Action<string>? OnDeleteChat;
    public event Action<string, string, int?>? OnSend;
    public event Action<int?>? OnViewPhoto;

    public MessengerAppFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _sprites = _sysMan.GetEntitySystem<SpriteSystem>();

        BackButton.Icon = Icon(IS14OsStyle.Back);
        BackButton.ToolTip = Loc.GetString("is14-os-messenger-back");
        BackButton.OnPressed += _ => GoBack();

        DirectoryButton.Icon = Icon(IS14OsStyle.Contacts);
        DirectoryButton.ToolTip = Loc.GetString("is14-os-messenger-directory");
        DirectoryButton.OnPressed += _ => OnDirectory?.Invoke(_state?.Directory == null);

        MuteButton.Icon = Icon(IS14OsStyle.Mute);
        MuteButton.ToolTip = Loc.GetString("is14-os-messenger-mute");
        MuteButton.OnPressed += _ => OnMute?.Invoke();

        AttachButton.Icon = Icon(IS14OsStyle.Attach);
        AttachButton.ToolTip = Loc.GetString("is14-os-messenger-attach");
        AttachButton.OnPressed += _ => TogglePicker();

        AttachClearButton.Icon = Icon(IS14OsStyle.Close);
        AttachClearButton.OnPressed += _ => SetAttachment(null);

        SendButton.Icon = Icon(IS14OsStyle.Send);
        SendButton.ToolTip = Loc.GetString("is14-os-messenger-send");
        SendButton.OnPressed += _ => Send();

        MessageEdit.PlaceHolder = Loc.GetString("is14-os-messenger-placeholder");
        MessageEdit.OnTextEntered += _ => Send();
    }

    private Texture? Icon(Robust.Shared.Utility.SpriteSpecifier specifier)
    {
        return IS14OsStyle.Resolve(_sprites, specifier);
    }

    #region State

    public void UpdateState(OsMessengerState state)
    {
        _state = state;

        TakePhoto(state);

        var inChat = state.OpenChat != null;
        var inDirectory = state.Directory != null;

        ChatBox.Visible = inChat;
        ListScroll.Visible = !inChat;
        BackButton.Visible = inChat || inDirectory;
        DirectoryButton.Visible = !inChat;
        DirectoryButton.Selected = inDirectory;
        MuteButton.Selected = state.Muted;

        HeaderLabel.Text = inChat
            ? ChatName(state)
            : inDirectory
                ? Loc.GetString("is14-os-messenger-directory")
                : Loc.GetString("is14-os-messenger-own", ("address", state.OwnAddress));

        ErrorLabel.Visible = state.Error != null;
        if (state.Error != null)
            ErrorLabel.Text = Loc.GetString(state.Error);

        if (inChat)
            RebuildMessages(state);
        else
            RebuildList(state);

        if (!inChat)
            SetAttachment(null);
    }

    private string ChatName(OsMessengerState state)
    {
        var chat = state.Chats.FirstOrDefault(c => c.Address == state.OpenChat);
        return chat == null ? state.OpenChat ?? string.Empty : $"{chat.Name} · {chat.Address}";
    }

    #endregion

    #region Lists

    private void RebuildList(OsMessengerState state)
    {
        EntryList.RemoveAllChildren();

        if (state.Directory != null)
        {
            if (state.Directory.Count == 0)
            {
                EntryList.AddChild(Hint("is14-os-messenger-directory-empty"));
                return;
            }

            foreach (var entry in state.Directory)
            {
                var row = new StatRow
                {
                    Palette = _palette,
                    Framed = true,
                    Icon = Icon(IS14OsStyle.Owner),
                    Caption = entry.Name,
                    Value = entry.Job ?? entry.Address,
                    Margin = new Thickness(0, 0, 0, 2),
                    ToolTip = entry.Address,
                };

                var open = new IconTile
                {
                    Palette = _palette,
                    Compact = true,
                    Icon = Icon(IS14OsStyle.Send),
                    IconSize = 12,
                    ToolTip = Loc.GetString("is14-os-messenger-write"),
                };

                var address = entry.Address;
                open.OnPressed += _ =>
                {
                    OnDirectory?.Invoke(false);
                    OnOpenChat?.Invoke(address);
                };

                row.SetTrailing(open);
                EntryList.AddChild(row);
            }

            return;
        }

        if (state.Chats.Count == 0)
        {
            EntryList.AddChild(Hint("is14-os-messenger-empty"));
            return;
        }

        foreach (var chat in state.Chats)
        {
            var row = new StatRow
            {
                Palette = _palette,
                Framed = true,
                Icon = Icon(IS14OsStyle.Owner),
                Caption = chat.Unread ? $"● {chat.Name}" : chat.Name,
                Value = chat.Preview,
                Margin = new Thickness(0, 0, 0, 2),
                ValueColor = chat.Unread ? _palette.Accent : null,
                ToolTip = chat.Job ?? chat.Address,
            };

            var buttons = new BoxContainer { Orientation = LayoutOrientation.Horizontal };

            var open = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = Icon(IS14OsStyle.Open),
                IconSize = 12,
                Badge = chat.Unread,
                Margin = new Thickness(0, 0, 3, 0),
            };
            open.OnPressed += _ => OnOpenChat?.Invoke(chat.Address);

            var delete = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = Icon(IS14OsStyle.Delete),
                IconSize = 12,
                ToolTip = Loc.GetString("is14-os-messenger-delete"),
            };
            delete.OnPressed += _ =>
            {
                delete.Disabled = true;
                OnDeleteChat?.Invoke(chat.Address);
            };

            buttons.AddChild(open);
            buttons.AddChild(delete);
            row.SetTrailing(buttons);

            EntryList.AddChild(row);
        }
    }

    private void RebuildMessages(OsMessengerState state)
    {
        MessageList.RemoveAllChildren();

        foreach (var message in state.Messages)
            MessageList.AddChild(BuildBubble(message));

        MessageScroll.SetScrollValue(new Vector2(0, float.MaxValue));

        RequestNextPhoto(state);
    }

    #region Photos

    /// <summary>Decodes whatever payload the server sent along with this update, if any.</summary>
    private void TakePhoto(OsMessengerState state)
    {
        if (state.Photo is { } payload)
        {
            _photoMisses = 0;

            if (_photoRequest == payload.Id)
                _photoRequest = null;

            if (_photos.ContainsKey(payload.Id))
                return;

            // A gallery-heavy conversation would otherwise pile up textures for the whole session.
            if (_photos.Count >= MaxCachedPhotos)
                _photos.Clear();

            try
            {
                using var stream = new MemoryStream(payload.Data ?? Array.Empty<byte>());
                _photos[payload.Id] = Texture.LoadFromPNGStream(stream);
            }
            catch (Exception)
            {
                // A corrupt or hostile payload must not take the chat down with it.
                _photos[payload.Id] = null;
            }

            return;
        }

        if (_photoRequest is not { } pending || ReferenceEquals(state, _photoAccounted))
            return;

        _photoAccounted = state;

        // We asked and got nothing back twice running, so the file is gone. Remember that,
        // or the app would ask for it again on every single update.
        if (++_photoMisses < 2)
            return;

        _photos[pending] = null;
        _photoRequest = null;
        _photoMisses = 0;
    }

    /// <summary>
    ///     Pulls the transcript's photos down one at a time. Asking for all of them at once
    ///     would mean a megabyte of PNG in a single state push.
    /// </summary>
    private void RequestNextPhoto(OsMessengerState state)
    {
        if (_photoRequest != null)
            return;

        foreach (var message in state.Messages)
        {
            if (message.Attachment is not { Kind: OsFileKind.Photo } photo || _photos.ContainsKey(photo.Id))
                continue;

            _photoRequest = photo.Id;
            _photoMisses = 0;
            OnViewPhoto?.Invoke(photo.Id);
            return;
        }

        // Everything is on hand: drop the server's request so it stops attaching the last
        // photo to every update from here on.
        if (state.Photo != null)
            OnViewPhoto?.Invoke(null);
    }

    private Control BuildPhoto(OsFileMeta attachment)
    {
        if (!_photos.TryGetValue(attachment.Id, out var texture))
            return Hint("is14-os-messenger-photo-loading");

        if (texture == null)
            return Hint("is14-os-messenger-photo-broken");

        // Scale to the bubble instead of letting a photo shove the conversation off-screen.
        var natural = Math.Max(1f, texture.Size.X);
        var width = Math.Min(PhotoWidth, natural);

        return new TextureRect
        {
            Texture = texture,
            Stretch = TextureRect.StretchMode.Scale,
            CanShrink = true,
            SetSize = new Vector2(width, texture.Size.Y * (width / natural)),
            Margin = new Thickness(0, 2, 0, 1),
        };
    }

    #endregion

    /// <summary>
    ///     Outgoing messages hug the right, incoming the left. It is the cheapest possible way
    ///     to make a transcript readable without colouring every line.
    /// </summary>
    private Control BuildBubble(OsChatMessage message)
    {
        var panel = new PanelContainer
        {
            HorizontalAlignment = message.Outgoing ? HAlignment.Right : HAlignment.Left,
            Margin = new Thickness(message.Outgoing ? 32 : 0, 0, message.Outgoing ? 0 : 32, 3),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = message.Outgoing ? _palette.Accent.WithAlpha(0.22f) : _palette.PanelRaised,
                BorderColor = message.Outgoing ? _palette.Accent : _palette.Border,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 3,
                ContentMarginBottomOverride = 3,
            },
        };

        var box = new BoxContainer { Orientation = LayoutOrientation.Vertical };

        if (message.Attachment is { } attachment)
        {
            var chip = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            chip.AddChild(new TextureRect
            {
                Texture = Icon(attachment.Kind == OsFileKind.Photo ? IS14OsStyle.Photo : IS14OsStyle.Note),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                SetSize = new Vector2(12, 12),
                ModulateSelfOverride = _palette.Accent,
                Margin = new Thickness(0, 0, 4, 0),
                VerticalAlignment = VAlignment.Center,
            });
            chip.AddChild(new Label
            {
                Text = attachment.Name,
                FontColorOverride = _palette.Accent,
                VerticalAlignment = VAlignment.Center,
            });

            box.AddChild(chip);

            // A photo is the message: show it here rather than making the reader go dig it
            // out of the file manager.
            if (attachment.Kind == OsFileKind.Photo)
                box.AddChild(BuildPhoto(attachment));
        }

        if (message.Text.Length > 0)
        {
            var label = new RichTextLabel();
            label.SetMessage(message.Text);
            box.AddChild(label);
        }

        box.AddChild(new Label
        {
            Text = message.Time.ToString("hh\\:mm\\:ss"),
            FontColorOverride = _palette.Muted,
            HorizontalAlignment = HAlignment.Right,
        });

        panel.AddChild(box);
        return panel;
    }

    private Label Hint(string locId)
    {
        return new Label
        {
            Text = Loc.GetString(locId),
            FontColorOverride = _palette.Muted,
        };
    }

    #endregion

    #region Sending

    private void TogglePicker()
    {
        _pickingAttachment = !_pickingAttachment;

        if (!_pickingAttachment)
        {
            if (_state != null)
                RebuildMessages(_state);

            return;
        }

        RebuildPicker();
    }

    /// <summary>Attachment picking reuses the message area rather than opening a second window.</summary>
    private void RebuildPicker()
    {
        MessageList.RemoveAllChildren();

        var files = _state?.Files ?? new List<OsFileMeta>();

        if (files.Count == 0)
        {
            MessageList.AddChild(Hint("is14-os-messenger-no-files"));
            return;
        }

        foreach (var file in files)
        {
            var tile = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = Icon(file.Kind == OsFileKind.Photo ? IS14OsStyle.Photo : IS14OsStyle.Note),
                Caption = $"{file.Name} · {file.Size}",
                IconSize = 12,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2),
            };

            var id = file.Id;
            var name = file.Name;
            tile.OnPressed += _ =>
            {
                SetAttachment(id, name);
                _pickingAttachment = false;

                if (_state != null)
                    RebuildMessages(_state);
            };

            MessageList.AddChild(tile);
        }
    }

    private void SetAttachment(int? id, string? name = null)
    {
        _attachment = id;
        AttachPanel.Visible = id != null;
        AttachButton.Selected = id != null;

        if (id != null)
            AttachLabel.Text = name ?? string.Empty;
    }

    private void Send()
    {
        if (_state?.OpenChat is not { } address)
            return;

        var text = MessageEdit.Text.Trim();
        if (text.Length == 0 && _attachment == null)
            return;

        OnSend?.Invoke(address, text, _attachment);
        MessageEdit.Text = string.Empty;
        SetAttachment(null);
    }

    private void GoBack()
    {
        if (_state?.OpenChat != null)
        {
            OnOpenChat?.Invoke(null);
            return;
        }

        OnDirectory?.Invoke(false);
    }

    #endregion

    public void ApplyTheme(IS14ThemePalette palette)
    {
        _palette = palette;

        HeaderLabel.FontColorOverride = palette.Accent;
        ErrorLabel.FontColorOverride = palette.Bad;
        AttachLabel.FontColorOverride = palette.Accent;

        BackButton.Palette = palette;
        DirectoryButton.Palette = palette;
        MuteButton.Palette = palette;
        AttachButton.Palette = palette;
        AttachClearButton.Palette = palette;
        SendButton.Palette = palette;

        AttachPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.PanelRaised,
            BorderColor = palette.Accent,
            BorderThickness = new Thickness(1),
        };

        if (_state != null)
            UpdateState(_state);
    }
}
