using Content.Client._IS14.Controls;
using Content.Client._IS14.OS.Shell;
using Content.Shared._IS14.OS.UI;
using Content.Shared._IS14.OS.UI.Apps;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Apps;

/// <summary>
///     Station press. Headlines, then one article at a time — the same shape as the messenger
///     and the gallery, because on a screen this size a list and a reader cannot share it.
/// </summary>
public sealed class NewsAppUi : IS14OsAppUi
{
    private NewsAppFragment? _fragment;

    private NewsAppFragment Fragment => _fragment ??= new NewsAppFragment();

    public override string AppId => "AppNews";

    public override Control Root => Fragment;

    public override void Setup(IS14OsBui bui)
    {
        base.Setup(bui);

        Fragment.OnRead += article => SendAppEvent(AppId, new OsNewsReadEvent(article));
    }

    public override void UpdateState(IS14OsAppState state)
    {
        if (state is OsNewsState news)
            Fragment.UpdateState(news);
    }

    public override void ApplyTheme(IS14ThemePalette palette)
    {
        Fragment.ApplyTheme(palette);
    }
}

[GenerateTypedNameReferences]
public sealed partial class NewsAppFragment : BoxContainer
{
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private readonly SpriteSystem _sprites;

    private IS14ThemePalette _palette = IS14ThemePalette.Default;
    private OsNewsState? _state;

    public event Action<int?>? OnRead;

    public NewsAppFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _sprites = _sysMan.GetEntitySystem<SpriteSystem>();

        SummaryRow.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Note);
        SummaryRow.Caption = Loc.GetString("is14-os-news-summary");

        BackButton.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Back);
        BackButton.ToolTip = Loc.GetString("is14-os-news-back");
        BackButton.OnPressed += _ => OnRead?.Invoke(null);
    }

    public void UpdateState(OsNewsState state)
    {
        _state = state;

        var reading = state.Reading != null;
        ListBox.Visible = !reading;
        ArticleBox.Visible = reading;

        if (reading)
            ShowArticle(state);
        else
            RebuildList(state);
    }

    private void ShowArticle(OsNewsState state)
    {
        if (state.Reading is not { } index || index < 0 || index >= state.Headlines.Count)
            return;

        var headline = state.Headlines[index];

        ArticleTitle.Text = headline.Title;
        ArticleTitle.FontColorOverride = _palette.Accent;
        ArticleByline.Text = Byline(headline);
        ArticleByline.FontColorOverride = _palette.Muted;

        // Articles are written by players, so the text is never trusted as markup: an author
        // who could open a colour tag could recolour the reader's whole screen.
        ArticleBody.SetMessage(FormattedMessage.FromUnformatted(state.Body ?? string.Empty),
            defaultColor: _palette.Text);
    }

    private void RebuildList(OsNewsState state)
    {
        SummaryRow.Value = state.Headlines.Count == 0
            ? Loc.GetString("is14-os-news-none")
            : Loc.GetString("is14-os-news-count",
                ("count", state.Headlines.Count),
                ("unread", state.Unread));

        HeadlineList.RemoveAllChildren();

        if (state.Headlines.Count == 0)
        {
            HeadlineList.AddChild(new Label
            {
                Text = Loc.GetString("is14-os-news-empty"),
                FontColorOverride = _palette.Muted,
            });

            return;
        }

        // Newest first: a shift's news is read from the top, not from the founding of the station.
        for (var i = state.Headlines.Count - 1; i >= 0; i--)
        {
            var headline = state.Headlines[i];
            var index = i;
            var unread = i >= state.Headlines.Count - state.Unread;

            var row = new StatRow
            {
                Palette = _palette,
                Framed = true,
                Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Note),
                Caption = headline.Title,
                Value = Byline(headline),
                Margin = new Thickness(0, 0, 0, 2),
            };

            var open = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Open),
                IconSize = 12,
                Badge = unread,
                ToolTip = Loc.GetString("is14-os-news-open"),
            };

            open.OnPressed += _ => OnRead?.Invoke(index);
            row.SetTrailing(open);
            HeadlineList.AddChild(row);
        }
    }

    private static string Byline(OsNewsHeadline headline)
    {
        return Loc.GetString("is14-os-news-byline",
            ("author", string.IsNullOrWhiteSpace(headline.Author)
                ? Loc.GetString("is14-os-status-unknown")
                : headline.Author!),
            ("time", headline.Published.ToString(@"hh\:mm")));
    }

    public void ApplyTheme(IS14ThemePalette palette)
    {
        _palette = palette;

        SummaryRow.Palette = palette;
        BackButton.Palette = palette;
        ArticlePanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.Panel,
            BorderColor = palette.Border,
            BorderThickness = new Thickness(1),
        };

        if (_state != null)
            UpdateState(_state);
    }
}
