using Content.Client._IS14.Controls;
using Content.Client._IS14.OS.Shell;
using Content.Shared._IS14.OS.UI;
using Content.Shared._IS14.OS.UI.Apps;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Apps;

/// <summary>
///     Notes. The first app that owns data, and therefore the end-to-end proof that installing
///     an app puts its components on the device and uninstalling takes them away.
/// </summary>
public sealed class NotesAppUi : IS14OsAppUi
{
    private NotesAppFragment? _fragment;

    private NotesAppFragment Fragment => _fragment ??= new NotesAppFragment();

    public override string AppId => "AppNotes";

    public override Control Root => Fragment;

    public override void Setup(IS14OsBui bui)
    {
        base.Setup(bui);

        Fragment.OnSave += text => SendAppEvent(AppId, new OsNotesSaveEvent(text));
        Fragment.OnExport += name => SendAppEvent(AppId, new OsNotesExportEvent(name));
    }

    public override void UpdateState(IS14OsAppState state)
    {
        if (state is OsNotesState notes)
            Fragment.UpdateState(notes);
    }

    public override void ApplyTheme(IS14ThemePalette palette)
    {
        Fragment.ApplyTheme(palette);
    }
}

[GenerateTypedNameReferences]
public sealed partial class NotesAppFragment : BoxContainer
{
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private string _saved = string.Empty;

    public event Action<string>? OnSave;
    public event Action<string>? OnExport;

    public NotesAppFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        var sprites = _sysMan.GetEntitySystem<SpriteSystem>();

        SaveButton.Icon = IS14OsStyle.Resolve(sprites, IS14OsStyle.Save);
        ExportButton.Icon = IS14OsStyle.Resolve(sprites, IS14OsStyle.Note);
        ExportButton.Caption = Loc.GetString("is14-os-notes-export");
        ExportButton.ToolTip = Loc.GetString("is14-os-notes-export-tooltip");
        ExportButton.OnPressed += _ =>
        {
            // The first line makes a far better file name than "Note 3".
            var text = Rope.Collapse(NoteEdit.TextRope);
            var firstLine = text.Split('\n')[0].Trim();
            OnExport?.Invoke(firstLine);
        };
        SaveButton.Caption = Loc.GetString("is14-os-notes-save");
        NoteEdit.Placeholder = new Rope.Leaf(Loc.GetString("is14-os-notes-placeholder"));

        SaveButton.OnPressed += _ =>
        {
            var text = Rope.Collapse(NoteEdit.TextRope);
            _saved = text;
            SavedLabel.Text = Loc.GetString("is14-os-notes-saved");
            OnSave?.Invoke(text);
        };
    }

    public void UpdateState(OsNotesState state)
    {
        if (state.Status != null)
            SavedLabel.Text = Loc.GetString(state.Status);

        // Don't stomp on what the player is typing: only take the server's text when it is
        // genuinely different from what we last sent.
        if (state.Text == _saved)
            return;

        _saved = state.Text;
        NoteEdit.TextRope = new Rope.Leaf(state.Text);
        SavedLabel.Text = string.Empty;
    }

    public void ApplyTheme(IS14ThemePalette palette)
    {
        SavedLabel.FontColorOverride = palette.Good;
        SaveButton.Palette = palette;
        ExportButton.Palette = palette;

        EditPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.Backdrop,
            BorderColor = palette.Border,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3,
        };
    }
}
