using System.Linq;
using Content.Client._IS14.Controls;
using Content.Client._IS14.OS.Shell;
using Content.Shared.Cargo;
using Content.Shared.Cargo.BUI;
using Content.Shared.Cargo.Events;
using Content.Shared.Cargo.Prototypes;
using Content.Shared._IS14.OS.UI;
using Content.Shared._IS14.OS.UI.Apps;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Apps;

/// <summary>
///     Department orders. Unlike the four economy apps this one does not reuse a console
///     window: the cargo order console is upstream, and rebuilding its layout here would mean
///     restructuring upstream client code. A native OS layout also means orders is the one
///     console app that does follow the device theme.
/// </summary>
public sealed class OrdersAppUi : IS14OsAppUi
{
    private OrdersAppFragment? _fragment;

    private OrdersAppFragment Fragment => _fragment ??= new OrdersAppFragment();

    public override string AppId => "AppOrders";

    public override Control Root => Fragment;

    public override void Setup(IS14OsBui bui)
    {
        base.Setup(bui);

        Fragment.OnOrder += (product, amount) => SendAppEvent(AppId,
            new OsConsoleMessageEvent(new CargoConsoleAddOrderMessage(null, null, null, product, amount)));

        Fragment.OnApprove += order => SendAppEvent(AppId,
            new OsConsoleMessageEvent(new CargoConsoleApproveOrderMessage(order)));

        Fragment.OnRemove += order => SendAppEvent(AppId,
            new OsConsoleMessageEvent(new CargoConsoleRemoveOrderMessage(order)));
    }

    public override void UpdateState(IS14OsAppState state)
    {
        if (state is OsConsoleState wrapped)
            Fragment.UpdateState(wrapped.State as CargoConsoleInterfaceState);
    }

    public override void ApplyTheme(IS14ThemePalette palette)
    {
        Fragment.ApplyTheme(palette);
    }
}

[GenerateTypedNameReferences]
public sealed partial class OrdersAppFragment : BoxContainer
{
    private const string SectionCatalog = "catalog";
    private const string SectionOrders = "orders";

    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private readonly SpriteSystem _sprites;

    private IS14ThemePalette _palette = IS14ThemePalette.Default;
    private CargoConsoleInterfaceState? _state;
    private string _section = SectionCatalog;

    /// <summary>Product the order form is filled in for, if it is open.</summary>
    private string? _ordering;

    public event Action<string, int>? OnOrder;
    public event Action<int>? OnApprove;
    public event Action<int>? OnRemove;

    public OrdersAppFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _sprites = _sysMan.GetEntitySystem<SpriteSystem>();

        StationRow.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Station);
        StationRow.Caption = Loc.GetString("is14-os-orders-station");

        SearchEdit.PlaceHolder = Loc.GetString("is14-os-orders-search");
        SearchEdit.OnTextChanged += _ => Rebuild();

        AmountEdit.PlaceHolder = Loc.GetString("is14-os-orders-amount");
        AmountEdit.OnTextEntered += _ => Confirm();

        ConfirmButton.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Save);
        ConfirmButton.ToolTip = Loc.GetString("is14-os-orders-confirm");
        ConfirmButton.OnPressed += _ => Confirm();

        CancelButton.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Close);
        CancelButton.ToolTip = Loc.GetString("is14-os-orders-cancel");
        CancelButton.OnPressed += _ => CloseForm();

        Sections.OnChoiceSelected += id =>
        {
            _section = id;
            CloseForm();
            Rebuild();
        };
    }

    public void UpdateState(CargoConsoleInterfaceState? state)
    {
        _state = state;
        Rebuild();
    }

    private void Rebuild()
    {
        var orderCount = _state?.Orders.Count ?? 0;

        Sections.SetItems(new List<ChoiceStripItem>
        {
            new(SectionCatalog, Loc.GetString("is14-os-orders-section-catalog")),
            new(SectionOrders, Loc.GetString("is14-os-orders-section-orders", ("count", orderCount))),
        }, _section);

        EntryList.RemoveAllChildren();

        if (_state == null)
        {
            StationRow.Value = Loc.GetString("is14-os-status-unknown");
            EntryList.AddChild(Muted(Loc.GetString("is14-os-orders-offline")));
            return;
        }

        StationRow.Value = Loc.GetString("is14-os-orders-capacity",
            ("station", _state.Name),
            ("count", _state.Count),
            ("capacity", _state.Capacity));

        if (_section == SectionCatalog)
            RebuildCatalog(_state);
        else
            RebuildOrders(_state);
    }

    private void RebuildCatalog(CargoConsoleInterfaceState state)
    {
        var filter = SearchEdit.Text.Trim();
        var shown = 0;

        foreach (var productId in state.Products)
        {
            if (productId.Id is not { } id || !_proto.TryIndex<CargoProductPrototype>(id, out var product))
                continue;

            if (filter.Length > 0 && !product.Name.Contains(filter, StringComparison.CurrentCultureIgnoreCase))
                continue;

            var row = new StatRow
            {
                Palette = _palette,
                Framed = true,
                Icon = IS14OsStyle.Resolve(_sprites, product.Icon),
                Caption = product.Name,
                Value = Loc.GetString("is14-os-orders-price", ("price", product.Cost)),
                Margin = new Thickness(0, 0, 0, 2),
                ToolTip = product.Description,
            };

            var order = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Download),
                IconSize = 12,
                Selected = _ordering == id,
                ToolTip = Loc.GetString("is14-os-orders-order"),
            };

            var name = product.Name;
            order.OnPressed += _ => OpenForm(id, name);

            row.SetTrailing(order);
            EntryList.AddChild(row);
            shown++;
        }

        if (shown == 0)
            EntryList.AddChild(Muted(Loc.GetString("is14-os-orders-catalog-empty")));
    }

    private void RebuildOrders(CargoConsoleInterfaceState state)
    {
        if (state.Orders.Count == 0)
        {
            EntryList.AddChild(Muted(Loc.GetString("is14-os-orders-empty")));
            return;
        }

        foreach (var order in state.Orders)
        {
            var row = new StatRow
            {
                Palette = _palette,
                Framed = true,
                Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Note),
                Caption = Loc.GetString("is14-os-orders-entry",
                    ("product", order.ProductName),
                    ("amount", order.OrderQuantity)),
                Value = Loc.GetString("is14-os-orders-price", ("price", order.Price * order.OrderQuantity)),
                ToolTip = Loc.GetString("is14-os-orders-requester", ("requester", order.Requester)),
                Margin = new Thickness(0, 0, 0, 2),
            };

            var buttons = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            var id = order.OrderId;

            // An approved order is on its way; the only thing still worth offering is to cancel.
            if (!order.Approved)
            {
                var approve = new IconTile
                {
                    Palette = _palette,
                    Compact = true,
                    Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Check),
                    IconSize = 12,
                    ToolTip = Loc.GetString("is14-os-orders-approve"),
                    Margin = new Thickness(0, 0, 3, 0),
                };

                approve.OnPressed += _ =>
                {
                    approve.Disabled = true;
                    OnApprove?.Invoke(id);
                };

                buttons.AddChild(approve);
            }
            else
            {
                row.ModulateSelfOverride = _palette.Good;
            }

            var remove = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Delete),
                IconSize = 12,
                ToolTip = Loc.GetString("is14-os-orders-remove"),
            };

            remove.OnPressed += _ =>
            {
                remove.Disabled = true;
                OnRemove?.Invoke(id);
            };

            buttons.AddChild(remove);
            row.SetTrailing(buttons);
            EntryList.AddChild(row);
        }
    }

    private void OpenForm(string productId, string name)
    {
        _ordering = productId;

        OrderPanel.Visible = true;
        OrderTitle.Text = name;
        OrderTitle.FontColorOverride = _palette.Accent;
        AmountEdit.Text = "1";
        AmountEdit.GrabKeyboardFocus();

        Rebuild();
    }

    private void CloseForm()
    {
        _ordering = null;
        OrderPanel.Visible = false;
        AmountEdit.Text = string.Empty;
    }

    private void Confirm()
    {
        if (_ordering is not { } product)
            return;

        if (!int.TryParse(AmountEdit.Text, out var amount) || amount <= 0)
            return;

        OnOrder?.Invoke(product, amount);
        CloseForm();
    }

    private Label Muted(string text)
    {
        return new Label { Text = text, FontColorOverride = _palette.Muted };
    }

    public void ApplyTheme(IS14ThemePalette palette)
    {
        _palette = palette;

        StationRow.Palette = palette;
        Sections.Palette = palette;
        ConfirmButton.Palette = palette;
        CancelButton.Palette = palette;

        OrderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.Panel,
            BorderColor = palette.Border,
            BorderThickness = new Thickness(1),
        };

        Rebuild();
    }
}
