using Content.Client._IS14.Controls;
using Content.Client._IS14.OS.Shell;
using Content.Shared._IS14.OS.Prototypes;
using Content.Shared._IS14.OS.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Apps;

/// <summary>
///     Settings: theme and device toggles. Theme is device state rather than a client
///     preference — a syndicate-red PDA should look that way to everyone who sees the screen.
/// </summary>
public sealed class SettingsAppUi : IS14OsAppUi
{
    private SettingsAppFragment? _fragment;

    private SettingsAppFragment Fragment => _fragment ??= new SettingsAppFragment();

    public override string AppId => "AppSettings";

    public override Control Root => Fragment;

    public override void Setup(IS14OsBui bui)
    {
        base.Setup(bui);

        Fragment.OnSetTheme += theme => Bui.SendSetTheme(theme);
        Fragment.OnShellAction += action => Bui.SendShellAction(action);
    }

    public override void UpdateShell(OsShellState shell)
    {
        Fragment.UpdateShell(shell);
    }

    public override void ApplyTheme(IS14ThemePalette palette)
    {
        Fragment.ApplyTheme(palette);
    }
}

[GenerateTypedNameReferences]
public sealed partial class SettingsAppFragment : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private readonly SpriteSystem _sprites;

    private IS14ThemePalette _palette = IS14ThemePalette.Default;
    private OsShellState? _shell;

    public event Action<string>? OnSetTheme;
    public event Action<OsShellAction>? OnShellAction;

    public SettingsAppFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _sprites = _sysMan.GetEntitySystem<SpriteSystem>();

        ThemeIcon.Texture = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Theme);
        ThemeCaption.Text = Loc.GetString("is14-os-settings-theme");
        AboutRow.Caption = Loc.GetString("is14-os-settings-about-caption");

        ThemeStrip.OnChoiceSelected += id => OnSetTheme?.Invoke(id);
    }

    public void UpdateShell(OsShellState shell)
    {
        _shell = shell;

        RebuildThemes(shell);
        RebuildActions(shell);

        AboutRow.Value = Loc.GetString("is14-os-settings-about",
            ("windows", shell.MaxWindows),
            ("memory", shell.MemoryTotal));
    }

    /// <summary>
    ///     Device switches, drawn as icon tiles rather than a stack of text buttons so the
    ///     dangerous one (the uplink) is visually distinct from the harmless ones.
    /// </summary>
    private void RebuildActions(OsShellState shell)
    {
        ActionList.RemoveAllChildren();

        if (shell.HasFlashlight)
        {
            AddAction(
                shell.FlashlightOn ? "is14-os-settings-flashlight-off" : "is14-os-settings-flashlight-on",
                IS14OsStyle.Light,
                OsShellAction.ToggleFlashlight,
                shell.FlashlightOn ? _palette.Warn : null);
        }

        if (shell.HasRinger)
            AddAction("is14-os-settings-ringtone", IS14OsStyle.Ringtone, OsShellAction.ShowRingtone, null);

        if (shell.HasUplink)
        {
            AddAction("is14-os-settings-uplink", IS14OsStyle.Uplink, OsShellAction.ShowUplink, _palette.Bad);
            AddAction("is14-os-settings-uplink-lock", IS14OsStyle.Lock, OsShellAction.LockUplink, _palette.Warn);
        }
    }

    private void AddAction(string locId, SpriteSpecifier icon, OsShellAction action, Color? tint)
    {
        var tile = new IconTile
        {
            Palette = _palette,
            Compact = true,
            Icon = IS14OsStyle.Resolve(_sprites, icon),
            Caption = Loc.GetString(locId),
            IconSize = 14,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 3),
        };

        if (tint != null)
            tile.ModulateSelfOverride = tint.Value;

        tile.OnPressed += _ => OnShellAction?.Invoke(action);
        ActionList.AddChild(tile);
    }

    /// <summary>
    ///     Themes are shown as their own accent colour rather than as a list of names — you pick
    ///     a look by seeing it.
    /// </summary>
    private void RebuildThemes(OsShellState shell)
    {
        var items = new List<ChoiceStripItem>();

        foreach (var theme in shell.Themes)
        {
            if (theme.Id is not { } id)
                continue;

            if (!_proto.TryIndex<IS14OsThemePrototype>(id, out var proto))
                continue;

            items.Add(new ChoiceStripItem(id, Loc.GetString(proto.Name), Swatch: proto.Accent));
        }

        ThemeStrip.SetItems(items, shell.ThemeId);
    }

    public void ApplyTheme(IS14ThemePalette palette)
    {
        _palette = palette;

        ThemeCaption.FontColorOverride = palette.Text;
        ThemeIcon.ModulateSelfOverride = palette.Accent;
        ThemeStrip.Palette = palette;
        AboutRow.Palette = palette;

        if (_shell != null)
            RebuildActions(_shell);
    }
}
