using Content.Client._IS14.Controls;
using Content.Client._IS14.OS.Shell;
using Content.Shared._IS14.OS.Prototypes;
using Content.Shared._IS14.OS.UI;
using Content.Shared._IS14.OS.UI.Apps;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Apps;

/// <summary>
///     Settings: theme and device toggles. Theme is device state rather than a client
///     preference — a syndicate-red PDA should look that way to everyone who sees the screen.
/// </summary>
public sealed class SettingsAppUi : IS14OsAppUi
{
    private SettingsAppFragment? _fragment;

    private SettingsAppFragment Fragment => _fragment ??= new SettingsAppFragment();

    public override string AppId => "AppSettings";

    public override Control Root => Fragment;

    public override void Setup(IS14OsBui bui)
    {
        base.Setup(bui);

        Fragment.OnSetTheme += theme => Bui.SendSetTheme(theme);
        Fragment.OnShellAction += action => Bui.SendShellAction(action);
        Fragment.OnSetWallpaper += (wallpaper, photo) =>
            SendAppEvent(AppId, new OsSettingsSetWallpaperEvent(wallpaper, photo));
    }

    public override void UpdateShell(OsShellState shell)
    {
        Fragment.UpdateShell(shell);
    }

    public override void UpdateState(IS14OsAppState state)
    {
        if (state is OsSettingsState settings)
            Fragment.UpdateState(settings);
    }

    public override void ApplyTheme(IS14ThemePalette palette)
    {
        Fragment.ApplyTheme(palette);
    }
}

[GenerateTypedNameReferences]
public sealed partial class SettingsAppFragment : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private readonly SpriteSystem _sprites;

    private IS14ThemePalette _palette = IS14ThemePalette.Default;
    private OsShellState? _shell;
    private OsSettingsState? _settings;

    /// <summary>Id the "no picture at all" entry carries; the theme's flat background wins.</summary>
    private const string NoWallpaper = "none";

    /// <summary>Mirrors IS14OsSystem.PhotoWallpaperPrefix.</summary>
    private const string PhotoPrefix = "photo:";

    public event Action<string>? OnSetTheme;
    public event Action<OsShellAction>? OnShellAction;
    public event Action<string?, int?>? OnSetWallpaper;

    public SettingsAppFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _sprites = _sysMan.GetEntitySystem<SpriteSystem>();

        ThemeIcon.Texture = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Theme);
        ThemeCaption.Text = Loc.GetString("is14-os-settings-theme");
        AboutRow.Caption = Loc.GetString("is14-os-settings-about-caption");

        ThemePicker.Placeholder = Loc.GetString("is14-os-settings-theme-none");
        ThemePicker.OnItemSelected += id => OnSetTheme?.Invoke(id);

        WallpaperIcon.Texture = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Wallpaper);
        WallpaperCaption.Text = Loc.GetString("is14-os-settings-wallpaper");
        WallpaperPicker.Placeholder = Loc.GetString("is14-os-settings-wallpaper-none");
        WallpaperPicker.OnItemSelected += OnWallpaperSelected;
    }

    public void UpdateShell(OsShellState shell)
    {
        _shell = shell;

        RebuildThemes(shell);
        RebuildActions(shell);
        RebuildWallpapers();

        AboutRow.Value = Loc.GetString("is14-os-settings-about",
            ("windows", shell.MaxWindows),
            ("memory", shell.MemoryTotal));
    }

    /// <summary>
    ///     Device switches, drawn as icon tiles rather than a stack of text buttons so the
    ///     dangerous one (the uplink) is visually distinct from the harmless ones.
    /// </summary>
    private void RebuildActions(OsShellState shell)
    {
        ActionList.RemoveAllChildren();

        if (shell.HasFlashlight)
        {
            AddAction(
                shell.FlashlightOn ? "is14-os-settings-flashlight-off" : "is14-os-settings-flashlight-on",
                IS14OsStyle.Light,
                OsShellAction.ToggleFlashlight,
                shell.FlashlightOn ? _palette.Warn : null);
        }

        if (shell.HasRinger)
            AddAction("is14-os-settings-ringtone", IS14OsStyle.Ringtone, OsShellAction.ShowRingtone, null);

        if (shell.HasUplink)
        {
            AddAction("is14-os-settings-uplink", IS14OsStyle.Uplink, OsShellAction.ShowUplink, _palette.Bad);
            AddAction("is14-os-settings-uplink-lock", IS14OsStyle.Lock, OsShellAction.LockUplink, _palette.Warn);
        }
    }

    private void AddAction(string locId, SpriteSpecifier icon, OsShellAction action, Color? tint)
    {
        var tile = new IconTile
        {
            Palette = _palette,
            Compact = true,
            Icon = IS14OsStyle.Resolve(_sprites, icon),
            Caption = Loc.GetString(locId),
            IconSize = 14,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 3),
        };

        if (tint != null)
            tile.ModulateSelfOverride = tint.Value;

        tile.OnPressed += _ => OnShellAction?.Invoke(action);
        ActionList.AddChild(tile);
    }

    /// <summary>
    ///     Themes are folded into a dropdown, each entry carrying its own accent colour: the
    ///     list of looks is worth a click, but not the standing height it used to cost on a
    ///     screen this small.
    /// </summary>
    private void RebuildThemes(OsShellState shell)
    {
        var items = new List<ChoiceStripItem>();

        foreach (var theme in shell.Themes)
        {
            if (theme.Id is not { } id)
                continue;

            if (!_proto.TryIndex<IS14OsThemePrototype>(id, out var proto))
                continue;

            items.Add(new ChoiceStripItem(id, Loc.GetString(proto.Name), Swatch: proto.Accent));
        }

        ThemePicker.SetItems(items, shell.ThemeId);
    }

    public void UpdateState(OsSettingsState state)
    {
        _settings = state;
        RebuildWallpapers();
    }

    /// <summary>
    ///     Wallpapers and the device's own photos in one list, because to the player they are
    ///     the same choice: what is behind the icons. A picture you took yourself is the point
    ///     of the feature, so it sits alongside the stock ones rather than in a second menu.
    /// </summary>
    private void RebuildWallpapers()
    {
        var items = new List<ChoiceStripItem>
        {
            new(NoWallpaper, Loc.GetString("is14-os-settings-wallpaper-none")),
        };

        if (_settings != null)
        {
            foreach (var wallpaper in _settings.Wallpapers)
            {
                if (wallpaper.Id is { } id && _proto.TryIndex<IS14OsWallpaperPrototype>(id, out var proto))
                    items.Add(new ChoiceStripItem(id, Loc.GetString(proto.Name)));
            }

            foreach (var photo in _settings.Photos)
            {
                items.Add(new ChoiceStripItem(PhotoPrefix + photo.Id,
                    photo.Name,
                    IS14OsStyle.Resolve(_sprites, IS14OsStyle.Photo)));
            }
        }

        WallpaperPicker.SetItems(items, _shell?.Wallpaper ?? NoWallpaper);
    }

    private void OnWallpaperSelected(string id)
    {
        if (id == NoWallpaper)
            OnSetWallpaper?.Invoke(null, null);
        else if (id.StartsWith(PhotoPrefix) && int.TryParse(id.AsSpan(PhotoPrefix.Length), out var photo))
            OnSetWallpaper?.Invoke(null, photo);
        else
            OnSetWallpaper?.Invoke(id, null);
    }

    public void ApplyTheme(IS14ThemePalette palette)
    {
        _palette = palette;

        ThemeCaption.FontColorOverride = palette.Text;
        ThemeIcon.ModulateSelfOverride = palette.Accent;
        ThemePicker.Palette = palette;
        WallpaperCaption.FontColorOverride = palette.Text;
        WallpaperIcon.ModulateSelfOverride = palette.Accent;
        WallpaperPicker.Palette = palette;
        AboutRow.Palette = palette;

        if (_shell != null)
            RebuildActions(_shell);
    }
}
