using Content.Client._IS14.Controls;
using Content.Client._IS14.OS.Shell;
using Content.Client.GameTicking.Managers;
using Content.Shared._IS14.OS.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._IS14.OS.Apps;

/// <summary>
///     Status: who owns the device, where it is, and what the station is doing.
///     Renders straight from the shell state — no server traffic of its own.
/// </summary>
public sealed class StatusAppUi : IS14OsAppUi
{
    private StatusAppFragment? _fragment;

    private StatusAppFragment Fragment => _fragment ??= new StatusAppFragment();

    public override string AppId => "AppStatus";

    public override Control Root => Fragment;

    public override void UpdateShell(OsShellState shell)
    {
        Fragment.UpdateShell(shell);
    }

    public override void ApplyTheme(IS14ThemePalette palette)
    {
        Fragment.ApplyTheme(palette);
    }
}

[GenerateTypedNameReferences]
public sealed partial class StatusAppFragment : BoxContainer
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private ClientGameTicker? _ticker;

    public StatusAppFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        var sprites = _sysMan.GetEntitySystem<SpriteSystem>();

        OwnerRow.Icon = IS14OsStyle.Resolve(sprites, IS14OsStyle.Owner);
        JobRow.Icon = IS14OsStyle.Resolve(sprites, IS14OsStyle.Job);
        StationRow.Icon = IS14OsStyle.Resolve(sprites, IS14OsStyle.Station);
        AlertRow.Icon = IS14OsStyle.Resolve(sprites, IS14OsStyle.Alert);
        TimeRow.Icon = IS14OsStyle.Resolve(sprites, IS14OsStyle.Clock);
        AddressRow.Icon = IS14OsStyle.Resolve(sprites, IS14OsStyle.Address);

        OwnerRow.Caption = Loc.GetString("is14-os-status-owner");
        JobRow.Caption = Loc.GetString("is14-os-status-job");
        StationRow.Caption = Loc.GetString("is14-os-status-station");
        AlertRow.Caption = Loc.GetString("is14-os-status-alert");
        TimeRow.Caption = Loc.GetString("is14-os-status-time");
        AddressRow.Caption = Loc.GetString("is14-os-status-address");
    }

    public void UpdateShell(OsShellState shell)
    {
        _ticker ??= _sysMan.GetEntitySystem<ClientGameTicker>();

        var unknown = Loc.GetString("is14-os-status-unknown");

        OwnerRow.Value = shell.IdName ?? shell.OwnerName ?? unknown;
        JobRow.Value = shell.IdJob ?? unknown;
        StationRow.Value = shell.StationName ?? unknown;

        if (string.IsNullOrEmpty(shell.AlertLevel))
        {
            AlertRow.Value = unknown;
            AlertRow.ValueColor = null;
            InstructionsLabel.SetMessage(string.Empty);
        }
        else
        {
            AlertRow.Value = shell.AlertLevel;
            AlertRow.ValueColor = shell.AlertColor;
            InstructionsLabel.SetMessage(shell.AlertInstructions ?? string.Empty);
        }

        var time = _ticker != null ? _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan) : TimeSpan.Zero;
        TimeRow.Value = time.ToString("hh\\:mm\\:ss");

        AddressRow.Visible = shell.Address != null;
        AddressRow.Value = shell.Address;
    }

    public void ApplyTheme(IS14ThemePalette palette)
    {
        OwnerRow.Palette = palette;
        JobRow.Palette = palette;
        StationRow.Palette = palette;
        AlertRow.Palette = palette;
        TimeRow.Palette = palette;
        AddressRow.Palette = palette;
    }
}
