using Content.Shared._IS14.Economy.Atm;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Economy.Atm;

[GenerateTypedNameReferences]
public sealed partial class IS14AtmWindow : DefaultWindow
{
    private const int PinLength = 4;

    private readonly IEntityManager _entManager;

    private IS14AtmUiState? _lastState;
    private string _pinInput = string.Empty;
    /// <summary>Local mode: an authenticated user is entering a new PIN via the numpad.</summary>
    private bool _changingPin;

    /// <summary>Fired on numpad OK. The screen tells the BUI which message to send
    /// (SetPin/EnterPin; anything else means a PIN change).</summary>
    public event Action<IS14AtmScreen, string>? OnPinSubmitted;
    public event Action<int>? OnWithdraw;
    public event Action<int, int>? OnTransfer;
    public event Action? OnEjectCard;

    public IS14AtmWindow()
    {
        RobustXamlLoader.Load(this);

        _entManager = IoCManager.Resolve<IEntityManager>();

        WireNumpad();

        PinCancelBtn.OnPressed += _ =>
        {
            _changingPin = false;
            _pinInput = string.Empty;
            RefreshView();
        };

        Withdraw50Btn.OnPressed += _ => AddToWithdrawAmount(50);
        Withdraw100Btn.OnPressed += _ => AddToWithdrawAmount(100);
        Withdraw500Btn.OnPressed += _ => AddToWithdrawAmount(500);
        WithdrawBtn.OnPressed += _ =>
        {
            if (TryParseAmount(WithdrawAmountEdit.Text, out var amount))
                OnWithdraw?.Invoke(amount);
        };

        TransferBtn.OnPressed += _ =>
        {
            var accountText = TransferAccountEdit.Text.Trim().TrimStart('#');
            if (int.TryParse(accountText, out var account)
                && TryParseAmount(TransferAmountEdit.Text, out var amount))
            {
                OnTransfer?.Invoke(account, amount);
            }
        };

        ChangePinBtn.OnPressed += _ =>
        {
            _changingPin = true;
            _pinInput = string.Empty;
            RefreshView();
        };

        EjectCardBtn.OnPressed += _ => OnEjectCard?.Invoke();
    }

    public void UpdateState(IS14AtmUiState state)
    {
        _lastState = state;

        if (state.Screen != IS14AtmScreen.Menu)
            _changingPin = false;
        _pinInput = string.Empty;

        RefreshView();
    }

    // ── Numpad ────────────────────────────────────────────────────────────────

    private void WireNumpad()
    {
        var digits = new[]
        {
            (PinBtn0, "0"), (PinBtn1, "1"), (PinBtn2, "2"), (PinBtn3, "3"), (PinBtn4, "4"),
            (PinBtn5, "5"), (PinBtn6, "6"), (PinBtn7, "7"), (PinBtn8, "8"), (PinBtn9, "9"),
        };

        foreach (var (btn, digit) in digits)
        {
            var capturedDigit = digit;
            btn.OnPressed += _ =>
            {
                if (_pinInput.Length >= PinLength)
                    return;
                _pinInput += capturedDigit;
                RefreshPinDisplay();

                // Plain login doesn't need an OK press: submit as soon as the 4th digit is in.
                // Picking a new PIN (first login / change) still requires explicit confirmation.
                if (_pinInput.Length == PinLength && !_changingPin
                    && _lastState?.Screen == IS14AtmScreen.EnterPin)
                {
                    SubmitPin();
                }
            };
        }

        PinBtnClear.OnPressed += _ =>
        {
            _pinInput = string.Empty;
            RefreshPinDisplay();
        };

        PinBtnOk.OnPressed += _ => SubmitPin();
    }

    private void SubmitPin()
    {
        if (_lastState == null || _pinInput.Length != PinLength)
            return;

        var screen = _changingPin ? IS14AtmScreen.Menu : _lastState.Screen;
        OnPinSubmitted?.Invoke(screen, _pinInput);
        _pinInput = string.Empty;

        // A PIN change is fire-and-forget: drop back to the account menu right away.
        if (_changingPin)
        {
            _changingPin = false;
            RefreshView();
            return;
        }

        RefreshPinDisplay();
    }

    private void AddToWithdrawAmount(int delta)
    {
        int.TryParse(WithdrawAmountEdit.Text.Trim(), out var current);
        WithdrawAmountEdit.Text = (current + delta).ToString();
    }

    private void RefreshPinDisplay()
    {
        const string mask = "****";
        const string blanks = "____";
        PinDisplayLabel.Text = mask[.._pinInput.Length] + blanks[_pinInput.Length..];
    }

    // ── View ──────────────────────────────────────────────────────────────────

    private void RefreshView()
    {
        if (_lastState == null)
            return;

        var state = _lastState;
        var screen = state.Screen;
        if (screen == IS14AtmScreen.Menu && _changingPin)
            screen = IS14AtmScreen.SetPin; // show the numpad locally

        NoCardPanel.Visible = state.Screen == IS14AtmScreen.NoCard;
        LockedPanel.Visible = state.Screen == IS14AtmScreen.Locked;
        PinPanel.Visible = screen is IS14AtmScreen.SetPin or IS14AtmScreen.EnterPin;
        MenuPanel.Visible = state.Screen == IS14AtmScreen.Menu && !_changingPin;

        CardOwnerLabel.Text = state.AccountNumber > 0
            ? Loc.GetString("is14-atm-card-header", ("owner", state.CardOwner), ("account", state.AccountNumber))
            : state.CardOwner;

        // Show the sprite of the actual inserted card, falling back to a generic icon.
        if (state.IdCard.HasValue && _entManager.TryGetEntity(state.IdCard.Value, out var cardUid))
        {
            CardIcon.SetEntity(cardUid);
            CardIcon.Visible = true;
            CardIconFallback.Visible = false;
        }
        else
        {
            CardIcon.SetEntity(null);
            CardIcon.Visible = false;
            CardIconFallback.Visible = state.IdCard.HasValue;
        }

        if (_changingPin)
            PinPromptLabel.Text = Loc.GetString("is14-atm-change-pin-prompt");
        else if (state.Screen == IS14AtmScreen.SetPin)
            PinPromptLabel.Text = Loc.GetString("is14-atm-set-pin-prompt");
        else
            PinPromptLabel.Text = Loc.GetString("is14-atm-enter-pin-prompt");

        AttemptsLabel.Visible = state.Screen == IS14AtmScreen.EnterPin && !_changingPin;
        AttemptsLabel.Text = Loc.GetString("is14-atm-attempts-left", ("attempts", state.AttemptsLeft));
        PinCancelBtn.Visible = _changingPin;

        LockedLabel.Text = Loc.GetString("is14-atm-locked", ("seconds", state.LockSecondsLeft));
        BalanceLabel.Text = Loc.GetString("is14-vending-balance-value", ("balance", state.Balance));
        StatusLabel.Text = state.StatusMessage;

        RefreshPinDisplay();
    }

    private static bool TryParseAmount(string text, out int amount)
        => int.TryParse(text.Trim(), out amount) && amount > 0;
}
