- type: latheRecipePack
  id: SecurityCaptureDevicePack
  recipes:
  - WeaponGrapplingGunHunter

- type: latheRecipePack
  id: SecurityAmmoStaticCorvaxGoob
  recipes:
  - MagazineLargeCaliber
  - MagazineBoxLargeCaliber
