// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Research;

/// <summary>Where a technology stands right now, in one word.</summary>
public enum IS14NodeState : byte
{
    /// <summary>Prerequisites are missing: it is not on the table yet.</summary>
    Locked,

    /// <summary>
    /// Prerequisites are done, but this one is not bought with data at all: it wants a sample
    /// destroyed in the analyzer first.
    /// </summary>
    NeedsSample,

    /// <summary>An alternative to it has been researched, so this road is closed for good.</summary>
    Excluded,

    /// <summary>Prerequisites are done but the station cannot pay.</summary>
    Unaffordable,

    /// <summary>Ready to buy.</summary>
    Available,

    Researched,
}

/// <summary>
/// One technology on the research map: a coloured square with the technology's icon and nothing
/// else. The colour is the whole message — green researched, yellow ready, orange short of data,
/// red still blocked — while the name, the price and the details live in the side panel, and the
/// tooltip covers the quick look.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class IS14ResearchNode : PanelContainer
{
    public const int Size = 64;

    /// <summary>Distance between map columns and rows, node size included.</summary>
    public const int ColumnStride = 120;

    public const int RowStride = 84;

    public TechnologyPrototype Prototype = default!;

    public IS14NodeState State { get; private set; } = IS14NodeState.Locked;

    public bool Selected;

    public event Action<string>? OnSelected;

    public IS14ResearchNode()
    {
        RobustXamlLoader.Load(this);

        NodeButton.OnPressed += _ => OnSelected?.Invoke(Prototype.ID);
    }

    public void Initialize(TechnologyPrototype prototype, SpriteSystem sprites)
    {
        Prototype = prototype;
        IconRect.Texture = sprites.Frame0(prototype.Icon);
    }

    /// <summary>
    /// Sets the colour and the hover text. The tooltip carries the name and the price, because
    /// the square itself shows neither.
    /// </summary>
    public void UpdateState(IS14NodeState state, string tooltip)
    {
        State = state;
        ToolTip = tooltip;
        UpdatePanel();
    }

    private void UpdatePanel()
    {
        var (background, border) = State switch
        {
            IS14NodeState.Researched => (Color.FromHex("#23422a"), Color.FromHex("#5ec45e")),
            IS14NodeState.Available => (Color.FromHex("#4a4718"), Color.FromHex("#e8fa25")),
            IS14NodeState.Unaffordable => (Color.FromHex("#42331a"), Color.FromHex("#cca031")),
            // A breakthrough is not short of data, it is waiting for an object: violet, so it
            // never reads as "come back when you have saved up".
            IS14NodeState.NeedsSample => (Color.FromHex("#2b2244"), Color.FromHex("#9a6ef0")),
            IS14NodeState.Excluded => (Color.FromHex("#262629"), Color.FromHex("#5a5a60")),
            _ => (Color.FromHex("#3a1c1f"), Color.FromHex("#a33b40")),
        };

        // Blocked and closed technologies are dimmed as well as coloured: their icon should
        // not draw the eye.
        IconRect.ModulateSelfOverride = State is IS14NodeState.Locked or IS14NodeState.Excluded
            ? Color.FromHex("#8f8f96")
            : Color.White;

        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = Selected ? Color.White : border,
            BorderThickness = new Thickness(Selected ? 3 : 2),
        };
    }

    public void SetSelected(bool selected)
    {
        Selected = selected;
        UpdatePanel();
    }
}
