// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Research;

/// <summary>One orderable topic: what it is, which branch it belongs to, and a button.</summary>
[GenerateTypedNameReferences]
public sealed partial class IS14WorkOrderRow : BoxContainer
{
    public event Action<string>? OnOrder;

    private string _technologyId = string.Empty;

    public IS14WorkOrderRow()
    {
        RobustXamlLoader.Load(this);

        OrderButton.OnPressed += _ => OnOrder?.Invoke(_technologyId);
    }

    public void SetRow(
        TechnologyPrototype tech,
        TechDisciplinePrototype? branch,
        bool ordered,
        SpriteSystem sprites)
    {
        _technologyId = tech.ID;

        NameLabel.Text = Loc.GetString(tech.Name);
        BranchLabel.Text = branch != null
            ? $"{Loc.GetString(branch.Name)} · {Loc.GetString("is14-research-card-tier", ("tier", tech.Tier))}"
            : Loc.GetString("is14-research-card-tier", ("tier", tech.Tier));

        IconRect.Texture = sprites.Frame0(tech.Icon);

        OrderButton.Text = Loc.GetString(ordered ? "is14-workorder-cancel" : "is14-workorder-order");
        OrderButton.Disabled = false;

        RowPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(ordered ? "#2b2a16" : "#1B1B1E"),
            BorderColor = Color.FromHex(ordered ? "#cca031" : "#3a3a41"),
            BorderThickness = new Thickness(1),
        };
    }
}
