// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._IS14.Research;

/// <summary>One branch of the tree: a draggable map of its technologies.</summary>
[GenerateTypedNameReferences]
public sealed partial class IS14ResearchBranchTab : BoxContainer
{
    public IS14ResearchBranchTab()
    {
        RobustXamlLoader.Load(this);

        ZoomSlider.OnValueChanged += _ => Map.SetZoom(ZoomSlider.Value);
        CenterButton.OnPressed += _ => Map.Center();

        // The wheel and the slider are the same control in two shapes, so each follows the
        // other instead of fighting it.
        Map.OnZoomChanged += zoom =>
        {
            if (!MathHelper.CloseTo(ZoomSlider.Value, zoom))
                ZoomSlider.Value = zoom;
        };
    }

    /// <summary>Places a node by its grid coordinates from the prototype.</summary>
    public void AddNode(IS14ResearchNode node, int column, int row)
    {
        Map.Place(node, new Vector2(column * IS14ResearchNode.ColumnStride, row * IS14ResearchNode.RowStride));
    }

    /// <summary>Slides the map so this node sits in the middle of the viewport.</summary>
    public void CenterOn(IS14ResearchNode node)
    {
        Map.CenterOn(node);
    }

    /// <summary>Screen rectangle of the map, used to decide whether a drag pans or moves the window.</summary>
    public UIBox2 MapRect => Map.GlobalRect;

    /// <summary>Forwards a mouse move to the map, which pans only while it is being dragged.</summary>
    public void Pan(Vector2 delta)
    {
        Map.Pan(delta);
    }

    public void StopDrag()
    {
        Map.StopDrag();
    }
}
