// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Input;
using Content.Shared._IS14.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._IS14.Research;

/// <summary>
/// The NIC console: a map of the tree per branch, with the selected topic explained on the right.
/// </summary>
/// <remarks>
/// The map is built once and only its node states are refreshed, because the server pushes a
/// fresh balance every second while the window is open.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class IS14ResearchConsoleWindow : FancyWindow
{
    private readonly IEntityManager _entManager;
    private readonly IPrototypeManager _protoManager;
    private readonly SpriteSystem _sprites;
    private readonly IS14ResearchCostSystem _costs;

    private readonly Dictionary<string, IS14ResearchNode> _nodes = new();
    private readonly Dictionary<string, IS14PointCounter> _counters = new();
    private readonly List<IS14ResearchBranchTab> _tabs = new();
    private readonly List<Button> _branchButtons = new();

    private string? _selected;
    private bool _built;

    /// <summary>
    /// What the map was built for. A hidden topic uncovered mid-shift — the First Department
    /// taking a trophy apart — has to appear without the console being closed and reopened.
    /// </summary>
    private string _builtRevealed = string.Empty;
    private IS14ResearchConsoleUiState _state = new();

    public event Action<string>? OnResearchPressed;

    public IS14ResearchConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        _entManager = IoCManager.Resolve<IEntityManager>();
        _protoManager = IoCManager.Resolve<IPrototypeManager>();
        _sprites = _entManager.System<SpriteSystem>();
        _costs = _entManager.System<IS14ResearchCostSystem>();

        Details.OnResearchPressed += id => OnResearchPressed?.Invoke(id);
        Details.OnClosePressed += Deselect;
    }

    public void UpdateState(IS14ResearchConsoleUiState state)
    {
        _state = state;
        BuildMap(state);
        UpdateHeader(state);

        var unlocked = new HashSet<string>(state.Unlocked);

        foreach (var (id, node) in _nodes)
        {
            if (!_protoManager.TryIndex(id, out TechnologyPrototype? tech))
                continue;

            var costs = Price(tech, state);
            node.UpdateState(NodeState(tech, costs, state, unlocked), Tooltip(tech, costs));
        }

        ShowSelected(state);
    }

    /// <summary>
    /// Hover text for a square on the map: its name and price, since the square shows neither.
    /// </summary>
    private string Tooltip(TechnologyPrototype tech, Dictionary<ProtoId<ResearchPointTypePrototype>, int> costs)
    {
        var parts = new List<string>();

        foreach (var (typeId, amount) in costs.OrderBy(pair => pair.Key.Id))
        {
            var name = _protoManager.TryIndex(typeId, out ResearchPointTypePrototype? type)
                ? Loc.GetString(type.ShortName)
                : typeId.Id;

            parts.Add($"{amount} {name}");
        }

        return $"{Loc.GetString(tech.Name)}\n{string.Join(", ", parts)}";
    }

    /// <summary>
    /// What the console will actually charge: the table price less reverse-engineering credit
    /// and the shift's priority list. Mirrors the server's own sum, capped the same way.
    /// </summary>
    private Dictionary<ProtoId<ResearchPointTypePrototype>, int> Price(
        TechnologyPrototype tech,
        IS14ResearchConsoleUiState state)
    {
        return IS14ResearchCostSystem.Discounted(_costs.GetCost(tech), TotalDiscount(tech.ID, state));
    }

    private static float TotalDiscount(string technologyId, IS14ResearchConsoleUiState state)
    {
        state.Discounts.TryGetValue(technologyId, out var reverse);
        state.Priorities.TryGetValue(technologyId, out var priority);

        return MathF.Min(IS14ResearchCostSystem.MaxDiscount, reverse + priority);
    }

    /// <summary>
    /// Where a technology stands: researched, closed off by an alternative, waiting for a
    /// sample, buyable, too expensive, or still blocked by its prerequisites.
    /// </summary>
    private IS14NodeState NodeState(
        TechnologyPrototype tech,
        Dictionary<ProtoId<ResearchPointTypePrototype>, int> costs,
        IS14ResearchConsoleUiState state,
        HashSet<string> unlocked)
    {
        if (unlocked.Contains(tech.ID))
            return IS14NodeState.Researched;

        // A fork already taken: no amount of data reopens it.
        foreach (var sibling in _costs.GetExclusiveSiblings(tech.ID))
        {
            if (unlocked.Contains(sibling))
                return IS14NodeState.Excluded;
        }

        if (!tech.TechnologyPrerequisites.All(prereq => unlocked.Contains(prereq.Id)))
            return IS14NodeState.Locked;

        if (_costs.GetBreakthrough(tech.ID) != null && !state.Breakthroughs.Contains(tech.ID))
            return IS14NodeState.NeedsSample;

        foreach (var (typeId, amount) in costs)
        {
            state.Points.TryGetValue(typeId.Id, out var balance);

            if (balance < amount)
                return IS14NodeState.Unaffordable;
        }

        return IS14NodeState.Available;
    }

    private void UpdateHeader(IS14ResearchConsoleUiState state)
    {
        ServerLabel.Text = state.ServerConnected
            ? Loc.GetString("is14-research-console-server", ("name", state.ServerName))
            : Loc.GetString("is14-research-console-no-server");

        IncomeHintLabel.Text = Loc.GetString("is14-research-console-income-hint", ("minutes", state.IncomeWindowMinutes));

        foreach (var type in _costs.SortedTypes())
        {
            if (!_counters.TryGetValue(type.ID, out var counter))
            {
                counter = new IS14PointCounter();
                _counters[type.ID] = counter;
                PointsContainer.AddChild(counter);
            }

            state.Points.TryGetValue(type.ID, out var amount);
            state.RecentIncome.TryGetValue(type.ID, out var income);

            counter.SetCounter(type, amount, income, state.IncomeWindowMinutes, _sprites);
        }
    }

    private void ShowSelected(IS14ResearchConsoleUiState state)
    {
        if (_selected == null || !_protoManager.TryIndex(_selected, out TechnologyPrototype? tech))
        {
            Details.Clear();
            Details.Visible = false;
            return;
        }

        Details.Visible = true;

        var costs = Price(tech, state);
        var unlocked = new HashSet<string>(state.Unlocked);
        state.Discounts.TryGetValue(tech.ID, out var reverse);
        state.Priorities.TryGetValue(tech.ID, out var priority);

        Details.Show(
            tech,
            _costs.GetData(tech.ID),
            costs,
            state.Points,
            unlocked,
            NodeState(tech, costs, state, unlocked),
            state.ServerConnected,
            reverse,
            priority,
            _costs.GetExclusiveSiblings(tech.ID));
    }

    /// <summary>
    /// Builds one tab per branch, nodes placed by their prototype position. Hidden technologies
    /// are left out entirely: they do not exist until contraband reveals them.
    /// </summary>
    private void BuildMap(IS14ResearchConsoleUiState state)
    {
        var revealedKey = string.Join(',', state.Revealed.OrderBy(id => id));

        if (_built && revealedKey == _builtRevealed)
            return;

        if (_built)
        {
            // Rebuilt from scratch: the node set itself changed, and this happens a couple of
            // times a shift at most.
            foreach (var tab in _tabs)
            {
                MapArea.RemoveChild(tab);
            }

            foreach (var button in _branchButtons)
            {
                BranchStrip.RemoveChild(button);
            }

            _tabs.Clear();
            _branchButtons.Clear();
            _nodes.Clear();
        }

        _built = true;
        _builtRevealed = revealedKey;

        var branches = state.Branches.Count > 0
            ? state.Branches
            : _protoManager.EnumeratePrototypes<TechDisciplinePrototype>().Select(d => d.ID).OrderBy(id => id).ToList();

        var byBranch = new Dictionary<string, List<TechnologyPrototype>>();

        var revealed = new HashSet<string>(state.Revealed);

        foreach (var tech in _protoManager.EnumeratePrototypes<TechnologyPrototype>())
        {
            if (!branches.Contains(tech.Discipline.Id))
                continue;

            // A hidden technology is drawn only if this station rolled or uncovered it.
            if (tech.Hidden && !revealed.Contains(tech.ID))
                continue;

            if (!byBranch.TryGetValue(tech.Discipline.Id, out var list))
            {
                list = new List<TechnologyPrototype>();
                byBranch[tech.Discipline.Id] = list;
            }

            list.Add(tech);
        }

        foreach (var branchId in branches)
        {
            if (!byBranch.TryGetValue(branchId, out var technologies))
                continue;

            var tab = new IS14ResearchBranchTab();

            foreach (var tech in technologies.OrderBy(t => t.Position.X).ThenBy(t => t.Position.Y))
            {
                var node = new IS14ResearchNode();
                node.Initialize(tech, _sprites);
                node.OnSelected += Select;

                _nodes[tech.ID] = node;
                tab.AddNode(node, tech.Position.X, tech.Position.Y);
            }

            var discipline = _protoManager.TryIndex(branchId, out TechDisciplinePrototype? proto) ? proto : null;
            var index = _tabs.Count;

            tab.Visible = index == 0;
            MapArea.AddChild(tab);
            _tabs.Add(tab);

            var button = new Button
            {
                Text = discipline?.UiName ?? branchId,
                ToolTip = discipline != null ? Loc.GetString(discipline.Name) : branchId,
                MinHeight = 46,
                StyleClasses = { "ButtonSquare" },
            };

            if (discipline != null)
                button.ModulateSelfOverride = discipline.Color.WithAlpha(0.65f);

            button.OnPressed += _ => ShowBranch(index);

            BranchStrip.AddChild(button);
            _branchButtons.Add(button);
        }

        ShowBranch(0);
    }

    /// <summary>Switches the visible branch map and marks its tag in the strip.</summary>
    private void ShowBranch(int index)
    {
        for (var i = 0; i < _tabs.Count; i++)
        {
            _tabs[i].Visible = i == index;
            _branchButtons[i].Pressed = i == index;
        }

        BranchLabel.Text = _branchButtons.Count > index ? _branchButtons[index].ToolTip ?? string.Empty : string.Empty;
    }

    /// <summary>
    /// Keeps the window still while the map is being dragged. FancyWindow treats its whole body as
    /// a move handle, which would otherwise drag the console around instead of panning the tree.
    /// Resize edges still win, so the window can be resized from its borders as usual.
    /// </summary>
    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = base.GetDragModeFor(relativeMousePos);

        if (mode != DragMode.Move)
            return mode;

        var global = GlobalPosition + relativeMousePos;

        foreach (var tab in _tabs)
        {
            if (tab.Visible && tab.MapRect.Contains(global))
                return DragMode.None;
        }

        return mode;
    }

    /// <summary>
    /// Drags the open map. Mouse moves only reach the control under the cursor, and while panning
    /// that is usually a node, so the window forwards every move to the maps; a map that is not
    /// being dragged ignores it.
    /// </summary>
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        foreach (var tab in _tabs)
        {
            tab.Pan(args.Relative);
        }
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        // Releasing anywhere ends the drag, including outside the map.
        if (args.Function != EngineKeyFunctions.Use && args.Function != EngineKeyFunctions.UIRightClick)
            return;

        foreach (var tab in _tabs)
        {
            tab.StopDrag();
        }
    }

    /// <summary>Closes the detail panel and drops the highlight.</summary>
    private void Deselect()
    {
        if (_selected != null && _nodes.TryGetValue(_selected, out var node))
            node.SetSelected(false);

        _selected = null;
        Details.Clear();
        Details.Visible = false;
    }

    private void Select(string technologyId)
    {
        if (_selected != null && _nodes.TryGetValue(_selected, out var previous))
            previous.SetSelected(false);

        _selected = technologyId;

        if (_nodes.TryGetValue(technologyId, out var node))
            node.SetSelected(true);

        // Redraw the panel immediately from the last state instead of waiting for the next push.
        ShowSelected(_state);
    }
}
