// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._IS14.Research;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Research;

/// <summary>
/// One balance in the console header, with what came in over the last few minutes —
/// which is how the department sees who is actually feeding them data.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class IS14PointCounter : BoxContainer
{
    public IS14PointCounter()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetCounter(ResearchPointTypePrototype type, int amount, int income, int windowMinutes, SpriteSystem sprites)
    {
        NameLabel.Text = Loc.GetString(type.Name);
        NameLabel.FontColorOverride = type.Color;
        AmountLabel.Text = amount.ToString();

        IconRect.Visible = type.Icon != null;
        if (type.Icon != null)
            IconRect.Texture = sprites.Frame0(type.Icon);

        IncomeLabel.Text = income > 0 ? $"+{income}" : string.Empty;
        IncomeLabel.FontColorOverride = Color.FromHex("#7ecd48");

        CounterPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = type.Color.WithAlpha(0.13f),
            BorderColor = type.Color.WithAlpha(0.7f),
            BorderThickness = new Thickness(1),
        };

        var tooltip = Loc.GetString("is14-research-counter-tooltip",
            ("minutes", windowMinutes),
            ("income", income));

        if (type.Description != null)
            tooltip = $"{Loc.GetString(type.Description)}\n{tooltip}";

        if (type.Donor != null)
            tooltip = $"{tooltip}\n{Loc.GetString("is14-research-counter-donor", ("donor", Loc.GetString(type.Donor)))}";

        ToolTip = tooltip;
    }
}
