using System.Numerics;
using Content.Client.Pinpointer.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._IS14.Economy.EconomyMonitor;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._IS14.Economy.EconomyMonitor;

[GenerateTypedNameReferences]
public sealed partial class EconomyMonitorWindow : FancyWindow
{
    private static readonly Color ColIncome   = Color.FromHex("#66CC66");
    private static readonly Color ColExpense  = Color.FromHex("#CC6666");
    private static readonly Color ColNeutral  = Color.FromHex("#AAAAAA");
    private static readonly Color ColMuted    = Color.FromHex("#666666");
    private static readonly Color ColRowEven  = Color.FromHex("#0E1320");
    private static readonly Color ColRowOdd   = Color.FromHex("#141A28");
    private static readonly Color ColSelected = Color.FromHex("#1A3A2A");

    private readonly IEntityManager _entManager;
    private readonly IPrototypeManager _proto;
    private readonly SharedTransformSystem _transform;
    private readonly SpriteSystem _sprites;
    private readonly Texture _fallbackTexture;

    private EconomyMonitorUiState? _lastState;
    private NetEntity? _selectedVendor;

    public EconomyMonitorWindow()
    {
        RobustXamlLoader.Load(this);

        _entManager = IoCManager.Resolve<IEntityManager>();
        _proto = IoCManager.Resolve<IPrototypeManager>();
        _transform = _entManager.System<SharedTransformSystem>();
        _sprites = _entManager.System<SpriteSystem>();
        _fallbackTexture = _sprites.Frame0(
            new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_square.png")));

        NavMap.TrackedEntitySelectedAction += OnMapEntitySelected;

        AccountSearch.OnTextChanged += _ => RefreshLog();

        ClearBtn.OnPressed += _ =>
        {
            AccountSearch.Clear();
            _selectedVendor = null;
            NavMap.FocusVendor = null;
            RefreshVendorList();
            RefreshLog();
        };
    }

    public void UpdateState(EconomyMonitorUiState state)
    {
        _lastState = state;

        if (state.GridEntity.HasValue && _entManager.TryGetEntity(state.GridEntity.Value, out var gridUid))
            NavMap.MapUid = gridUid;
        else
            NavMap.Visible = false;

        RefreshVendorList();
        RefreshLog();
    }

    // ── Vendor list ───────────────────────────────────────────────────────────

    private void RefreshVendorList()
    {
        VendorList.RemoveAllChildren();
        NavMap.TrackedEntities.Clear();
        NavMap.LocalizedNames.Clear();

        if (_lastState == null)
            return;

        var allBtn = new Button
        {
            Text = Loc.GetString("economy-monitor-vendor-all"),
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _selectedVendor == null,
        };
        allBtn.OnPressed += _ =>
        {
            _selectedVendor = null;
            NavMap.FocusVendor = null;
            RefreshVendorList();
            RefreshLog();
        };
        VendorList.AddChild(allBtn);

        foreach (var vendor in _lastState.Vendors)
        {
            var coords = _entManager.GetCoordinates(vendor.Coordinates);
            var localCoords = NavMap.MapUid.HasValue
                ? _transform.WithEntityId(coords, NavMap.MapUid.Value)
                : coords;

            var isSelected = _selectedVendor == vendor.Entity;

            var blipTex = _fallbackTexture;
            if (vendor.PrototypeId != null
                && _proto.TryIndex<EntityPrototype>(vendor.PrototypeId, out var proto))
            {
                blipTex = _sprites.Frame0(proto);
            }

            NavMap.TrackedEntities[vendor.Entity] = new NavMapBlip(
                localCoords,
                blipTex,
                Color.White.WithAlpha(isSelected ? 1.0f : 0.7f),
                blinks: isSelected,
                selectable: true,
                scale: 1.5f);

            NavMap.LocalizedNames[vendor.Entity] = vendor.Name;

            var btn = new Button
            {
                Text = vendor.Name,
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = isSelected,
            };

            var capturedVendor = vendor;
            var capturedCoords = localCoords;
            btn.OnPressed += _ =>
            {
                _selectedVendor = _selectedVendor == capturedVendor.Entity ? null : capturedVendor.Entity;
                NavMap.FocusVendor = _selectedVendor;
                if (_selectedVendor.HasValue)
                    NavMap.CenterToCoordinates(capturedCoords);
                RefreshVendorList();
                RefreshLog();
            };

            VendorList.AddChild(btn);
        }
    }

    // ── Log rows ──────────────────────────────────────────────────────────────

    private void RefreshLog()
    {
        LogRows.RemoveAllChildren();

        if (_lastState == null)
            return;

        int? accountFilter = null;
        var text = AccountSearch.Text.Trim().TrimStart('#');
        if (int.TryParse(text, out var acc))
            accountFilter = acc;

        var rowIndex = 0;
        foreach (var record in _lastState.Records)
        {
            if (_selectedVendor.HasValue && record.SourceEntity != _selectedVendor)
                continue;
            if (accountFilter.HasValue && record.AccountNumber != accountFilter.Value)
                continue;

            LogRows.AddChild(BuildRow(record, rowIndex));
            rowIndex++;
        }

        if (rowIndex == 0)
        {
            LogRows.AddChild(new Label
            {
                Text = Loc.GetString("economy-monitor-no-records"),
                FontColorOverride = ColMuted,
                Margin = new Thickness(4, 8),
            });
        }
    }

    private Control BuildRow(EconomyTransactionRecord record, int index)
    {
        var bg = index % 2 == 0 ? ColRowEven : ColRowOdd;

        var amtStr   = record.Delta >= 0 ? $"+{record.Delta}" : record.Delta.ToString();
        var amtColor = record.Delta > 0 ? ColIncome : record.Delta < 0 ? ColExpense : ColNeutral;
        var locMark  = record.SourceEntity.HasValue ? "📍" : "";

        var hbox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
        hbox.AddChild(MakeCell(FormatTime(record.Timestamp),  80, ColMuted));
        hbox.AddChild(MakeCell($"#{record.AccountNumber}",    70, ColNeutral));
        hbox.AddChild(MakeCell(amtStr,                        80, amtColor));
        hbox.AddChild(MakeCell(record.Description,             0, Color.White, expand: true));
        hbox.AddChild(MakeCell(record.NewBalance.ToString(),  80, ColNeutral));
        hbox.AddChild(MakeCell(locMark,                       24, ColMuted));

        if (record.Location.HasValue)
        {
            var btn = new Button
            {
                HorizontalExpand = true,
                StyleBoxOverride = new StyleBoxFlat { BackgroundColor = bg },
            };
            btn.AddChild(hbox);

            var capturedRecord = record;
            btn.OnPressed += _ =>
            {
                var coords = _entManager.GetCoordinates(capturedRecord.Location!.Value);
                if (NavMap.MapUid.HasValue)
                    coords = _transform.WithEntityId(coords, NavMap.MapUid.Value);
                NavMap.CenterToCoordinates(coords);

                if (capturedRecord.SourceEntity.HasValue)
                {
                    _selectedVendor = capturedRecord.SourceEntity.Value;
                    NavMap.FocusVendor = _selectedVendor;
                    RefreshVendorList();
                }
            };
            return btn;
        }

        var panel = new PanelContainer { HorizontalExpand = true };
        panel.PanelOverride = new StyleBoxFlat { BackgroundColor = bg };
        panel.AddChild(hbox);
        return panel;
    }

    private void OnMapEntitySelected(NetEntity? entity)
    {
        _selectedVendor = entity;
        NavMap.FocusVendor = entity;
        RefreshVendorList();
        RefreshLog();
    }

    private static Label MakeCell(string text, int width, Color color, bool expand = false)
    {
        var lbl = new Label
        {
            Text = text,
            FontColorOverride = color,
            ClipText = true,
            HorizontalExpand = expand,
            Margin = new Thickness(4, 2),
        };
        if (width > 0)
            lbl.MinSize = new Vector2(width, 0);
        return lbl;
    }

    private static string FormatTime(TimeSpan ts)
        => $"{(int)ts.TotalHours:D2}:{ts.Minutes:D2}:{ts.Seconds:D2}";
}
