using System.Numerics;
using Content.Client.Pinpointer.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._IS14.Economy.EconomyMonitor;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._IS14.Economy.EconomyMonitor;

[GenerateTypedNameReferences]
public sealed partial class EconomyMonitorWindow : FancyWindow
{
    private static readonly Color ColIncome   = Color.FromHex("#66CC66");
    private static readonly Color ColExpense  = Color.FromHex("#CC6666");
    private static readonly Color ColNeutral  = Color.FromHex("#AAAAAA");
    private static readonly Color ColMuted    = Color.FromHex("#666666");
    private static readonly Color ColRowEven  = Color.FromHex("#0E1320");
    private static readonly Color ColRowOdd   = Color.FromHex("#141A28");
    private static readonly Color ColSelected = Color.FromHex("#1A3A2A");

    private readonly IEntityManager _entManager;
    private readonly IPrototypeManager _proto;
    private readonly SharedTransformSystem _transform;
    private readonly SpriteSystem _sprites;
    private readonly Texture _fallbackTexture;

    private EconomyMonitorUiState? _lastState;
    private NetEntity? _selectedVendor;
    private readonly HashSet<int> _selectedIds = new();
    private readonly HashSet<Guid> _expandedGroups = new();

    /// <summary>Raised with the selected record ids when the user presses the delete button.</summary>
    public event Action<List<int>>? OnDeleteRecords;

    /// <summary>Raised with the selected record ids when the user presses the print button.</summary>
    public event Action<List<int>>? OnPrintRecords;

    public EconomyMonitorWindow()
    {
        RobustXamlLoader.Load(this);

        _entManager = IoCManager.Resolve<IEntityManager>();
        _proto = IoCManager.Resolve<IPrototypeManager>();
        _transform = _entManager.System<SharedTransformSystem>();
        _sprites = _entManager.System<SpriteSystem>();
        _fallbackTexture = _sprites.Frame0(
            new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_square.png")));

        NavMap.TrackedEntitySelectedAction += OnMapEntitySelected;

        AccountSearch.OnTextChanged += _ => RefreshLog();

        ClearBtn.OnPressed += _ =>
        {
            AccountSearch.Clear();
            _selectedVendor = null;
            NavMap.FocusVendor = null;
            RefreshVendors();
            RefreshLog();
        };

        DeleteBtn.OnPressed += _ =>
        {
            if (_selectedIds.Count > 0)
                OnDeleteRecords?.Invoke(new List<int>(_selectedIds));
        };

        PrintBtn.OnPressed += _ =>
        {
            if (_selectedIds.Count > 0)
                OnPrintRecords?.Invoke(new List<int>(_selectedIds));
        };
    }

    public void UpdateState(EconomyMonitorUiState state)
    {
        _lastState = state;

        if (state.GridEntity.HasValue && _entManager.TryGetEntity(state.GridEntity.Value, out var gridUid))
            NavMap.MapUid = gridUid;
        else
            NavMap.Visible = false;

        RefreshVendors();
        RefreshLog();
    }

    // ── Vendor blips on the map ───────────────────────────────────────────────

    private void RefreshVendors()
    {
        NavMap.TrackedEntities.Clear();
        NavMap.LocalizedNames.Clear();

        if (_lastState == null)
            return;

        foreach (var vendor in _lastState.Vendors)
        {
            var coords = _entManager.GetCoordinates(vendor.Coordinates);
            var localCoords = NavMap.MapUid.HasValue
                ? _transform.WithEntityId(coords, NavMap.MapUid.Value)
                : coords;

            var isSelected = _selectedVendor == vendor.Entity;

            var blipTex = _fallbackTexture;
            if (vendor.PrototypeId != null
                && _proto.TryIndex<EntityPrototype>(vendor.PrototypeId, out var proto))
            {
                blipTex = _sprites.Frame0(proto);
            }

            NavMap.TrackedEntities[vendor.Entity] = new NavMapBlip(
                localCoords,
                blipTex,
                Color.White.WithAlpha(isSelected ? 1.0f : 0.7f),
                blinks: isSelected,
                selectable: true,
                scale: 1.5f);

            NavMap.LocalizedNames[vendor.Entity] = vendor.Name;
        }
    }

    // ── Log rows ──────────────────────────────────────────────────────────────

    private void RefreshLog()
    {
        LogRows.RemoveAllChildren();

        if (_lastState == null)
        {
            _selectedIds.Clear();
            UpdateActionButtons();
            return;
        }

        // Drop selections/expansions pointing at records that no longer exist.
        var presentIds = new HashSet<int>();
        var groups = new Dictionary<Guid, List<EconomyTransactionRecord>>();
        foreach (var record in _lastState.Records)
        {
            presentIds.Add(record.Id);
            if (record.GroupId is not { } groupId)
                continue;

            if (!groups.TryGetValue(groupId, out var members))
                groups[groupId] = members = new List<EconomyTransactionRecord>();
            members.Add(record);
        }
        _selectedIds.IntersectWith(presentIds);
        _expandedGroups.RemoveWhere(g => !groups.ContainsKey(g));

        int? accountFilter = null;
        var text = AccountSearch.Text.Trim().TrimStart('#');
        if (int.TryParse(text, out var acc))
            accountFilter = acc;

        var renderedGroups = new HashSet<Guid>();
        var rowIndex = 0;
        foreach (var record in _lastState.Records)
        {
            if (record.GroupId is { } groupId && groups[groupId].Count > 1)
            {
                if (!renderedGroups.Add(groupId))
                    continue;

                var members = groups[groupId];
                if (!AnyPassesFilters(members, accountFilter))
                    continue;

                var expanded = _expandedGroups.Contains(groupId);
                LogRows.AddChild(BuildGroupRow(members, groupId, expanded, rowIndex++));

                if (!expanded)
                    continue;

                foreach (var member in members)
                    LogRows.AddChild(BuildRow(member, rowIndex++, isChild: true));
            }
            else
            {
                if (!PassesFilters(record, accountFilter))
                    continue;

                LogRows.AddChild(BuildRow(record, rowIndex++, isChild: false));
            }
        }

        if (rowIndex == 0)
        {
            LogRows.AddChild(new Label
            {
                Text = Loc.GetString("economy-monitor-no-records"),
                FontColorOverride = ColMuted,
                Margin = new Thickness(4, 8),
            });
        }

        UpdateActionButtons();
    }

    private bool PassesFilters(EconomyTransactionRecord record, int? accountFilter)
    {
        if (_selectedVendor.HasValue && record.SourceEntity != _selectedVendor)
            return false;
        if (accountFilter.HasValue && record.AccountNumber != accountFilter.Value)
            return false;
        return true;
    }

    private bool AnyPassesFilters(List<EconomyTransactionRecord> records, int? accountFilter)
    {
        foreach (var record in records)
        {
            if (PassesFilters(record, accountFilter))
                return true;
        }
        return false;
    }

    /// <summary>
    /// Collapsed row for one purchase: shows the payer's transaction and expands
    /// into the individual money movements (payment, fund revenue, tax) on click.
    /// </summary>
    private Control BuildGroupRow(List<EconomyTransactionRecord> members, Guid groupId, bool expanded, int index)
    {
        // The payer's debit is the "face" of the purchase.
        var primary = members[0];
        foreach (var member in members)
        {
            if (member.Delta >= 0)
                continue;
            primary = member;
            break;
        }

        var bg = index % 2 == 0 ? ColRowEven : ColRowOdd;
        var marker = expanded ? "[-]" : $"[+{members.Count.ToString()}]";
        var amtStr = FormatDelta(primary.Delta);
        var amtColor = primary.Delta > 0 ? ColIncome : primary.Delta < 0 ? ColExpense : ColNeutral;

        var hbox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
        hbox.AddChild(MakeCell(FormatTime(primary.Timestamp), 80, ColMuted));
        hbox.AddChild(MakeCell($"#{primary.AccountNumber}",   70, ColNeutral));
        hbox.AddChild(MakeCell(amtStr,                        80, amtColor));
        hbox.AddChild(MakeCell($"{marker} {primary.Description}", 0, Color.White, expand: true));
        hbox.AddChild(MakeCell(primary.NewBalance.ToString(), 80, ColNeutral));

        var btn = new Button
        {
            HorizontalExpand = true,
            StyleBoxOverride = new StyleBoxFlat { BackgroundColor = bg },
        };
        btn.AddChild(hbox);
        btn.OnPressed += _ =>
        {
            if (!_expandedGroups.Remove(groupId))
                _expandedGroups.Add(groupId);
            RefreshLog();
        };

        var memberIds = new List<int>(members.Count);
        foreach (var member in members)
            memberIds.Add(member.Id);

        return WrapWithCheckbox(btn, memberIds, bg);
    }

    private Control BuildRow(EconomyTransactionRecord record, int index, bool isChild)
    {
        var bg = index % 2 == 0 ? ColRowEven : ColRowOdd;

        var amtStr   = FormatDelta(record.Delta);
        var amtColor = record.Delta > 0 ? ColIncome : record.Delta < 0 ? ColExpense : ColNeutral;
        var descColor = isChild ? ColNeutral : Color.White;
        var description = isChild ? $"    - {record.Description}" : record.Description;

        var hbox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
        hbox.AddChild(MakeCell(FormatTime(record.Timestamp),  80, ColMuted));
        hbox.AddChild(MakeCell($"#{record.AccountNumber}",    70, ColNeutral));
        hbox.AddChild(MakeCell(amtStr,                        80, amtColor));
        hbox.AddChild(MakeCell(description,                    0, descColor, expand: true));
        hbox.AddChild(MakeCell(record.NewBalance.ToString(),  80, ColNeutral));

        Control content;
        if (record.Location.HasValue)
        {
            var btn = new Button
            {
                HorizontalExpand = true,
                StyleBoxOverride = new StyleBoxFlat { BackgroundColor = bg },
            };
            btn.AddChild(hbox);

            var capturedRecord = record;
            btn.OnPressed += _ =>
            {
                var coords = _entManager.GetCoordinates(capturedRecord.Location!.Value);
                if (NavMap.MapUid.HasValue)
                    coords = _transform.WithEntityId(coords, NavMap.MapUid.Value);
                NavMap.CenterToCoordinates(coords);

                if (capturedRecord.SourceEntity.HasValue)
                {
                    _selectedVendor = capturedRecord.SourceEntity.Value;
                    NavMap.FocusVendor = _selectedVendor;
                    RefreshVendors();
                }
            };
            content = btn;
        }
        else
        {
            var panel = new PanelContainer { HorizontalExpand = true };
            panel.PanelOverride = new StyleBoxFlat { BackgroundColor = bg };
            panel.AddChild(hbox);
            content = panel;
        }

        // Sub-rows of an expanded purchase are selected via the group row's checkbox;
        // a spacer keeps their columns aligned with checkbox rows.
        if (!isChild)
            return WrapWithCheckbox(content, new List<int> { record.Id }, bg);

        var childRow = new PanelContainer { HorizontalExpand = true };
        childRow.PanelOverride = new StyleBoxFlat { BackgroundColor = bg };
        var childBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
        childBox.AddChild(new Control { MinSize = new Vector2(29, 0) });
        childBox.AddChild(content);
        childRow.AddChild(childBox);
        return childRow;
    }

    /// <summary>Puts a selection checkbox in front of a log row; toggling it (de)selects all given record ids.</summary>
    private Control WrapWithCheckbox(Control content, List<int> recordIds, Color bg)
    {
        var allSelected = true;
        foreach (var id in recordIds)
        {
            if (_selectedIds.Contains(id))
                continue;
            allSelected = false;
            break;
        }

        var checkBox = new CheckBox
        {
            Pressed = allSelected,
            Margin = new Thickness(6, 0, 2, 0),
            VerticalAlignment = VAlignment.Center,
        };
        checkBox.OnToggled += args =>
        {
            foreach (var id in recordIds)
            {
                if (args.Pressed)
                    _selectedIds.Add(id);
                else
                    _selectedIds.Remove(id);
            }
            UpdateActionButtons();
        };

        var row = new PanelContainer { HorizontalExpand = true };
        row.PanelOverride = new StyleBoxFlat { BackgroundColor = bg };

        var hbox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
        hbox.AddChild(checkBox);
        hbox.AddChild(content);
        row.AddChild(hbox);
        return row;
    }

    private void UpdateActionButtons()
    {
        DeleteBtn.Disabled = _selectedIds.Count == 0;
        PrintBtn.Disabled = _selectedIds.Count == 0;
    }

    private void OnMapEntitySelected(NetEntity? entity)
    {
        _selectedVendor = entity;
        NavMap.FocusVendor = entity;
        RefreshVendors();
        RefreshLog();
    }

    private static Label MakeCell(string text, int width, Color color, bool expand = false)
    {
        var lbl = new Label
        {
            Text = text,
            FontColorOverride = color,
            ClipText = true,
            HorizontalExpand = expand,
            Margin = new Thickness(4, 2),
        };
        if (width > 0)
            lbl.MinSize = new Vector2(width, 0);
        return lbl;
    }

    private static string FormatTime(TimeSpan ts)
        => $"{(int)ts.TotalHours:D2}:{ts.Minutes:D2}:{ts.Seconds:D2}";

    /// <summary>
    /// Zero-delta records are decisions that moved no money yet (e.g. a salary change),
    /// so they read better as a dash than as "+0".
    /// </summary>
    private static string FormatDelta(int delta)
        => delta switch
        {
            0 => "—",
            > 0 => $"+{delta}",
            _ => delta.ToString(),
        };
}
