using Content.Client.UserInterface.Controls;
using Content.Shared._IS14.Economy.EconomyMonitor;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Economy.EconomyMonitor;

/// <summary>
///     The standalone economy monitor: a window around <see cref="EconomyMonitorPanel"/>. The
///     layout lives in the panel so the OS application can show the same thing without a window
///     around it (Docs/_IS14/os-design.md §12.2).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class EconomyMonitorWindow : FancyWindow
{
    /// <summary>Raised with the selected record ids when the user presses the delete button.</summary>
    public event Action<List<int>>? OnDeleteRecords;

    /// <summary>Raised with the selected record ids when the user presses the print button.</summary>
    public event Action<List<int>>? OnPrintRecords;

    public EconomyMonitorWindow()
    {
        RobustXamlLoader.Load(this);

        Panel.OnDeleteRecords += ids => OnDeleteRecords?.Invoke(ids);
        Panel.OnPrintRecords += ids => OnPrintRecords?.Invoke(ids);
    }

    public void UpdateState(EconomyMonitorUiState state)
    {
        Panel.UpdateState(state);
    }
}
