// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._IS14.Economy.Gosplan;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Economy.Gosplan;

[GenerateTypedNameReferences]
public sealed partial class GosplanConsoleWindow : DefaultWindow
{
    /// <summary>Controls are reused between refreshes — the board updates every second.</summary>
    private readonly Dictionary<string, PlanDepartmentButton> _departments = new();

    private readonly Dictionary<string, PlanQuotaRow> _rows = new();

    private readonly List<PlanPeriodCard> _cards = new();

    /// <summary>Fund the reader is looking at. Survives refreshes, and the round if they leave and come back.</summary>
    private string _selectedFund = string.Empty;

    /// <summary>
    /// Last state the server sent. A click has to redraw against the current plan, not
    /// against whatever the buttons happened to be built from.
    /// </summary>
    private GosplanConsoleUiState? _state;

    public GosplanConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(PlanTab, Loc.GetString("is14-gosplan-tab-plan"));
        TabContainer.SetTabTitle(HistoryTab, Loc.GetString("is14-gosplan-tab-history"));
    }

    public void UpdateState(GosplanConsoleUiState state)
    {
        _state = state;

        TimerPanel.Update(state);

        Banner.Visible = state.Active;
        Tabs.Visible = state.Active;
        NoPlanLabel.Visible = !state.Active;

        if (!state.Active)
        {
            DepartmentList.RemoveAllChildren();
            QuotaList.RemoveAllChildren();
            HistoryList.RemoveAllChildren();
            _departments.Clear();
            _rows.Clear();
            _cards.Clear();
            return;
        }

        Banner.Update(state);
        UpdateLegend(state);
        UpdateDepartments(state);
        UpdateHistory(state);
    }

    /// <summary>
    /// The gauge thresholds are server-side cvars, so the legend reads them out of the
    /// state rather than repeating the defaults.
    /// </summary>
    private void UpdateLegend(GosplanConsoleUiState state)
    {
        LegendFailLabel.Text = Loc.GetString("is14-gosplan-mark-fail",
            ("percent", (int)MathF.Round(state.FailThreshold * 100f)));

        LegendTargetLabel.Text = Loc.GetString("is14-gosplan-mark-target",
            ("percent", (int)MathF.Round(state.OverThreshold * 100f)));

        LegendCapLabel.Text = Loc.GetString("is14-gosplan-mark-cap",
            ("percent", (int)MathF.Round(state.PayoutCap * 100f)));
    }

    private void UpdateDepartments(GosplanConsoleUiState state)
    {
        var departments = state.Departments;

        // Rebuild only when the set of departments actually changes; otherwise refresh in
        // place so the scroll position survives the once-a-second update.
        if (_departments.Count != departments.Count || departments.Any(d => !_departments.ContainsKey(d.FundId)))
        {
            DepartmentList.RemoveAllChildren();
            _departments.Clear();

            foreach (var department in departments)
            {
                var fund = department.FundId;
                var button = new PlanDepartmentButton();
                button.OnPressed += _ => Select(fund);

                _departments[fund] = button;
                DepartmentList.AddChild(button);
            }
        }

        // Whatever was open may have been dropped from the plan; fall back to the banner
        // holder, because that is the department the room is arguing about anyway.
        if (!_departments.ContainsKey(_selectedFund))
        {
            _selectedFund = departments.FirstOrDefault(d => d.HasBanner)?.FundId
                            ?? departments.FirstOrDefault()?.FundId
                            ?? string.Empty;
        }

        foreach (var department in departments)
        {
            if (_departments.TryGetValue(department.FundId, out var button))
                button.Update(department, state, department.FundId == _selectedFund);
        }

        UpdateQuotas(state);
    }

    /// <summary>Opens a department. Selecting is local — the server sends the whole plan either way.</summary>
    private void Select(string fundId)
    {
        if (_selectedFund == fundId || _state is not { } state)
            return;

        _selectedFund = fundId;

        foreach (var department in state.Departments)
        {
            if (_departments.TryGetValue(department.FundId, out var button))
                button.Update(department, state, department.FundId == _selectedFund);
        }

        UpdateQuotas(state);
    }

    private void UpdateQuotas(GosplanConsoleUiState state)
    {
        var selected = state.Departments.FirstOrDefault(d => d.FundId == _selectedFund);

        DepartmentPanel.Visible = selected != null;

        if (selected == null)
        {
            QuotaList.RemoveAllChildren();
            _rows.Clear();
            return;
        }

        DepartmentPanel.Update(selected, state);

        var quotas = selected.Quotas;

        // Same reuse rule as the department list, plus the rebuild that a change of
        // department forces: the rows belong to whichever fund is open.
        if (_rows.Count != quotas.Count || quotas.Any(q => !_rows.ContainsKey(q.QuotaId)))
        {
            QuotaList.RemoveAllChildren();
            _rows.Clear();

            foreach (var quota in quotas)
            {
                var row = new PlanQuotaRow();
                _rows[quota.QuotaId] = row;
                QuotaList.AddChild(row);
            }
        }

        var fundColor = GosplanPalette.Fund(selected.FundId);

        foreach (var quota in quotas)
        {
            if (_rows.TryGetValue(quota.QuotaId, out var row))
                row.Update(quota, state, fundColor);
        }
    }

    private void UpdateHistory(GosplanConsoleUiState state)
    {
        var history = state.History;

        HistoryEmptyLabel.Visible = history.Count == 0;

        // History only grows once a period, but the same reuse rule applies: a rebuild
        // every second would throw the player out of whatever they were reading.
        while (_cards.Count < history.Count)
        {
            var card = new PlanPeriodCard();
            _cards.Add(card);
            HistoryList.AddChild(card);
        }

        while (_cards.Count > history.Count)
        {
            var last = _cards[^1];
            _cards.RemoveAt(_cards.Count - 1);
            HistoryList.RemoveChild(last);
        }

        for (var i = 0; i < history.Count; i++)
        {
            // The list arrives newest first, so the first card is the period just closed.
            _cards[i].Update(history[i], state, i == 0);
        }
    }
}
