// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._IS14.Economy.Gosplan;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Economy.Gosplan;

[GenerateTypedNameReferences]
public sealed partial class GosplanConsoleWindow : DefaultWindow
{
    /// <summary>Rows are reused between refreshes — the board updates every second.</summary>
    private readonly Dictionary<string, PlanQuotaRow> _rows = new();

    private readonly List<PlanPeriodCard> _cards = new();

    public GosplanConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(PlanTab, Loc.GetString("is14-gosplan-tab-plan"));
        TabContainer.SetTabTitle(HistoryTab, Loc.GetString("is14-gosplan-tab-history"));
    }

    public void UpdateState(GosplanConsoleUiState state)
    {
        TimerPanel.Update(state);

        Banner.Visible = state.Active;
        Tabs.Visible = state.Active;
        NoPlanLabel.Visible = !state.Active;

        if (!state.Active)
        {
            QuotaList.RemoveAllChildren();
            HistoryList.RemoveAllChildren();
            _rows.Clear();
            _cards.Clear();
            return;
        }

        Banner.Update(state);
        UpdateLegend(state);
        UpdateQuotas(state);
        UpdateHistory(state);
    }

    /// <summary>
    /// The gauge thresholds are server-side cvars, so the legend reads them out of the
    /// state rather than repeating the defaults.
    /// </summary>
    private void UpdateLegend(GosplanConsoleUiState state)
    {
        LegendFailLabel.Text = Loc.GetString("is14-gosplan-mark-fail",
            ("percent", (int)MathF.Round(state.FailThreshold * 100f)));

        LegendTargetLabel.Text = Loc.GetString("is14-gosplan-mark-target",
            ("percent", (int)MathF.Round(state.OverThreshold * 100f)));

        LegendCapLabel.Text = Loc.GetString("is14-gosplan-mark-cap",
            ("percent", (int)MathF.Round(state.PayoutCap * 100f)));
    }

    private void UpdateQuotas(GosplanConsoleUiState state)
    {
        var quotas = state.Quotas;

        // Rebuild only when the set of quotas actually changes; otherwise refresh in place
        // so the scroll position survives the once-a-second update.
        if (_rows.Count != quotas.Count || quotas.Any(q => !_rows.ContainsKey(q.QuotaId)))
        {
            QuotaList.RemoveAllChildren();
            _rows.Clear();

            foreach (var quota in quotas)
            {
                var row = new PlanQuotaRow();
                _rows[quota.QuotaId] = row;
                QuotaList.AddChild(row);
            }
        }

        foreach (var quota in quotas)
        {
            if (_rows.TryGetValue(quota.QuotaId, out var row))
                row.Update(quota, state);
        }
    }

    private void UpdateHistory(GosplanConsoleUiState state)
    {
        var history = state.History;

        HistoryEmptyLabel.Visible = history.Count == 0;

        // History only grows once a period, but the same reuse rule applies: a rebuild
        // every second would throw the player out of whatever they were reading.
        while (_cards.Count < history.Count)
        {
            var card = new PlanPeriodCard();
            _cards.Add(card);
            HistoryList.AddChild(card);
        }

        while (_cards.Count > history.Count)
        {
            var last = _cards[^1];
            _cards.RemoveAt(_cards.Count - 1);
            HistoryList.RemoveChild(last);
        }

        for (var i = 0; i < history.Count; i++)
        {
            // The list arrives newest first, so the first card is the period just closed.
            _cards[i].Update(history[i], state, i == 0);
        }
    }
}
