// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._IS14.Economy.Gosplan;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Economy.Gosplan;

/// <summary>
/// One department in the board's left-hand list. Shows only enough to decide whether
/// this is the department worth opening: who they are, how they are doing overall, and
/// whether they are one period away from a sanction.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PlanDepartmentButton : ContainerButton
{
    private static readonly Color Idle = Color.FromHex("#161C2E");
    private static readonly Color Hover = Color.FromHex("#1C2438");
    private static readonly Color Selected = Color.FromHex("#232C46");

    /// <summary>Station account prototype ID this row stands for.</summary>
    public string FundId { get; private set; } = string.Empty;

    /// <summary>The stripe down the left is the department's colour, as everywhere else on the board.</summary>
    private readonly StyleBoxFlat _panel = new()
    {
        BackgroundColor = Idle,
        BorderThickness = new Thickness(3, 0, 0, 0),
    };

    private bool _selected;

    public PlanDepartmentButton()
    {
        RobustXamlLoader.Load(this);

        StyleBoxOverride = _panel;

        // The gauge is a summary here, not something to read numbers off, so it loses
        // the cell separators the full-size ones carry.
        Gauge.Segments = 0;
    }

    public void Update(PlanDepartmentEntry entry, GosplanConsoleUiState state, bool selected)
    {
        FundId = entry.FundId;
        _selected = selected;

        var fundColor = GosplanPalette.Fund(entry.FundId);
        var color = GosplanPalette.ForFulfillment(entry.Fulfillment, state.FailThreshold, state.OverThreshold);

        _panel.BackgroundColor = selected ? Selected : Idle;
        _panel.BorderColor = selected ? fundColor : fundColor.WithAlpha(0.5f);

        NameLabel.Text = entry.HasBanner
            ? Loc.GetString("is14-gosplan-department-banner-mark", ("fund", entry.FundName))
            : entry.FundName;

        NameLabel.FontColorOverride = selected ? fundColor : fundColor.WithAlpha(0.85f);

        PercentLabel.Text = Loc.GetString("is14-gosplan-percent",
            ("percent", (int)MathF.Round(entry.Fulfillment * 100f)));
        PercentLabel.FontColorOverride = color;

        Gauge.MaxValue = MathF.Max(state.PayoutCap, state.OverThreshold * 1.1f);
        Gauge.Target = state.OverThreshold;
        Gauge.Fail = state.FailThreshold;
        Gauge.Value = entry.Fulfillment;
        Gauge.FillColor = color;
        Gauge.Pulse = entry.FailStreak > 0 && entry.Fulfillment < state.FailThreshold;

        NoteLabel.Text = entry.FailStreak > 0
            ? Loc.GetString("is14-gosplan-department-streak", ("streak", entry.FailStreak))
            : Loc.GetString("is14-gosplan-department-metrics", ("count", entry.Quotas.Count));

        NoteLabel.FontColorOverride = entry.FailStreak > 0 ? GosplanPalette.Failing : GosplanPalette.TextDim;
    }

    protected override void MouseEntered()
    {
        base.MouseEntered();

        if (!_selected)
            _panel.BackgroundColor = Hover;
    }

    protected override void MouseExited()
    {
        base.MouseExited();

        if (!_selected)
            _panel.BackgroundColor = Idle;
    }
}
