// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._IS14.Economy.Gosplan;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Economy.Gosplan;

/// <summary>
/// The red banner gets a block of its own: it is the one thing on the board that is
/// won rather than measured, and it should be the first thing anyone walking past
/// the console sees.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RedBannerPanel : BoxContainer
{
    private static readonly Color HeldBackground = Color.FromHex("#5A1417");
    private static readonly Color HeldBorder = Color.FromHex("#C9A53B");
    private static readonly Color EmptyBackground = Color.FromHex("#241C22");
    private static readonly Color EmptyBorder = Color.FromHex("#3A3040");
    private static readonly Color HolderText = Color.FromHex("#FFD9D9");
    private static readonly Color DetailText = Color.FromHex("#E0A0A0");
    private static readonly Color EmptyHolder = Color.FromHex("#7A7288");
    private static readonly Color EmptyHint = Color.FromHex("#5E5870");
    private static readonly Color StarDim = Color.FromHex("#4C4458");

    private readonly StyleBoxFlat _panel = new()
    {
        BackgroundColor = HeldBackground,
        BorderColor = HeldBorder,
        BorderThickness = new Thickness(2),
    };

    public RedBannerPanel()
    {
        RobustXamlLoader.Load(this);
        BannerPanel.PanelOverride = _panel;
    }

    public void Update(GosplanConsoleUiState state)
    {
        var held = state.Active && state.BannerFundName.Length > 0;

        _panel.BackgroundColor = held ? HeldBackground : EmptyBackground;
        _panel.BorderColor = held ? HeldBorder : EmptyBorder;

        StarLabel.FontColorOverride = held ? GosplanPalette.Gold : StarDim;
        TitleLabel.FontColorOverride = held ? GosplanPalette.Gold : GosplanPalette.TextDim;

        if (!held)
        {
            HolderLabel.Text = GosplanPalette.Markup(EmptyHolder, Loc.GetString("is14-gosplan-banner-none"));
            DetailLabel.Text = GosplanPalette.Markup(EmptyHint, Loc.GetString("is14-gosplan-banner-none-hint"));
            return;
        }

        HolderLabel.Text = GosplanPalette.Markup(HolderText, state.BannerFundName);

        var detail = state.BannerPeriodIndex > 0
            ? Loc.GetString("is14-gosplan-banner-since", ("period", state.BannerPeriodIndex))
            : string.Empty;

        if (state.BannerBonus > 0)
        {
            var bonus = Loc.GetString("is14-gosplan-banner-bonus", ("amount", state.BannerBonus));
            detail = detail.Length > 0 ? $"{detail} · {bonus}" : bonus;
        }

        DetailLabel.Text = GosplanPalette.Markup(DetailText, detail);
    }
}
