using System.Linq;
using System.Numerics;
using Content.Client._IS14.Controls;
using Content.Client.GameTicking.Managers;
using Content.Client.UserInterface.Controls;
using Content.Shared._IS14.OS.Prototypes;
using Content.Shared._IS14.OS.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Shell;

/// <summary>
///     The device screen: desktop, app windows and taskbar. Everything visual is painted from
///     the theme prototype at runtime, so no engine stylesheet is touched (Docs §8.1).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class IS14OsShellWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private IPrototypeManager _proto = default!;
    private SpriteSystem _sprites = default!;
    private ClientGameTicker? _ticker;

    private readonly Dictionary<string, IS14OsAppWindow> _windows = new();

    private OsShellState? _shell;
    private IS14ThemePalette _palette = IS14ThemePalette.Default;
    private string? _lastThemeId;

    public event Action<string>? OnOpenApp;
    public event Action<string>? OnCloseApp;
    public event Action<string>? OnMinimizeApp;
    public event Action<string>? OnFocusApp;

    private IS14OsBui? _bui;

    public IS14OsShellWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StartButton.Caption = Loc.GetString("is14-os-start");
        StartMenuHeader.Text = Loc.GetString("is14-os-start-menu-header");
        BootLabel.Text = Loc.GetString("is14-os-booting");

        StartButton.OnPressed += _ => ToggleStartMenu();
    }

    public void Setup(IS14OsBui bui, IPrototypeManager proto)
    {
        _bui = bui;
        _proto = proto;
        _sprites = _sysMan.GetEntitySystem<SpriteSystem>();
        _ticker = _sysMan.GetEntitySystem<ClientGameTicker>();

        StartButton.Icon = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Logo);
        BootLogo.Texture = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Logo);
        ClockIcon.Texture = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Clock);
        AlertIcon.Texture = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Alert);
        BatteryIcon.Texture = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Battery);
        AddressIcon.Texture = IS14OsStyle.Resolve(_sprites, IS14OsStyle.Address);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateTray();
        UpdateBootProgress();
    }

    public void UpdateState(IS14OsUiState state)
    {
        // A state can still arrive after the BUI tore the window down — closing the lid disposes
        // this control and its children in the same tick a predicted state is being re-applied.
        // Touching the tree then throws, so stop at the door.
        if (Disposed)
            return;

        _shell = state.Shell;

        ApplyTheme(state.Shell.ThemeId);

        Title = state.Shell.DeviceName;

        var booting = state.Shell.Booting;
        BootScreen.Visible = booting;
        WindowLayer.Visible = !booting;
        ShortcutScroll.Visible = !booting && state.Windows.Count == 0;

        if (booting)
            StartMenuPanel.Visible = false;

        SyncWindows(state);
        RebuildTaskbar(state.Shell);
        RebuildShortcuts(state.Shell);

        if (StartMenuPanel.Visible)
            RebuildStartMenu(state.Shell);
    }

    #region Windows

    private void SyncWindows(IS14OsUiState state)
    {
        // Drop windows the server no longer reports as open.
        foreach (var (appId, window) in _windows.ToArray())
        {
            if (state.Windows.Any(w => w.App.Id == appId))
                continue;

            if (window.Parent != null)
                WindowLayer.RemoveChild(window);

            _windows.Remove(appId);
        }

        var fullscreen = state.Shell.ShellMode == OsShellMode.Fullscreen;

        foreach (var windowState in state.Windows)
        {
            var appId = windowState.App.Id;
            if (appId == null || !_proto.TryIndex<IS14OsAppPrototype>(appId, out var app))
                continue;

            if (!_windows.TryGetValue(appId, out var window))
            {
                var ui = IS14OsAppUiRegistry.Create(appId);
                if (ui == null)
                    continue;

                if (_bui != null)
                    ui.Setup(_bui);

                window = new IS14OsAppWindow();
                window.Initialize(appId, ui);
                window.Title = Loc.GetString(app.Name);
                window.Icon = ResolveAppIcon(app);
                window.OnCloseRequested += id => OnCloseApp?.Invoke(id);
                window.OnMinimizeRequested += id => OnMinimizeApp?.Invoke(id);
                window.OnFocusRequested += id => OnFocusApp?.Invoke(id);

                _windows[appId] = window;
                WindowLayer.AddChild(window);

                if (!fullscreen)
                {
                    LayoutContainer.SetPosition(window, NextCascadePosition());
                    window.SetSize = app.WindowSize;
                }
            }

            window.SetFullscreen(fullscreen);
            window.Visible = !windowState.Minimized;

            window.Ui.UpdateShell(state.Shell);

            if (windowState.AppState != null)
                window.Ui.UpdateState(windowState.AppState);

            window.ApplyTheme(_palette);
            window.Ui.ApplyTheme(_palette);
        }

        // Server list order is z-order: the last open app is on top.
        foreach (var windowState in state.Windows)
        {
            if (windowState.App.Id is { } id
                && _windows.TryGetValue(id, out var window)
                && window.Visible
                && window.Parent != null)
            {
                window.SetPositionLast();
            }
        }
    }

    private Vector2 NextCascadePosition()
    {
        var step = 18f * _windows.Count;
        return new Vector2(12f + step % 90f, 12f + step % 90f);
    }

    private Texture? ResolveAppIcon(IS14OsAppPrototype app)
    {
        return IS14OsStyle.Resolve(_sprites, app.Icon ?? IS14OsStyle.Fallback);
    }

    #endregion

    #region Desktop, taskbar and start menu

    private List<IS14OsAppPrototype> GetInstalled(OsShellState shell)
    {
        var apps = new List<IS14OsAppPrototype>();

        foreach (var appId in shell.Installed)
        {
            if (appId.Id is { } id && _proto.TryIndex<IS14OsAppPrototype>(id, out var app))
                apps.Add(app);
        }

        apps.Sort((a, b) => a.Order != b.Order
            ? a.Order.CompareTo(b.Order)
            : string.Compare(Loc.GetString(a.Name), Loc.GetString(b.Name), StringComparison.CurrentCulture));

        return apps;
    }

    /// <summary>
    ///     Icons on the desktop rather than an empty panel with an apology on it — this is the
    ///     first thing the player sees when the lid opens, so it should look like a device.
    /// </summary>
    private void RebuildShortcuts(OsShellState shell)
    {
        if (!ShortcutScroll.Visible)
            return;

        Shortcuts.RemoveAllChildren();

        foreach (var app in GetInstalled(shell))
        {
            var tile = new IconTile
            {
                Palette = _palette,
                Icon = ResolveAppIcon(app),
                Caption = Loc.GetString(app.Name),
                IconSize = 26,
                MinSize = new Vector2(108, 76),
                ToolTip = app.Description == null ? null : Loc.GetString(app.Description),
            };

            var id = app.ID;
            tile.OnPressed += _ => OnOpenApp?.Invoke(id);
            Shortcuts.AddChild(tile);
        }
    }

    private void RebuildTaskbar(OsShellState shell)
    {
        TaskButtons.RemoveAllChildren();

        foreach (var appId in shell.Open)
        {
            if (appId.Id is not { } id || !_proto.TryIndex<IS14OsAppPrototype>(id, out var app))
                continue;

            var minimized = shell.Minimized.Any(m => m.Id == id);

            var tile = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = ResolveAppIcon(app),
                Caption = Loc.GetString(app.Name),
                IconSize = 14,
                Selected = !minimized,
                MinWidth = 104,
                Margin = new Thickness(0, 0, 3, 0),
                ToolTip = Loc.GetString(app.Name),
            };

            tile.OnPressed += _ =>
            {
                if (minimized)
                    OnFocusApp?.Invoke(id);
                else
                    OnMinimizeApp?.Invoke(id);
            };

            TaskButtons.AddChild(tile);
        }
    }

    private void ToggleStartMenu()
    {
        StartMenuPanel.Visible = !StartMenuPanel.Visible;
        StartButton.Selected = StartMenuPanel.Visible;

        if (StartMenuPanel.Visible && _shell != null)
            RebuildStartMenu(_shell);
    }

    private void RebuildStartMenu(OsShellState shell)
    {
        StartMenu.RemoveAllChildren();

        foreach (var app in GetInstalled(shell))
        {
            var open = shell.Open.Any(a => a.Id == app.ID);

            var tile = new IconTile
            {
                Palette = _palette,
                Compact = true,
                Icon = ResolveAppIcon(app),
                Caption = Loc.GetString(app.Name),
                IconSize = 16,
                Badge = open,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2),
                ToolTip = app.Description == null ? null : Loc.GetString(app.Description),
            };

            var id = app.ID;
            tile.OnPressed += _ =>
            {
                StartMenuPanel.Visible = false;
                StartButton.Selected = false;
                OnOpenApp?.Invoke(id);
            };

            StartMenu.AddChild(tile);
        }
    }

    private void UpdateTray()
    {
        if (_shell == null)
            return;

        var time = _ticker != null
            ? _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan)
            : TimeSpan.Zero;

        TrayLabel.Text = $"{time:hh\\:mm\\:ss}";
        TrayLabel.FontColorOverride = _palette.Text;

        var hasAlert = !string.IsNullOrEmpty(_shell.AlertLevel);
        AlertIcon.Visible = hasAlert;
        AlertLabel.Visible = hasAlert;

        if (hasAlert)
        {
            AlertLabel.Text = _shell.AlertLevel!.ToUpperInvariant();
            AlertLabel.FontColorOverride = _shell.AlertColor;
            AlertIcon.ModulateSelfOverride = _shell.AlertColor;
        }

        AddressLabel.Text = _shell.Address ?? Loc.GetString("is14-os-status-no-address");
        AddressLabel.FontColorOverride = _palette.Muted;
        AddressIcon.ModulateSelfOverride = _palette.Muted;

        UpdateBattery(_shell.Battery);
    }

    /// <summary>
    ///     Charge readout. Colour does the warning, not a popup: the player should notice a red
    ///     number in the tray long before the device shuts in their hands.
    /// </summary>
    private void UpdateBattery(float? charge)
    {
        BatteryIcon.Visible = charge != null;
        BatteryLabel.Visible = charge != null;

        if (charge is not { } value)
            return;

        var percent = (int) MathF.Round(value * 100f);
        BatteryLabel.Text = $"{percent}%";

        var color = value switch
        {
            <= 0.1f => _palette.Bad,
            <= 0.25f => _palette.Warn,
            _ => _palette.Muted,
        };

        BatteryLabel.FontColorOverride = color;
        BatteryIcon.ModulateSelfOverride = color;
    }

    private void UpdateBootProgress()
    {
        if (_shell is not { Booting: true })
            return;

        var total = (_shell.BootEnd - _shell.BootStart).TotalSeconds;
        if (total <= 0)
            return;

        var done = (_timing.CurTime - _shell.BootStart).TotalSeconds;
        BootBar.Value = (float) Math.Clamp(done / total, 0d, 1d);
    }

    #endregion

    #region Theme

    private void ApplyTheme(string themeId)
    {
        if (themeId == _lastThemeId)
            return;

        if (!_proto.TryIndex<IS14OsThemePrototype>(themeId, out var theme))
            return;

        _lastThemeId = themeId;
        _palette = IS14OsStyle.ToPalette(theme);

        DesktopPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = theme.Background };
        StatusPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = theme.Panel,
            BorderColor = theme.Border,
            BorderThickness = new Thickness(0, 0, 0, 1),
        };
        BootScreen.PanelOverride = new StyleBoxFlat { BackgroundColor = theme.Background };
        TaskbarPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = theme.Panel,
            BorderColor = theme.Border,
            BorderThickness = new Thickness(0, 1, 0, 0),
        };
        StartMenuPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = theme.Panel,
            BorderColor = theme.Accent,
            BorderThickness = new Thickness(1),
        };

        StartButton.Palette = _palette;
        StartMenuHeader.FontColorOverride = theme.Accent;
        BootLabel.FontColorOverride = theme.Accent;
        BootLogo.ModulateSelfOverride = theme.Accent;
        ClockIcon.ModulateSelfOverride = theme.Accent;
    }

    #endregion
}
