using System.Numerics;
using Content.Client._IS14.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Utility;

namespace Content.Client._IS14.OS.Shell;

/// <summary>
///     One application window inside the desktop, built on the engine's BaseWindow — which
///     handles raising and resizing, while moving is done here (see <see cref="MouseMove"/>).
///     In fullscreen mode (handhelds) the same window simply fills the desktop and stops
///     dragging: one implementation, two shell modes.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class IS14OsAppWindow : BaseWindow
{
    private const int DragMargin = 6;

    /// <summary>Height of the title bar, which is also the strip the window drags by.</summary>
    private const int TitleBarHeight = 28;

    // XamlIL requires a public parameterless constructor on every XAML root type, so identity
    // is handed over by Initialize rather than through the constructor.
    public string AppId { get; private set; } = string.Empty;
    public IS14OsAppUi Ui { get; private set; } = default!;

    private bool _fullscreen;

    /// <summary>
    ///     Whether the shell already considers this the top window. Clicking the window it is
    ///     already on must not cost a message: every focus request rebuilds and re-sends the
    ///     whole shell state, and on a console with the economy monitor open that state is not
    ///     small.
    /// </summary>
    public bool Focused { get; set; }

    /// <summary>Whether this window is currently being moved by us rather than resized by base.</summary>
    private bool _moving;

    /// <summary>Where inside the window the player grabbed it, so it does not jump on the first move.</summary>
    private Vector2 _grabOffset;

    public event Action<string>? OnCloseRequested;
    public event Action<string>? OnMinimizeRequested;
    public event Action<string>? OnFocusRequested;

    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value;
    }

    public Texture? Icon
    {
        get => TitleIcon.Texture;
        set
        {
            TitleIcon.Texture = value;
            TitleIcon.Visible = value != null;
        }
    }

    public IS14OsAppWindow()
    {
        RobustXamlLoader.Load(this);

        // Control.MouseFilter defaults to Ignore, and BaseWindow does not set it: DefaultWindow
        // does it in its constructor, FancyWindow in its XAML. Without this the window never
        // sees a click at all, so it neither drags nor raises itself — the buttons inside it
        // still work, which is what made the windows look merely "stuck" rather than deaf.
        MouseFilter = MouseFilterMode.Stop;

        MinimizeButton.Glyph = GlyphButton.Mark.Bar;
        MinimizeButton.ToolTip = Loc.GetString("is14-os-window-minimize");
        MinimizeButton.OnPressed += _ => OnMinimizeRequested?.Invoke(AppId);

        CloseAppButton.Glyph = GlyphButton.Mark.Cross;
        CloseAppButton.Danger = true;
        CloseAppButton.ToolTip = Loc.GetString("is14-os-window-close");
        CloseAppButton.OnPressed += _ => OnCloseRequested?.Invoke(AppId);
    }

    public void Initialize(string appId, IS14OsAppUi ui)
    {
        AppId = appId;
        Ui = ui;

        ContentHost.AddChild(ui.Root);
    }

    /// <summary>
    ///     Fullscreen pins the window to the whole desktop and turns off dragging and resizing.
    ///     The minimise button stays: on a handheld it is how you get back to the task switcher.
    /// </summary>
    public void SetFullscreen(bool fullscreen)
    {
        if (_fullscreen == fullscreen)
            return;

        _fullscreen = fullscreen;
        Resizable = !fullscreen;

        if (fullscreen)
        {
            // Clear any explicit size (NaN is the "unset" value) and dock to the whole desktop.
            SetSize = new Vector2(float.NaN, float.NaN);
            LayoutContainer.SetAnchorAndMarginPreset(this, LayoutContainer.LayoutPreset.Wide);
        }
    }

    public void ApplyTheme(IS14ThemePalette palette)
    {
        Chrome.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.Panel,
            BorderColor = palette.Border,
            BorderThickness = new Thickness(_fullscreen ? 0 : 1),
        };

        TitleBarPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.PanelRaised,
            BorderColor = palette.Border,
            BorderThickness = new Thickness(0, 0, 0, 1),
        };

        ContentPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = palette.Panel };

        TitleLabel.FontColorOverride = palette.Accent;
        TitleIcon.ModulateSelfOverride = palette.Accent;

        MinimizeButton.Palette = palette;
        CloseAppButton.Palette = palette;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Function == EngineKeyFunctions.UIClick)
        {
            _moving = GetDragModeFor(args.RelativePosition) == DragMode.Move;

            // RelativePosition is measured from this window's top-left, which is exactly the
            // grip offset the move has to preserve.
            _grabOffset = args.RelativePosition;
        }

        // A handheld shows one window at a time, so there is nothing to raise; and a window
        // already on top has nothing to gain either.
        if (_fullscreen || Focused)
            return;

        OnFocusRequested?.Invoke(AppId);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Function == EngineKeyFunctions.UIClick)
            _moving = false;
    }

    /// <summary>
    ///     Moving the window, done here rather than left to BaseWindow, which gets it wrong for
    ///     a desktop that is not the whole screen. The engine clamps the <em>cursor</em> to the
    ///     parent's size and then subtracts the grip offset, so how far a window can be pushed
    ///     depends on where along the title bar it was grabbed — grab the right-hand end and it
    ///     stops early, grab the left-hand end and it sails past. It also compares a screen-space
    ///     cursor against a parent-space size, which only lines up when the parent sits at the
    ///     top-left of the screen; our desktop is nested inside the shell window and never does.
    ///
    ///     So: work in parent space, and clamp the <em>window</em>, not the cursor. Resizing and
    ///     the resize cursors are still the engine's, hence the fall-through.
    /// </summary>
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        if (!_moving || _fullscreen || Parent == null)
        {
            base.MouseMove(args);
            return;
        }

        var cursor = args.GlobalPosition - Parent.GlobalPosition;

        LayoutContainer.SetPosition(this, ClampToDesktop(cursor, _grabOffset, Size, Parent.Size));
    }

    /// <summary>
    ///     Where a dragged window lands: the cursor in desktop space, less where the window was
    ///     grabbed, kept wholly inside the desktop.
    ///
    ///     Static and on its own because the property that matters is a fact about this
    ///     arithmetic and nothing else — how far a window can be pushed must not depend on where
    ///     along its title bar it was picked up, which is exactly what clamping the cursor
    ///     instead of the window gets wrong.
    /// </summary>
    public static Vector2 ClampToDesktop(Vector2 cursorInDesktop, Vector2 grabOffset, Vector2 windowSize, Vector2 desktopSize)
    {
        // A window bigger than the desktop has nowhere to go; pin it rather than letting the
        // limit go negative and flip the clamp inside out.
        var limit = Vector2.Max(desktopSize - windowSize, Vector2.Zero);

        return Vector2.Clamp(cursorInDesktop - grabOffset, Vector2.Zero, limit);
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        if (_fullscreen)
            return DragMode.None;

        var mode = DragMode.None;

        if (Resizable)
        {
            if (relativeMousePos.Y < DragMargin)
                mode = DragMode.Top;
            else if (relativeMousePos.Y > Size.Y - DragMargin)
                mode = DragMode.Bottom;

            if (relativeMousePos.X < DragMargin)
                mode |= DragMode.Left;
            else if (relativeMousePos.X > Size.X - DragMargin)
                mode |= DragMode.Right;
        }

        if (mode == DragMode.None && relativeMousePos.Y < TitleBarHeight)
            mode = DragMode.Move;

        return mode;
    }
}
