- type: job
  id: DirectorMOKO
  name: job-name-DirectorMOKO
  description: job-description-DirectorMOKO
  playTimeTracker: JobDirectorMOKO
  setPreference: true #IS14TODO Set false
  startingGear: CentcomGear
  icon: "JobIconDirectorMOKO"
  supervisors: job-supervisors-centcom # Goobstation
  canBeAntag: false
  weight: 40
  requirements:
  - !type:AgeRequirement
    requiredAge: 21
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: Skills # CorvaxGoob-Skills
      skills:
      - ShuttleControl
      - Shooting
      - AdvancedBuilding
      - Surgery
      - MedicalEquipment
      - Butchering
