using Content.Shared._IS14.Economy.VendingMachine;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._IS14.Economy.VendingMachine;

[GenerateTypedNameReferences]
public sealed partial class IS14VendingItemButton : ContainerButton
{
    private static readonly Color ColorNormal      = Color.FromHex("#1C2236");
    private static readonly Color ColorHover       = Color.FromHex("#24304A");
    private static readonly Color ColorPressed     = Color.FromHex("#141828");
    private static readonly Color ColorDisabledBg  = Color.FromHex("#181C28");
    private static readonly Color ColorBorder      = Color.FromHex("#363E58");
    private static readonly Color ColorBorderHover = Color.FromHex("#5060A0");

    private static readonly Color ColorPriceGold = Color.FromHex("#A88A18");
    private static readonly Color ColorPricePoor = Color.FromHex("#993030");
    private static readonly Color ColorStock     = Color.FromHex("#787880");
    private static readonly Color ColorStockLow  = Color.FromHex("#A07828");
    private static readonly Color ColorStockNone = Color.FromHex("#993030");

    private bool _isDisabled;

    public IS14VendingItemButton()
    {
        RobustXamlLoader.Load(this);
    }

    public void Initialize(IS14VendingMachineUiEntry entry, int buyerBalance)
    {
        var outOfStock = entry.Stock <= 0;
        var canAfford  = buyerBalance >= entry.Price;
        _isDisabled = outOfStock || !canAfford;
        Disabled = _isDisabled;

        ToolTip = entry.ItemName;

        StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = _isDisabled ? ColorDisabledBg : ColorNormal,
            BorderColor = ColorBorder,
            BorderThickness = new Thickness(1),
        };

        PriceLabel.Text = Loc.GetString("is14-vending-price", ("price", entry.Price));
        PriceLabel.FontColorOverride = canAfford ? ColorPriceGold : ColorPricePoor;

        if (outOfStock)
        {
            StockLabel.Text = Loc.GetString("is14-vending-out-of-stock");
            StockLabel.FontColorOverride = ColorStockNone;
        }
        else
        {
            StockLabel.Text = Loc.GetString("is14-vending-stock", ("stock", entry.Stock));
            StockLabel.FontColorOverride = entry.Stock <= 2 ? ColorStockLow : ColorStock;
        }

        IconView.SetPrototype(entry.ItemId);

        NameLabel.Text = entry.ItemName;
        NameLabel.FontColorOverride = _isDisabled ? Color.FromHex("#888890") : Color.White;
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();

        if (StyleBoxOverride is not StyleBoxFlat flat)
            return;

        switch (DrawMode)
        {
            case DrawModeEnum.Hover:
                flat.BackgroundColor = ColorHover;
                flat.BorderColor     = ColorBorderHover;
                break;
            case DrawModeEnum.Pressed:
                flat.BackgroundColor = ColorPressed;
                flat.BorderColor     = ColorBorder;
                break;
            case DrawModeEnum.Disabled:
                flat.BackgroundColor = ColorDisabledBg;
                flat.BorderColor     = ColorBorder;
                break;
            default:
                flat.BackgroundColor = ColorNormal;
                flat.BorderColor     = ColorBorder;
                break;
        }
    }
}
