using Content.Shared._IS14.Economy.VendingMachine;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._IS14.Economy.VendingMachine;

[GenerateTypedNameReferences]
public sealed partial class IS14VendingMachineWindow : DefaultWindow
{
    private static readonly Color ColorTabActiveBg       = Color.FromHex("#1A6828");
    private static readonly Color ColorTabActiveText     = Color.FromHex("#003300");
    private static readonly Color ColorTabActiveBorder   = Color.FromHex("#2A9040");
    private static readonly Color ColorTabInactiveBg     = Color.FromHex("#222638");
    private static readonly Color ColorTabInactiveText   = Color.FromHex("#AAAAAA");
    private static readonly Color ColorTabLockedText     = Color.FromHex("#B06030");
    private static readonly Color ColorTabBorder         = Color.FromHex("#3A4060");
    private static readonly Color ColorContrabandActiveBg   = Color.FromHex("#6A1818");
    private static readonly Color ColorContrabandInactiveBg = Color.FromHex("#2E0E0E");

    private readonly List<(IS14VendingTabButton button, int tabIndex)> _tabButtons = new();
    private readonly IEntityManager _entManager;
    private int _activeTabIndex;
    private IS14VendingMachineUiState? _lastState;

    public event Action<int, int>? OnBuyPressed;

    public IS14VendingMachineWindow()
    {
        RobustXamlLoader.Load(this);

        _entManager = IoCManager.Resolve<IEntityManager>();

        SearchEdit.OnTextChanged += _ =>
        {
            if (_lastState != null)
                RefreshGrid(_lastState);
        };
    }

    public void UpdateState(IS14VendingMachineUiState state)
    {
        var isFirst = _lastState == null;
        _lastState = state;

        Title = state.MachineName;

        PlayerLabel.Text = string.IsNullOrEmpty(state.PlayerJob)
            ? state.PlayerName
            : $"{state.PlayerName} | {state.PlayerJob}";

        // Show the sprite of the actual ID card the balance is read from,
        // falling back to a generic card icon if it isn't available client-side.
        if (state.IdCard.HasValue && _entManager.TryGetEntity(state.IdCard.Value, out var cardUid))
        {
            IdCardIcon.SetEntity(cardUid);
            IdCardIcon.Visible = true;
            IdCardIconFallback.Visible = false;
        }
        else
        {
            IdCardIcon.SetEntity(null);
            IdCardIcon.Visible = false;
            IdCardIconFallback.Visible = true;
        }

        AdLabel.Text = state.AdMessage;
        BalanceLabel.Text = Loc.GetString("is14-vending-balance-value", ("balance", state.Balance));

        if (isFirst)
            _activeTabIndex = state.Tabs.Count > 0 ? 0 : -1;

        if (_activeTabIndex >= state.Tabs.Count && _activeTabIndex >= 0)
            _activeTabIndex = state.Tabs.Count > 0 ? 0 : -1;

        if (_activeTabIndex < 0 && !state.ContrabandUnlocked)
            _activeTabIndex = state.Tabs.Count > 0 ? 0 : -1;

        RebuildTabs(state);
        RefreshTabColors();
        RefreshGrid(state);
    }

    private void RebuildTabs(IS14VendingMachineUiState state)
    {
        TabRow.RemoveAllChildren();
        _tabButtons.Clear();

        for (var i = 0; i < state.Tabs.Count; i++)
        {
            var capturedIndex = i;
            var tab = state.Tabs[i];
            var btn = new IS14VendingTabButton
            {
                Text = tab.Name,
                Locked = !tab.HasAccess,
            };
            if (!tab.HasAccess)
                btn.ToolTip = Loc.GetString("is14-vending-no-access-tooltip");
            btn.OnPressed += _ => SwitchTab(capturedIndex);
            TabRow.AddChild(btn);
            _tabButtons.Add((btn, capturedIndex));
        }

        var contrabandBtn = new IS14VendingTabButton
        {
            Text = Loc.GetString("is14-vending-tab-contraband"),
            Visible = state.ContrabandUnlocked,
        };
        contrabandBtn.OnPressed += _ => SwitchTab(-1);
        TabRow.AddChild(contrabandBtn);
        _tabButtons.Add((contrabandBtn, -1));
    }

    private static StyleBoxFlat MakeTabStyleBox(Color bg, Color border)
        => new()
        {
            BackgroundColor = bg,
            BorderColor = border,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride   = 8,
            ContentMarginRightOverride  = 8,
            ContentMarginTopOverride    = 3,
            ContentMarginBottomOverride = 3,
        };

    private void RefreshGrid(IS14VendingMachineUiState state)
    {
        ItemGrid.RemoveAllChildren();

        List<IS14VendingMachineUiEntry> inventory;
        var hasAccess = true;
        if (_activeTabIndex < 0)
        {
            inventory = state.Contraband;
        }
        else if (_activeTabIndex < state.Tabs.Count)
        {
            var tab = state.Tabs[_activeTabIndex];
            inventory = tab.Inventory;
            hasAccess = tab.HasAccess;
        }
        else
        {
            return;
        }

        var filter = SearchEdit.Text.Trim();

        for (var i = 0; i < inventory.Count; i++)
        {
            var entry = inventory[i];
            if (filter.Length > 0 && !entry.ItemName.Contains(filter, StringComparison.OrdinalIgnoreCase))
                continue;

            var capturedTab  = _activeTabIndex;
            var capturedItem = i;
            var card = new IS14VendingItemButton();
            card.Initialize(entry, state.Balance, hasAccess);
            card.OnPressed += _ => OnBuyPressed?.Invoke(capturedTab, capturedItem);
            ItemGrid.AddChild(card);
        }
    }

    private void SwitchTab(int tabIndex)
    {
        _activeTabIndex = tabIndex;
        RefreshTabColors();
        if (_lastState != null)
            RefreshGrid(_lastState);
    }

    private void RefreshTabColors()
    {
        foreach (var (btn, idx) in _tabButtons)
        {
            var active = idx == _activeTabIndex;
            var locked = idx >= 0 && _lastState != null && idx < _lastState.Tabs.Count && !_lastState.Tabs[idx].HasAccess;
            Color bg, border, textColor;

            if (idx < 0)
            {
                bg        = active ? ColorContrabandActiveBg : ColorContrabandInactiveBg;
                border    = Color.FromHex("#661111");
                textColor = active ? Color.FromHex("#FFAAAA") : Color.FromHex("#AA6666");
            }
            else if (active)
            {
                bg        = ColorTabActiveBg;
                border    = ColorTabActiveBorder;
                textColor = ColorTabActiveText;
            }
            else
            {
                bg        = ColorTabInactiveBg;
                border    = ColorTabBorder;
                textColor = ColorTabInactiveText;
            }

            // Locked tabs are marked with an amber tint regardless of active state.
            if (locked)
                textColor = ColorTabLockedText;

            btn.StyleBoxOverride = MakeTabStyleBox(bg, border);
            btn.TextColor = textColor;
        }
    }
}

