// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._IS14.Medical.BloodType;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._IS14.Medical.BloodType;

/// <summary>
/// The paper strip, held up and read.
/// </summary>
/// <remarks>
/// Reads the card's component every frame instead of being handed a state. The reaction takes
/// long enough to walk away from, so the window has to show where it genuinely is — closing
/// and reopening a card must not restart the clock, and coming back to one somebody left on a
/// table has to show it already finished.
///
/// Deliberately not the analyser's window with a line hidden. The point of the strip is that
/// it is a piece of card: no instrument face, no verdict panel, nowhere for an answer to
/// appear. It prints wells, one blank for a name, and a manufacturer's footer.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class BloodStripWindow : DefaultWindow
{
    /// <summary>How long the pad takes to soak through once blood lands on it.</summary>
    private const float SoakSeconds = 0.9f;

    /// <summary>Colour the doctor's pen writes in.</summary>
    private static readonly Color Ink = Color.FromHex("#3E3627");

    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    /// <summary>Raised when the doctor has finished writing a name on the card.</summary>
    public event Action<string>? OnPatientChanged;

    private readonly List<BloodTestWell> _wells = new();

    private EntityUid _owner;
    private bool _built;
    private bool _builtUsed;

    public BloodStripWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // The editor sits on the printed line rather than in a box of its own: no background,
        // and the text tinted to ink so it reads as writing on the card instead of as a field
        // borrowed from a machine.
        PatientEdit.StyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Transparent };
        PatientEdit.ModulateSelfOverride = Ink;

        // Enter only. Losing focus must not commit, because committing is permanent and
        // clicking away mid-word is not a decision anybody made.
        PatientEdit.OnTextEntered += args => OnPatientChanged?.Invoke(args.Text);
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
        _built = false;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_entMan.TryGetComponent<BloodTestStripComponent>(_owner, out var strip))
            return;

        var strips = _entMan.System<BloodTestStripSystem>();

        // Wells only change when the card goes from blank to soaked, which happens once.
        if (!_built || _builtUsed != strip.Used)
            Build(strip);

        UpdatePatient(strip);
        UpdateWells(strip, strips.IsMismatched(strip));
    }

    /// <summary>
    /// Lays out the wells the card is printed with. Driven by what the card was made for
    /// rather than by what is on it, so a blank strip already shows its three empty circles.
    /// </summary>
    private void Build(BloodTestStripComponent strip)
    {
        var bloodType = _entMan.System<BloodTypeSystem>();
        var antigens = strip.Used && strip.Reagent == strip.Card
            ? strip.Antigens
            : new HashSet<Robust.Shared.Prototypes.ProtoId<BloodAntigenPrototype>>();

        WellsBox.RemoveAllChildren();
        _wells.Clear();

        foreach (var well in bloodType.BuildWells(new BloodSample(strip.Card, antigens, null)))
        {
            var control = new BloodTestWell();

            // No plus and minus printed underneath: clotted or not clotted is a thing you can
            // see, and spelling it out would be the card doing the reading for you.
            control.SetPalette(BloodTestPalette.Paper, spellItOut: false);
            control.SetWell(well);

            WellsBox.AddChild(control);
            _wells.Add(control);
        }

        _built = true;
        _builtUsed = strip.Used;
    }

    /// <summary>
    /// Swaps the blank between a printed line and something you can type on.
    /// </summary>
    /// <remarks>
    /// Writing is possible exactly once: with a pen, on a card nobody has signed yet. After
    /// that the name is part of the card, and the editor never comes back — which is the only
    /// thing that makes a signed strip worth trusting.
    /// </remarks>
    private void UpdatePatient(BloodTestStripComponent strip)
    {
        var signed = strip.Patient != string.Empty;
        var writing = strip.Writable && !signed;

        PatientEdit.Visible = writing;
        PatientLabel.Visible = !writing;

        if (writing)
        {
            PatientEdit.PlaceHolder = Loc.GetString("is14-blood-strip-patient-placeholder");
            return;
        }

        PatientLabel.Text = strip.Patient;
    }

    /// <summary>
    /// Moves the wells to where the reaction actually is, from the card's own clock.
    /// </summary>
    private void UpdateWells(BloodTestStripComponent strip, bool mismatched)
    {
        var hasWells = _wells.Count > 0 && !mismatched;

        WellsBox.Visible = hasWells;
        NoteLabel.Visible = !hasWells;

        if (!hasWells)
        {
            NoteLabel.Text = Loc.GetString(mismatched
                ? "is14-blood-strip-examine-nothing"
                : "is14-blood-strip-no-wells");

            return;
        }

        var soaked = 0f;
        var reacted = 0f;

        // Wetting and reacting run off the same clock but not off the same event: a card
        // ruined by the wrong liquid soaks exactly like a good one and then stops there.
        if (strip.Used || strip.Stain != null)
        {
            var elapsed = (float) (_timing.CurTime - strip.SoakedAt).TotalSeconds;

            soaked = Math.Clamp(elapsed / SoakSeconds, 0f, 1f);

            if (strip.Used)
            {
                var develop = MathF.Max((float) strip.DevelopDelay.TotalSeconds, SoakSeconds + 0.01f);
                reacted = Math.Clamp((elapsed - SoakSeconds) / (develop - SoakSeconds), 0f, 1f);
            }
        }

        foreach (var well in _wells)
        {
            well.SetStain(strip.Stain);
            well.SetProgress(soaked, reacted);
        }
    }
}
