// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._IS14.Medical.BloodType;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._IS14.Medical.BloodType;

/// <summary>
/// The marker: what somebody has decided to write on this bag.
/// </summary>
/// <remarks>
/// It offers every group the bag could plausibly hold and refuses to hint at which one is
/// right, because working that out is the job of the test. Writing the wrong one is entirely
/// possible and entirely the writer's fault, which is what makes a labelled shelf worth
/// something — somebody stood there and vouched for each of those bags.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class BloodLabelWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _protos = default!;

    /// <summary>Raised with the group to write, or null to wipe the label.</summary>
    public event Action<ProtoId<BloodTypePrototype>?>? OnWrite;

    public BloodLabelWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        EraseButton.OnPressed += _ => OnWrite?.Invoke(null);
    }

    public void UpdateState(BloodLabelUiState state)
    {
        OptionsGrid.RemoveAllChildren();

        foreach (var option in state.Options)
        {
            if (!_protos.TryIndex(option, out var proto))
                continue;

            var button = new Button
            {
                Text = Loc.GetString(proto.ShortName),
                MinWidth = 56,
                Margin = new Thickness(2),
            };

            if (proto.Color is { } color)
                button.Label.FontColorOverride = color;

            var chosen = option;
            button.OnPressed += _ => OnWrite?.Invoke(chosen);

            OptionsGrid.AddChild(button);
        }

        // Written out rather than shown as a pressed button: the buttons are an action, and
        // one of them being stuck down reads as a filter.
        CurrentLabel.Text = state.Current is { } current && _protos.TryIndex(current, out var currentProto)
            ? Loc.GetString("is14-blood-label-current", ("type", Loc.GetString(currentProto.ShortName)))
            : Loc.GetString("is14-blood-label-current-none");

        EraseButton.Disabled = state.Current == null;
    }
}
