// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._IS14.Medical.BloodType;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._IS14.Medical.BloodType;

/// <summary>
/// A blood typing card, run in front of the player rather than handed to them finished.
/// </summary>
/// <remarks>
/// The wells resolve one after another and the group is withheld until the last one settles.
/// It costs a couple of seconds of nothing happening, which is the point: the answer arrives
/// as a small event instead of as a line of text, and the doctor spends those seconds
/// knowing they are about to find out whether they guessed right.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class BloodTestWindow : DefaultWindow
{
    /// <summary>How long one well takes from the drop landing to the result settling.</summary>
    private const float WellSeconds = 1.1f;

    /// <summary>Delay between one well starting and the next.</summary>
    private const float StaggerSeconds = 0.4f;

    private static readonly Color Pending = Color.FromHex("#5A6478");
    private static readonly Color Failure = Color.FromHex("#9A6A2A");

    private readonly List<BloodTestWell> _wells = new();

    private BloodTestKitUiState? _state;
    private float _elapsed;
    private bool _settled;

    public BloodTestWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(BloodTestKitUiState state)
    {
        _state = state;
        _elapsed = 0f;
        _settled = false;

        WellsBox.RemoveAllChildren();
        _wells.Clear();

        SampleLabel.Text = Loc.GetString("is14-blood-test-sample", ("sample", state.Sample));

        foreach (var well in state.Wells)
        {
            var control = new BloodTestWell();
            control.SetPalette(BloodTestPalette.Screen);
            control.SetWell(well);

            WellsBox.AddChild(control);
            _wells.Add(control);
        }

        var hasWells = _wells.Count > 0;

        WellsBox.Visible = hasWells;
        EmptyLabel.Visible = !hasWells;
        EmptyLabel.Text = Loc.GetString(state.Outcome == BloodTestOutcome.NoBlood
            ? "is14-blood-test-no-blood"
            : "is14-blood-test-unreadable");

        ResultLabel.Text = "—";
        ResultLabel.FontColorOverride = Pending;
        ResultNameLabel.Text = Loc.GetString("is14-blood-test-working");

        // Nothing to run, or a card that finished developing while it sat in a pocket.
        if (!hasWells || !state.Animate)
            Settle();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_settled || _state == null)
            return;

        _elapsed += args.DeltaSeconds;

        for (var i = 0; i < _wells.Count; i++)
        {
            // The analyser runs its wells one after another: it is a machine working through
            // a rack, not a card somebody bled on all at once.
            var progress = Math.Clamp((_elapsed - i * StaggerSeconds) / WellSeconds, 0f, 1f);
            _wells[i].SetProgress(MathF.Min(progress / 0.3f, 1f), MathF.Max(progress - 0.3f, 0f) / 0.7f);
        }

        if (_elapsed >= (_wells.Count - 1) * StaggerSeconds + WellSeconds)
            Settle();
    }

    private void Settle()
    {
        _settled = true;

        if (_state == null)
            return;

        foreach (var well in _wells)
        {
            well.SetProgress(1f, 1f);
        }

        if (_state.Outcome != BloodTestOutcome.Typed || _state.ShortName == null || _state.Name == null)
        {
            ResultLabel.Text = Loc.GetString("is14-blood-test-result-unknown");
            ResultLabel.FontColorOverride = Failure;
            ResultNameLabel.Text = Loc.GetString(_state.Outcome == BloodTestOutcome.NoBlood
                ? "is14-blood-test-no-blood"
                : "is14-blood-test-unreadable");

            return;
        }

        ResultLabel.Text = Loc.GetString(_state.ShortName);
        ResultLabel.FontColorOverride = _state.Color;
        ResultNameLabel.Text = Loc.GetString(_state.Name);
    }
}
