// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics.RSI;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class StampWidget : PanelContainer
{
    private static readonly ProtoId<ShaderPrototype> PaperStamp = "PaperStamp";

    /// <summary>
    ///     Large icons are drawn half again as big as their source sprite, to match the
    ///     scale the original hand-drawn stamps were authored at.
    /// </summary>
    private const float IconScale = 1.5f;

    private ShaderInstance? _stampShader;

    /// Every frame of the large icon, or null when this stamp falls back to the bordered text label.
    private Texture[]? _iconFrames;

    /// Per-frame delays in seconds, or null when the icon is a still image.
    private float[]? _iconDelays;

    /// Length of one full loop of <see cref="_iconDelays"/>.
    private float _iconLoopLength;

    /// How far into the loop we currently are.
    private float _iconTime;

    private int _iconFrame;

    public float Orientation
    {
        get => StampedByLabel.Orientation;
        set => StampedByLabel.Orientation = value;
    }

    public StampDisplayInfo StampInfo
    {
        set
        {
            if (value.StampLargeIcon is { } icon)
                SetLargeIcon(icon);
            else
                SetTextStamp(value);
        }
    }

    public StampWidget()
    {
        RobustXamlLoader.Load(this);

        var resCache = IoCManager.Resolve<IResourceCache>();
        var borderImage = resCache.GetResource<TextureResource>(
                "/Textures/Interface/Paper/paper_stamp_border.svg.96dpi.png");

        var borderTexture = new StyleBoxTexture { Texture = borderImage };
        borderTexture.SetPatchMargin(StyleBoxTexture.Margin.All, 7.0f);
        PanelOverride = borderTexture;

        var prototypes = IoCManager.Resolve<IPrototypeManager>();
        _stampShader = prototypes.Index(PaperStamp).InstanceUnique();
    }

    /// <summary>
    ///     Draws the stamp as a sprite. Accepts both a bare texture and an RSI state; an
    ///     animated RSI state is played back on a loop for as long as the paper is open.
    /// </summary>
    private void SetLargeIcon(SpriteSpecifier icon)
    {
        var sprites = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();
        var state = sprites.RsiStateLike(icon);

        _iconFrames = new Texture[state.AnimationFrameCount];
        for (var i = 0; i < _iconFrames.Length; i++)
        {
            _iconFrames[i] = state.GetFrame(RsiDirection.South, i);
        }

        if (state.IsAnimated)
        {
            _iconDelays = new float[_iconFrames.Length];
            _iconLoopLength = 0.0f;
            for (var i = 0; i < _iconDelays.Length; i++)
            {
                _iconDelays[i] = state.GetDelay(i);
                _iconLoopLength += _iconDelays[i];
            }

            // A state with no delay at all would never advance, so don't bother animating it.
            if (_iconLoopLength <= 0.0f)
                _iconDelays = null;
        }

        // The icon is drawn by hand in Draw, so neither the paper border nor the label are wanted.
        PanelOverride = null;
        StampedByLabel.Visible = false;
        SetSize = new Vector2(_iconFrames[0].Width, _iconFrames[0].Height) * IconScale;
    }

    /// <summary>
    ///     Fallback for stamps without an icon: the stamper's name inside a generic border.
    /// </summary>
    private void SetTextStamp(StampDisplayInfo info)
    {
        StampedByLabel.Text = Loc.GetString(info.StampedName);
        StampedByLabel.FontColorOverride = info.StampedColor;
        ModulateSelfOverride = info.StampedColor;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_iconDelays == null)
            return;

        _iconTime = (_iconTime + args.DeltaSeconds) % _iconLoopLength;

        var remaining = _iconTime;
        var frame = 0;
        while (frame < _iconDelays.Length - 1 && remaining >= _iconDelays[frame])
        {
            remaining -= _iconDelays[frame];
            frame++;
        }

        _iconFrame = frame;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        _stampShader?.SetParameter("objCoord", GlobalPosition * UIScale * new Vector2(1, -1));
        handle.UseShader(_stampShader);
        handle.SetTransform(GlobalPosition * UIScale, Orientation, Vector2.One);

        base.Draw(handle);

        if (_iconFrames != null)
            handle.DrawTextureRect(_iconFrames[_iconFrame], PixelSizeBox);

        // Restore a sane transform+shader
        handle.SetTransform(Matrix3x2.Identity);
        handle.UseShader(null);
    }
}
