// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Shared.Atmos;
using Content.Client.UserInterface.Controls;
using Content.Shared.Damage;
using Content.Shared.Damage.Prototypes;
using Content.Goobstation.Maths.FixedPoint;
using Content.Goobstation.Shared.Disease;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Content.Client.Resources;
using Content.Shared.Alert;
using Content.Shared.Mobs.Systems;
using Robust.Client.ResourceManagement;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

// Shitmed Change
using Content.Shared._Shitmed.Targeting;
using Content.Shared._Shitmed.Medical.HealthAnalyzer;
using Content.Shared._Shitmed.Medical.Surgery.Wounds;
using Content.Shared._Shitmed.Medical.Surgery.Wounds.Systems;
using Content.Shared.Atmos.Rotting;
using Content.Shared.Body.Part;
using Content.Shared.Chemistry.Components;
using Content.Shared.Chemistry.Reagent;
using System.Globalization;
using Content.Goobstation.Shared.Disease.Components;

namespace Content.Client.HealthAnalyzer.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HealthAnalyzerWindow : FancyWindow
    {
        private readonly IEntityManager _entityManager;
        private readonly SpriteSystem _spriteSystem;
        private readonly IPrototypeManager _prototypes;
        private readonly Dictionary<AnimatedTextureRect, SpriteSpecifier> _is14Icons = new();
        private readonly IResourceCache _cache;

        // Shitmed Change Start
        private readonly WoundSystem _wound;
        public event Action<TargetBodyPart?, EntityUid>? OnBodyPartSelected;
        public event Action<HealthAnalyzerMode, EntityUid>? OnModeChanged;
        private EntityUid _spriteViewEntity;

        [ValidatePrototypeId<EntityPrototype>]
        private readonly EntProtoId _bodyView = "AlertSpriteView";

        private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartControls;

        //IS14-change start — какая часть тела сейчас выбрана, чтобы её было видно на модельке
        private TargetBodyPart? _is14ActivePart;

        private static readonly Color IS14PartSelected = Color.FromHex("#7ADCF5");

        // Статусная шкала для плиток показателей. Прогнана валидатором палитр: разделение
        // при дальтонизме ΔE 8.6, при обычном зрении 15.3, контраст к подложке выше 3:1.
        // Полосу светлоты она не проходит намеренно — это правило для категориальных палитр,
        // где ни одна серия не должна выделяться, а здесь «критично» обязано кричать громче.
        private static readonly Color IS14Good = Color.FromHex("#35A86A");
        private static readonly Color IS14Warn = Color.FromHex("#C2952F");
        private static readonly Color IS14Bad = Color.FromHex("#CF5C52");

        /// <summary>
        /// Подсветки конечностей на кукле.
        /// </summary>
        /// <remarks>
        /// В обычном состоянии у этих кнопок текстуры нет вовсе — стиль задаёт её только для
        /// псевдокласса hover. Поэтому одной лишь модуляцией выбранную конечность подсветить
        /// нельзя: красить нечего. Берём ту же самую текстуру наведения и вешаем её выбранной
        /// кнопке как постоянную, чтобы выбор выглядел ровно так же, как наведение.
        /// </remarks>
        private static readonly Dictionary<TargetBodyPart, string> IS14PartTextures = new()
        {
            { TargetBodyPart.Head, "head" },
            { TargetBodyPart.Chest, "torso" },
            { TargetBodyPart.Groin, "groin" },
            { TargetBodyPart.LeftArm, "leftarm" },
            { TargetBodyPart.LeftHand, "lefthand" },
            { TargetBodyPart.RightArm, "rightarm" },
            { TargetBodyPart.RightHand, "righthand" },
            { TargetBodyPart.LeftLeg, "leftleg" },
            { TargetBodyPart.LeftFoot, "leftfoot" },
            { TargetBodyPart.RightLeg, "rightleg" },
            { TargetBodyPart.RightFoot, "rightfoot" },
        };
        //IS14-change end
        private EntityUid? _target;
        private readonly MobThresholdSystem _thresholds;
        // Shitmed Change End

        public HealthAnalyzerWindow()
        {
            RobustXamlLoader.Load(this);

            var dependencies = IoCManager.Instance!;
            _entityManager = dependencies.Resolve<IEntityManager>();
            _spriteSystem = _entityManager.System<SpriteSystem>();
            _thresholds = _entityManager.System<MobThresholdSystem>();
            _prototypes = dependencies.Resolve<IPrototypeManager>();
            _cache = dependencies.Resolve<IResourceCache>();
            // Shitmed Change Start
            _wound = _entityManager.System<WoundSystem>();
            //IS14-change start — иконки берутся из RSI по состоянию, а не по пути к png.
            // Путь к png внутри .rsi — это весь лист кадров, поэтому анимированные наборы
            // (human_alive, temperature, human_critical) рисовались простынёй.
            //IS14-change end

            _bodyPartControls = new Dictionary<TargetBodyPart, TextureButton>
            {
                { TargetBodyPart.Head, HeadButton },
                { TargetBodyPart.Chest, ChestButton },
                { TargetBodyPart.Groin, GroinButton },
                { TargetBodyPart.LeftArm, LeftArmButton },
                { TargetBodyPart.LeftHand, LeftHandButton },
                { TargetBodyPart.RightArm, RightArmButton },
                { TargetBodyPart.RightHand, RightHandButton },
                { TargetBodyPart.LeftLeg, LeftLegButton },
                { TargetBodyPart.LeftFoot, LeftFootButton },
                { TargetBodyPart.RightLeg, RightLegButton },
                { TargetBodyPart.RightFoot, RightFootButton },
            };

            foreach (var bodyPartButton in _bodyPartControls)
            {
                bodyPartButton.Value.MouseFilter = MouseFilterMode.Stop;
                bodyPartButton.Value.OnPressed += _ => SetActiveBodyPart(bodyPartButton.Key, bodyPartButton.Value);
            }
            ReturnButton.OnPressed += _ => ResetBodyPart();
            BodyButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Body);
            OrgansButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Organs);
            ChemicalsButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Chemicals);
            // Shitmed Change End
        }

        // Shitmed Change Start
        public void SetActiveBodyPart(TargetBodyPart part, TextureButton button)
        {
            if (_target == null)
                return;

            //IS14-change start — раньше выбор был виден только по смене текста справа
            _is14ActivePart = part;
            IS14RefreshPartHighlight();
            //IS14-change end

            OnBodyPartSelected?.Invoke(part, _target.Value);
        }

        /// <summary>
        /// Tints the selected limb on the doll.
        /// </summary>
        /// <remarks>
        /// The doll was already the thing you clicked, but nothing on it changed afterwards, so
        /// the only way to tell which limb you were reading was to remember. Modulating the
        /// button is enough — they are drawn from the doll's own textures.
        /// </remarks>
        private void IS14RefreshPartHighlight()
        {
            var cache = IoCManager.Resolve<IResourceCache>();

            foreach (var (part, button) in _bodyPartControls)
            {
                if (_is14ActivePart == part && IS14PartTextures.TryGetValue(part, out var file))
                {
                    button.TextureNormal =
                        cache.GetTexture($"/Textures/_Shitmed/Interface/Targeting/Doll/{file}_hover.png");
                    button.ModulateSelfOverride = IS14PartSelected;
                }
                else
                {
                    button.TextureNormal = null;
                    button.ModulateSelfOverride = null;
                }
            }
        }

        /// <summary>
        /// Красит значения плиток по тому, насколько плохо дело.
        /// </summary>
        /// <remarks>
        /// Температура сравнивается с нормой тела, а не с нулём Цельсия: интересно отклонение,
        /// а не абсолютное значение.
        /// </remarks>
        private void IS14ColourVitals(HealthAnalyzerBaseMessage msg)
        {
            const float bodyNormal = 310f;

            TemperatureLabel.FontColorOverride = float.IsNaN(msg.Temperature)
                ? null
                : IS14Pick(MathF.Abs(msg.Temperature - bodyNormal), 3f, 10f);

            BloodLabel.FontColorOverride = float.IsNaN(msg.BloodLevel)
                ? null
                : IS14Pick(1f - msg.BloodLevel, 0.10f, 0.30f);

            StatusLabel.FontColorOverride =
                _entityManager.TryGetComponent<MobStateComponent>(_target!.Value, out var state)
                    ? state.CurrentState switch
                    {
                        MobState.Alive => IS14Good,
                        MobState.Critical => IS14Warn,
                        MobState.Dead => IS14Bad,
                        _ => null,
                    }
                    : null;

            DamageLabel.FontColorOverride =
                _entityManager.TryGetComponent<DamageableComponent>(_target.Value, out var damage)
                    ? IS14Pick(damage.TotalDamage.Float(), 1f, 50f)
                    : null;
        }

        /// <summary>Good below the first threshold, bad above the second.</summary>
        private static Color IS14Pick(float value, float warn, float bad)
        {
            return value >= bad ? IS14Bad : value >= warn ? IS14Warn : IS14Good;
        }
        //IS14-change end

        /// <summary>
        /// Ставит кадр из RSI, но только если он изменился.
        /// </summary>
        /// <remarks>
        /// <see cref="AnimatedTextureRect.SetFromSpriteSpecifier"/> сбрасывает анимацию в
        /// нулевой кадр. Сканер шлёт обновления раз в секунду, так что без этой проверки
        /// анимированные иконки дёргались бы обратно к началу и никогда не доигрывали.
        /// </remarks>
        private void IS14SetIcon(AnimatedTextureRect rect, SpriteSpecifier spec)
        {
            if (_is14Icons.TryGetValue(rect, out var current) && current.Equals(spec))
                return;

            _is14Icons[rect] = spec;
            rect.DisplayRect.Stretch = TextureRect.StretchMode.KeepAspectCentered;
            rect.SetFromSpriteSpecifier(spec);
        }

        private void IS14SetIcon(AnimatedTextureRect rect, string rsi, string state)
        {
            IS14SetIcon(rect, new SpriteSpecifier.Rsi(new ResPath(rsi), state));
        }

        /// <summary>Иконка ступени готового алерта, с зажимом в его же диапазон.</summary>
        private bool IS14TryAlertIcon(string alertId, float fraction, out SpriteSpecifier icon)
        {
            icon = default!;

            if (!_prototypes.TryIndex<AlertPrototype>(alertId, out var alert))
                return false;

            var severity = (short) Math.Clamp(
                MathF.Round(MathHelper.Lerp(alert.MinSeverity, alert.MaxSeverity, Math.Clamp(fraction, 0f, 1f))),
                alert.MinSeverity,
                alert.MaxSeverity);

            icon = alert.GetIcon(alert.SupportsSeverity ? severity : null);
            return true;
        }

        /// <summary>
        /// Все четыре иконки плиток — живые, каждая по своему показателю.
        /// </summary>
        /// <remarks>
        /// Везде, где в игре уже есть ступенчатый набор под эту величину, берётся он: холод и
        /// жар — из алертов <c>Cold</c>/<c>Hot</c>, кровь — из <c>Bleed</c>. Так шкала иконок
        /// совпадает с той, что игрок видит у себя, и её не приходится выдумывать заново.
        /// </remarks>
        private void IS14UpdateIcons(HealthAnalyzerBaseMessage msg, EntityUid target)
        {
            IS14UpdateStatusIcon(target);

            const float bodyNormal = 310f;

            if (!float.IsNaN(msg.Temperature))
            {
                var deviation = msg.Temperature - bodyNormal;

                // Ниже нормы — набор холода, выше — жара. Шкала до 25 градусов отклонения.
                if (IS14TryAlertIcon(deviation < 0f ? "Cold" : "Hot", MathF.Abs(deviation) / 25f, out var temp))
                    IS14SetIcon(IS14TempIcon, temp);
            }

            // Шкала перевёрнута относительно алерта кровотечения: там ступень растёт с потерей,
            // а здесь это указатель уровня — полная капля означает полную кровь.
            if (!float.IsNaN(msg.BloodLevel)
                && IS14TryAlertIcon("Bleed", msg.BloodLevel, out var blood))
            {
                IS14SetIcon(IS14BloodIcon, blood);
            }

            // Урон — отдельная графика мониторинга экипажа, а не та же кукла, что в состоянии:
            // две одинаковые иконки рядом читались бы как одно и то же показание.
            var step = 0;

            if (_entityManager.TryGetComponent<DamageableComponent>(target, out var damageable)
                && _thresholds.TryGetPercentageForState(target, MobState.Critical, damageable.TotalDamage, out var toCrit)
                && toCrit is { } value)
            {
                step = (int) Math.Clamp(MathF.Round(Math.Clamp(value.Float(), 0f, 1f) * 4f), 0f, 4f);
            }

            IS14SetIcon(IS14DamageIcon, "/Textures/Interface/Alerts/human_crew_monitoring.rsi", $"health{step}");
        }

        /// <summary>
        /// Ставит в плитку состояния ровно ту иконку, которую пациент видит у себя в алертах.
        /// </summary>
        /// <remarks>
        /// Прочитать чужой <c>AlertsComponent</c> нельзя — у него <c>SendOnlyToOwner</c>, и
        /// клиенту врача он не приходит. Зато нужные слагаемые сетевые, а считает их общая
        /// <c>MobThresholdSystem</c>, так что мы вызываем те же самые методы, что и сервер,
        /// и получаем ту же ступень — не копируя формулу, а переиспользуя её.
        /// </remarks>
        private void IS14UpdateStatusIcon(EntityUid target)
        {
            if (!_entityManager.TryGetComponent<MobStateComponent>(target, out var mobState)
                || !_entityManager.TryGetComponent<MobThresholdsComponent>(target, out var thresholds))
            {
                return;
            }

            // Через локальную: у StateAlertDict ограниченный доступ, читать поле можно, а
            // вызывать на нём методы анализатор Robust не разрешает.
            var alerts = thresholds.StateAlertDict;

            if (!alerts.TryGetValue(mobState.CurrentState, out var alertId)
                || !_prototypes.TryIndex<AlertPrototype>(alertId, out var alert))
            {
                return;
            }

            var severity = alert.MinSeverity;

            if (alert.SupportsSeverity
                && _entityManager.TryGetComponent<DamageableComponent>(target, out var damageable)
                && _thresholds.TryGetNextState(target, mobState.CurrentState, out var next, thresholds)
                && _thresholds.TryGetPercentageForState(target, next.Value, damageable.TotalDamage, out var percent)
                && percent is { } value)
            {
                severity = (short) MathF.Round(MathHelper.Lerp(
                    alert.MinSeverity,
                    alert.MaxSeverity,
                    FixedPoint2.Clamp(value, 0, 1).Float()));
            }

            IS14SetIcon(IS14StatusIcon, alert.GetIcon(severity));
        }
        //IS14-change end

        public void SetMode(HealthAnalyzerMode mode)
        {
            if (_target == null)
                return;

            OnModeChanged?.Invoke(mode, _target.Value);
        }

        public void ResetBodyPart()
        {
            if (_target == null)
                return;

            //IS14-change start
            _is14ActivePart = null;
            IS14RefreshPartHighlight();
            //IS14-change end

            OnBodyPartSelected?.Invoke(null, _target.Value);
        }

        public void SetActiveButtons(bool isHumanoid)
        {
            foreach (var button in _bodyPartControls)
                button.Value.Visible = isHumanoid;
        }

        public bool TrySetupEntity(HealthAnalyzerBaseMessage msg)
        {
            if (_target is null)
            {
                NoPatientDataText.Visible = true;
                return false;
            }

            SetActiveButtons(_entityManager.HasComponent<TargetingComponent>(_target.Value));

            NoPatientDataText.Visible = false;

            //IS14-change start — блок кровообращения обновляется сам по кадрам, ему нужен только пациент
            IS14Circulation.SetTarget(_target);
            IS14Diagnoses.SetTarget(_target);
            IS14Organs.SetTarget(_target);
            //IS14-change end

            // Scan Mode

            //IS14-change start — значения плиток красятся по состоянию. Подпись у каждой плитки
            // остаётся нейтральной, поэтому цвет нигде не является единственным сигналом.
            IS14ColourVitals(msg);
            IS14UpdateIcons(msg, _target.Value);

            // статус живёт в заголовке окна, а не строкой в теле
            var is14Active = msg.ScanMode is true;

            Title = Loc.GetString(
                "is14-analyzer-title",
                ("state", Loc.GetString(msg.ScanMode.HasValue
                    ? is14Active
                        ? "health-analyzer-window-scan-mode-active"
                        : "health-analyzer-window-scan-mode-inactive"
                    : "health-analyzer-window-entity-unknown-text")));

            WindowTitle.FontColorOverride = msg.ScanMode.HasValue
                ? is14Active ? Color.FromHex("#3ABB6A") : Color.FromHex("#C4564E")
                : null;

            // Только сама надпись: её сосед по контейнеру — блок с именем пациента.
            ScanModeLabel.Visible = false;
            //IS14-change end

            // Patient Information

            SpriteView.SetEntity(_entityManager.HasComponent<HumanoidAppearanceComponent>(_target.Value)
                ? SetupIcon(msg.Body, msg.Bleeding)
                : _target.Value);
            SpriteView.Visible = msg.ScanMode.HasValue && msg.ScanMode.Value;
            PartView.Visible = SpriteView.Visible;
            NoDataTex.Visible = !SpriteView.Visible;

            var name = new FormattedMessage();
            name.PushColor(Color.White);
            name.AddText(_entityManager.HasComponent<MetaDataComponent>(_target.Value)
                ? Identity.Name(_target.Value, _entityManager)
                : Loc.GetString("health-analyzer-window-entity-unknown-text"));
            NameLabel.SetMessage(name);

            SpeciesLabel.Text =
                _entityManager.TryGetComponent<HumanoidAppearanceComponent>(_target.Value,
                    out var humanoidAppearanceComponent)
                    ? Loc.GetString(_prototypes.Index<SpeciesPrototype>(humanoidAppearanceComponent.Species).Name)
                    : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

            // Basic Diagnostic

            //IS14-change start — только цельсии: кельвины врачу ни о чём не говорят и вдвое
            // растягивали плитку
            TemperatureLabel.Text = !float.IsNaN(msg.Temperature)
                ? $"{msg.Temperature - Atmospherics.T0C:F1} °C"
                : Loc.GetString("health-analyzer-window-entity-unknown-value-text");
            //IS14-change end

            BloodLabel.Text = !float.IsNaN(msg.BloodLevel)
                ? $"{msg.BloodLevel * 100:F1} %"
                : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

            StatusLabel.Text =
                _entityManager.TryGetComponent<MobStateComponent>(_target.Value, out var mobStateComponent)
                    ? GetStatus(mobStateComponent.CurrentState)
                    : Loc.GetString("health-analyzer-window-entity-unknown-text");

            return true;
        }

        // All of this shit got fucked with, we're cooked hometh :wilted_rose: shitmod when
        public void Populate(HealthAnalyzerBodyMessage msg)
        {
            _target = _entityManager.GetEntity(msg.TargetEntity);
            EntityUid? part = msg.SelectedPart != null ? _entityManager.GetEntity(msg.SelectedPart.Value) : null;
            var isPart = part != null;

            if (!TrySetupEntity(msg)
                || _target is null
                || !_entityManager.TryGetComponent<DamageableComponent>(isPart ? part : _target, out var damageable))
                return;

            ReturnButton.Visible = isPart;
            PartNameLabel.Visible = isPart;
            DamageLabelHeading.Visible = true;
            DamageLabel.Visible = true;
            DamageLabel.Text = damageable.TotalDamage.ToString();

            // Alerts

            var showAlerts = msg.Unrevivable == true || msg.Bleeding.Values.Any(v => v); // Goobstation?


            AlertsDivider.Visible = showAlerts;
            AlertsContainer.Visible = showAlerts;

            if (showAlerts)
                AlertsContainer.RemoveAllChildren();
            // Goobstation start
            DamageLabelHeadingVital.Visible = true;
            DamageLabelVital.Visible = true;
            DamageLabelVital.Text = msg.VitalDamage.ToString();
            // Goobstation end

            if (part != null)
                PartNameLabel.Text = _entityManager.HasComponent<MetaDataComponent>(part)
                    ? Identity.Name(part.Value, _entityManager)
                    : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

            var damageSortedGroups =
                damageable.DamagePerGroup.OrderByDescending(damage => damage.Value)
                    .ToDictionary(x => x.Key, x => x.Value);

            IReadOnlyDictionary<string, FixedPoint2> damagePerType = damageable.Damage.DamageDict;

            DrawDiagnosticGroups(damageSortedGroups, damagePerType);

            // Goobstation
            if (_entityManager.TryGetComponent<DiseaseCarrierComponent>(_target, out var carrier))
            {
                DrawDiseases(carrier.Diseases.ContainedEntities);
            }

            ConditionsListContainer.RemoveAllChildren();

            // Goob start - low blood alert
            if (msg.BloodLevelLow)
                ConditionsListContainer.AddChild(new RichTextLabel
                {
                    Text = Loc.GetString("condition-body-low-blood", ("entity", Identity.Name(_target.Value, _entityManager))),
                    Margin = new Thickness(0, 4),
                });
            // Goob end

            if (msg.Unrevivable == true)
                ConditionsListContainer.AddChild(new RichTextLabel
                {
                    Text = Loc.GetString("condition-body-unrevivable", ("entity", Identity.Name(_target.Value, _entityManager))),
                    Margin = new Thickness(0, 4),
                });

            foreach (var (bodyPart, isBleeding) in msg.Bleeding)
            {
                if (!isBleeding)
                    continue;

                var locString = Loc.GetString($"condition-body-bleeding-{bodyPart.ToString()}", ("entity", Identity.Name(_target.Value, _entityManager)));

                ConditionsListContainer.AddChild(new RichTextLabel
                {
                    Text = locString,
                    Margin = new Thickness(0, 4),
                });
            }

            foreach (var (woundableTrauma, traumas) in msg.Traumas)
            {
                if (!TryGetEntityName(woundableTrauma, out var woundableName)
                    || isPart
                    && woundableTrauma != msg.SelectedPart)
                    continue;

                foreach (var trauma in traumas)
                {
                    // TODO: Once these string conditionals are better defined, rewrite to use a switch case based on trauma types.
                    string locString;
                    if (trauma.TargetType.HasValue)
                        locString = Loc.GetString($"condition-body-trauma-{trauma.TraumaType}",
                            ("targetSymmetry", trauma.TargetType.Value.Item2 != BodyPartSymmetry.None
                                ? $"{trauma.TargetType.Value.Item2.ToString().ToLower()} " // This is so fucking ugly.
                                : ""),
                            ("targetType", trauma.TargetType.Value.Item1.ToString().ToLower()));
                    else
                        locString = trauma.SeverityString != null
                            ? Loc.GetString($"condition-body-trauma-{trauma.TraumaType}-{trauma.SeverityString}", ("woundable", woundableName))
                            : Loc.GetString($"condition-body-trauma-{trauma.TraumaType}", ("woundable", woundableName));

                    ConditionsListContainer.AddChild(new RichTextLabel
                    {
                        Text = locString,
                        Margin = new Thickness(0, 4),
                    });
                }
            }

            /*foreach (var (woundablePain, pain) in msg.NervePainFeels)
            {
                if (pain == 1.0
                    || !TryGetEntityName(woundablePain, out var woundableName)
                    || isPart
                    && woundablePain != msg.SelectedPart)
                    continue;

                var painString = pain > 1.0 ? "increased" : "decreased";
                var locString = Loc.GetString($"condition-body-pain-{painString}", ("woundable", woundableName));

                ConditionsListContainer.AddChild(new RichTextLabel
                {
                    Text = locString,
                    Margin = new Thickness(0, 4),
                });
            }*/

            //IS14-change: список патологий общий с нашими диагнозами, поэтому «не обнаружено»
            // пишется только когда пусто и там, и там
            if (ConditionsListContainer.ChildCount == 0 && !IS14Diagnoses.HasEntries)
            {
                ConditionsListContainer.AddChild(new RichTextLabel
                {
                    Text = Loc.GetString("is14-analyzer-pathologies-none"),
                    Margin = new Thickness(0, 4),
                });
            }
        }
        public void Populate(HealthAnalyzerOrgansMessage msg)
        {
            _target = _entityManager.GetEntity(msg.TargetEntity);

            if (!TrySetupEntity(msg))
                return;

            ReturnButton.Visible = false;
            PartNameLabel.Visible = false;
            DamageLabelHeading.Visible = false;
            DamageLabel.Visible = false;

            ConditionsListContainer.RemoveAllChildren();
            GroupsContainer.RemoveAllChildren();

            //IS14-change start — вкладка органов целиком заменена: кукла в центре, органы вокруг.
            // Кровообращение и общие показатели тут не дублируются, они на вкладке тела.
            foreach (var (organ, data) in msg.Organs)
            {
                var organEnt = _entityManager.GetEntity(organ);

                if (!TryGetEntityName(organEnt, out var organName)
                    || data.IntegrityCap == 0) // avoid division by zero
                    continue;

                DrawOrganDiagnostics(organEnt, organName, data.Integrity / data.IntegrityCap * 100);

                if (_entityManager.HasComponent<RottingComponent>(organEnt))
                {
                    ConditionsListContainer.AddChild(new RichTextLabel
                    {
                        Text = Loc.GetString("condition-organ-rotting", ("organ", organName)),
                        Margin = new Thickness(0, 4),
                    });
                }

                ConditionsListContainer.AddChild(new RichTextLabel
                {
                    Text = Loc.GetString($"condition-organ-damage-{data.Severity.ToString()}", ("organ", organName)),
                    Margin = new Thickness(0, 4),
                });
            }

            //IS14-change: список патологий общий с нашими диагнозами, поэтому «не обнаружено»
            // пишется только когда пусто и там, и там
            if (ConditionsListContainer.ChildCount == 0 && !IS14Diagnoses.HasEntries)
            {
                ConditionsListContainer.AddChild(new RichTextLabel
                {
                    Text = Loc.GetString("is14-analyzer-pathologies-none"),
                    Margin = new Thickness(0, 4),
                });
            }
        }

        public void Populate(HealthAnalyzerChemicalsMessage msg)
        {
            _target = _entityManager.GetEntity(msg.TargetEntity);

            if (!TrySetupEntity(msg))
                return;

            ReturnButton.Visible = false;
            PartNameLabel.Visible = false;
            DamageLabelHeading.Visible = false;
            DamageLabel.Visible = false;

            ConditionsListContainer.RemoveAllChildren();
            GroupsContainer.RemoveAllChildren();

            DrawSolutionDiagnostics(msg.Solutions);

            //IS14-change: то же самое
            if (!IS14Diagnoses.HasEntries)
            {
                ConditionsListContainer.AddChild(new RichTextLabel
                {
                    Text = Loc.GetString("is14-analyzer-pathologies-none"),
                    Margin = new Thickness(0, 4),
                });
            }
        }

        private bool TryGetEntityName(NetEntity ent, out string name)
        {
            name = Loc.GetString("health-analyzer-window-entity-unknown-value-text");
            var targetedEnt = _entityManager.GetEntity(ent);

            if (!_entityManager.HasComponent<MetaDataComponent>(targetedEnt))
                return false;

            name = Identity.Name(targetedEnt, _entityManager);
            return true;
        }

        private bool TryGetEntityName(EntityUid ent, out string name)
        {
            name = Loc.GetString("health-analyzer-window-entity-unknown-value-text");

            if (!_entityManager.HasComponent<MetaDataComponent>(ent))
                return false;

            name = Identity.Name(ent, _entityManager);
            return true;
        }
        // Shitmed Change End
        private static string GetStatus(MobState mobState)
        {
            return mobState switch
            {
                MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
                MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
                MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
                _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
            };
        }

        private void DrawDiagnosticGroups(
            Dictionary<string, FixedPoint2> groups,
            IReadOnlyDictionary<string, FixedPoint2> damageDict)
        {
            GroupsContainer.RemoveAllChildren();

            foreach (var (damageGroupId, damageAmount) in groups)
            {
                if (damageAmount == 0)
                    continue;

                var groupTitleText = $"{Loc.GetString(
                    "health-analyzer-window-damage-group-text",
                    ("damageGroup", _prototypes.Index<DamageGroupPrototype>(damageGroupId).LocalizedName),
                    ("amount", damageAmount)
                )}";

                var groupContainer = new BoxContainer
                {
                    Align = BoxContainer.AlignMode.Begin,
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                };

                groupContainer.AddChild(CreateDiagnosticGroupTitle(groupTitleText, damageGroupId));

                GroupsContainer.AddChild(groupContainer);

                // Show the damage for each type in that group.
                var group = _prototypes.Index<DamageGroupPrototype>(damageGroupId);

                foreach (var type in group.DamageTypes)
                {
                    if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                        continue;

                    var damageString = Loc.GetString(
                        "health-analyzer-window-damage-type-text",
                        ("damageType", _prototypes.Index<DamageTypePrototype>(type).LocalizedName),
                        ("amount", typeAmount)
                    );

                    groupContainer.AddChild(CreateDiagnosticItemLabel(damageString.Insert(0, " · ")));
                }
            }
        }

        private void DrawOrganDiagnostics(EntityUid ent, string name, FixedPoint2 damage)
        {
            //TextInfo textInfo = new CultureInfo("en-US", false).TextInfo; // CorvaxGoob-Localization
            var groupTitleText = $"{Loc.GetString(
                "group-organ-status",
                ("organ", name), // CorvaxGoob-Localization // textInfo.ToTitleCase(name) -> name
                ("capacity", damage)
            )}";

            var groupContainer = new BoxContainer
            {
                Align = BoxContainer.AlignMode.Begin,
                Orientation = BoxContainer.LayoutOrientation.Vertical,
            };

            groupContainer.AddChild(CreateDiagnosticGroupTitle(groupTitleText, ent));

            GroupsContainer.AddChild(groupContainer);
        }

        private void DrawSolutionDiagnostics(Dictionary<NetEntity, Solution> solutions)
        {
            TextInfo textInfo = new CultureInfo("en-US", false).TextInfo;
            foreach (var (ent, data) in solutions)
            {
                 // CorvaxGoob-Localization-start
                var groupTitleText = "";

                if (data.Name != null)
                    groupTitleText = Loc.GetString(
                    "group-solution-name",
                    ("solution", Loc.GetString("solution-type-" + data.Name))
                    );
                else
                    Loc.GetString("group-solution-unknown");
                 // CorvaxGoob-Localization-end

                var groupContainer = new BoxContainer
                {
                    Align = BoxContainer.AlignMode.Begin,
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                };

                groupContainer.AddChild(CreateDiagnosticGroupTitle(groupTitleText, "metaphysical")); // CorvaxGoob-Localization // textInfo.ToTitleCase(groupTitleText) -> groupTitleText

                GroupsContainer.AddChild(groupContainer);

                foreach (var reagent in data.Contents)
                {
                    if (reagent.Quantity == 0)
                        continue;

                    var reagentName = Loc.GetString("chem-master-window-unknown-reagent-text");
                    if (_prototypes.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto))
                        reagentName = proto.LocalizedName;

                    var reagentString = $"{Loc.GetString(
                        "group-solution-contents",
                        ("reagent", textInfo.ToTitleCase(reagentName)),
                        ("quantity", reagent.Quantity)
                    )}";

                    groupContainer.AddChild(CreateDiagnosticItemLabel(reagentString.Insert(0, " · ")));
                }
            }
        }

        // Goobstation
        private void DrawDiseases(IReadOnlyList<EntityUid> diseases)
        {
            DiseasesContainer.RemoveAllChildren();

            if (diseases.Count == 0)
            {
                DiseasesDivider.Visible = false;
                DiseasesContainer.Visible = false;
                return;
            }
            DiseasesDivider.Visible = true;
            DiseasesContainer.Visible = true;

            DiseasesContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-diseases"),
            });

            foreach (var diseaseUid in diseases)
            {
                if (!_entityManager.TryGetComponent<DiseaseComponent>(diseaseUid, out var disease))
                    continue;

                var diseaseInfoContainer = new BoxContainer
                {
                    Align = BoxContainer.AlignMode.Begin,
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                };
                diseaseInfoContainer.AddChild(CreateDiagnosticItemLabel(Loc.GetString("health-analyzer-window-disease-type-text", ("type", disease.Genotype))));
                diseaseInfoContainer.AddChild(CreateDiagnosticItemLabel(" · " + Loc.GetString(
                    "health-analyzer-window-disease-progress-text",
                    ("progress", disease.InfectionProgress)
                )));
                diseaseInfoContainer.AddChild(CreateDiagnosticItemLabel(" · " + Loc.GetString(
                    "health-analyzer-window-immunity-progress-text",
                    ("progress", disease.ImmunityProgress)
                )));

                DiseasesContainer.AddChild(diseaseInfoContainer);
            }
        }

        private Texture GetTexture(string texture)
        {
            var rsiPath = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
            var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

            var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
            if (!rsi.TryGetState(rsiSprite.RsiState, out var state))
            {
                rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
            }

            return _spriteSystem.Frame0(rsiSprite);
        }

        private static Label CreateDiagnosticItemLabel(string text)
        {
            return new Label
            {
                Text = text,
            };
        }

        private BoxContainer CreateDiagnosticGroupTitle(string text, string id)
        {
            var rootContainer = new BoxContainer
            {
                Margin = new Thickness(0, 6, 0, 0),
                VerticalAlignment = VAlignment.Bottom,
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
            };

            rootContainer.AddChild(new TextureRect
            {
                SetSize = new Vector2(30, 30),
                Texture = GetTexture(id.ToLower())
            });

            rootContainer.AddChild(CreateDiagnosticItemLabel(text));

            return rootContainer;
        }

        private BoxContainer CreateDiagnosticGroupTitle(string text, EntityUid ent, string? TextureOverride = null)
        {
            var rootContainer = new BoxContainer
            {
                Margin = new Thickness(0, 6, 0, 0),
                VerticalAlignment = VAlignment.Bottom,
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
            };

            if (TextureOverride != null)
            {
                rootContainer.AddChild(new TextureRect
                {
                    SetSize = new Vector2(30, 30),
                    Texture = GetTexture(TextureOverride.ToLower())
                });
            }
            else
            {
                var spriteView = new SpriteView
                {
                    SetSize = new Vector2(30, 30),
                    OverrideDirection = Direction.South,
                };

                spriteView.SetEntity(ent);

                rootContainer.AddChild(spriteView);
            }

            rootContainer.AddChild(CreateDiagnosticItemLabel(text));

            return rootContainer;
        }

        // Shitmed Change Start
        /// <summary>
        /// Sets up the Body Doll using Alert Entity to use in Health Analyzer.
        /// </summary>
        private EntityUid? SetupIcon(Dictionary<TargetBodyPart, WoundableSeverity>? body,
            Dictionary<TargetBodyPart, bool> bleeding)
        {
            if (body is null)
                return null;

            if (!_entityManager.Deleted(_spriteViewEntity))
                _entityManager.QueueDeleteEntity(_spriteViewEntity);

            _spriteViewEntity = _entityManager.Spawn(_bodyView);

            if (!_entityManager.TryGetComponent<SpriteComponent>(_spriteViewEntity, out var sprite))
                return null;

            int layer = 0;
            foreach (var (bodyPart, integrity) in body)
            {
                // TODO: PartStatusUIController and make it use layers instead of TextureRects when EE refactors alerts.
                string enumName = Enum.GetName(typeof(TargetBodyPart), bodyPart) ?? "Unknown";
                int enumValue = (int) integrity;
                var baseRsiPath = new ResPath($"/Textures/_Shitmed/Interface/Targeting/Status/{enumName.ToLowerInvariant()}.rsi");
                var rsi = new SpriteSpecifier.Rsi(baseRsiPath, $"{enumName.ToLowerInvariant()}_{enumValue}");
                // Shitcode with love from Russia :)
                CreateOrAddToLayer(sprite, rsi, layer);
                layer++;

                if (bleeding.TryGetValue(bodyPart, out var isBleeding) && isBleeding)
                {
                    var bleedRsi = new SpriteSpecifier.Rsi(baseRsiPath, $"{enumName.ToLowerInvariant()}_bleed");
                    CreateOrAddToLayer(sprite, bleedRsi, layer);
                    layer++;
                }
            }
            return _spriteViewEntity;
        }

        private void CreateOrAddToLayer(SpriteComponent sprite, SpriteSpecifier rsi, int layer)
        {
            if (!sprite.TryGetLayer(layer, out _))
                sprite.AddLayer(_spriteSystem.Frame0(rsi));
            else
                sprite.LayerSetTexture(layer, _spriteSystem.Frame0(rsi));

            sprite.LayerSetScale(layer, new Vector2(3f, 3f));
        }
        // Shitmed Change End
    }
}
