using Content.Shared._IS14.Economy.Payroll;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Economy.Payroll;

[GenerateTypedNameReferences]
public sealed partial class PayrollEmployeeRow : ContainerButton
{
    private static readonly Color ColorNormal   = Color.FromHex("#1C2236");
    private static readonly Color ColorHover    = Color.FromHex("#24304A");
    private static readonly Color ColorSelected = Color.FromHex("#2C3A5E");
    private static readonly Color ColorBorder   = Color.FromHex("#363E58");
    private static readonly Color ColorBorderSelected = Color.FromHex("#8A6C14");

    private static readonly Color ColorName    = Color.FromHex("#B8C4D8");
    private static readonly Color ColorJob     = Color.FromHex("#787880");
    private static readonly Color ColorSalary  = Color.FromHex("#A88A18");
    private static readonly Color ColorRaised  = Color.FromHex("#3ABB3A");
    private static readonly Color ColorCut     = Color.FromHex("#993030");
    private static readonly Color ColorOwed    = Color.FromHex("#993030");

    private bool _selected;

    public PayrollEmployeeRow()
    {
        RobustXamlLoader.Load(this);

        StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = ColorNormal,
            BorderColor = ColorBorder,
            BorderThickness = new Thickness(1),
        };
    }

    public void Initialize(PayrollEmployeeEntry entry)
    {
        NameLabel.Text = entry.Name;
        NameLabel.FontColorOverride = ColorName;

        JobLabel.Text = entry.JobTitle;
        JobLabel.FontColorOverride = ColorJob;

        SalaryLabel.Text = Loc.GetString("is14-payroll-credits", ("amount", entry.Salary));
        // The head should see at a glance who is above or below their job's base pay.
        SalaryLabel.FontColorOverride = entry.Salary > entry.BaseSalary
            ? ColorRaised
            : entry.Salary < entry.BaseSalary ? ColorCut : ColorSalary;

        OwedLabel.Visible = entry.OwedSalary > 0;
        OwedLabel.Text = Loc.GetString("is14-payroll-owed", ("amount", entry.OwedSalary));
        OwedLabel.FontColorOverride = ColorOwed;

        ToolTip = Loc.GetString("is14-payroll-row-tooltip",
            ("base", entry.BaseSalary),
            ("min", entry.MinSalary),
            ("max", entry.MaxSalary));
    }

    public void SetSelected(bool selected)
    {
        _selected = selected;
        DrawModeChanged();
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();

        if (StyleBoxOverride is not StyleBoxFlat flat)
            return;

        flat.BorderColor = _selected ? ColorBorderSelected : ColorBorder;
        flat.BackgroundColor = DrawMode switch
        {
            DrawModeEnum.Hover => ColorHover,
            DrawModeEnum.Pressed => ColorSelected,
            _ => _selected ? ColorSelected : ColorNormal,
        };
    }
}
