using System.Linq;
using Content.Shared._IS14.Economy.Fines;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Economy.Fines;

[GenerateTypedNameReferences]
public sealed partial class FineCartridgeUiFragment : BoxContainer
{
    /// <summary>Fired when the officer writes a fine: (record id, article preset id, amount).</summary>
    public event Action<uint, string, int>? OnIssue;

    /// <summary>Fired when the officer cancels a fine.</summary>
    public event Action<uint>? OnVoid;

    private List<FineTargetEntry> _targets = new();
    private List<FineArticleEntry> _articles = new();
    private int _maxAmount;

    /// <summary>Kept across refreshes so a rebuild doesn't drop the officer's selection.</summary>
    private uint? _selectedRecord;

    public FineCartridgeUiFragment()
    {
        RobustXamlLoader.Load(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        SearchEdit.OnTextChanged += _ => RebuildTargets();

        TargetSelector.OnItemSelected += args =>
        {
            TargetSelector.SelectId(args.Id);
            _selectedRecord = (uint)args.Id;
        };

        ArticleSelector.OnItemSelected += args =>
        {
            ArticleSelector.SelectId(args.Id);

            // Picking an article fills in its standard penalty; the officer can still edit it.
            if (args.Id >= 0 && args.Id < _articles.Count)
                AmountEdit.Text = _articles[args.Id].Amount.ToString();
        };

        IssueButton.OnPressed += _ => Submit();
        AmountEdit.OnTextEntered += _ => Submit();
    }

    public void UpdateState(FineCartridgeUiState state)
    {
        _targets = state.Targets;
        _articles = state.Articles;
        _maxAmount = state.MaxAmount;

        RebuildTargets();
        RebuildArticles();
        RebuildLedger(state.Fines);

        if (state.Status.Length > 0)
            StatusLabel.Text = state.Status;
    }

    private void RebuildTargets()
    {
        var filter = SearchEdit.Text.Trim();

        TargetSelector.Clear();

        var shown = _targets
            .Where(t => filter.Length == 0 || t.Name.Contains(filter, StringComparison.CurrentCultureIgnoreCase))
            .ToList();

        foreach (var target in shown)
        {
            var label = target.OutstandingAmount > 0
                ? Loc.GetString("is14-fine-target-debt",
                    ("name", target.Name),
                    ("job", target.JobTitle),
                    ("debt", target.OutstandingAmount))
                : Loc.GetString("is14-fine-target", ("name", target.Name), ("job", target.JobTitle));

            // The record id doubles as the item id, so selection survives filtering.
            TargetSelector.AddItem(label, (int)target.RecordId);
        }

        if (_selectedRecord is { } selected && shown.Any(t => t.RecordId == selected))
            TargetSelector.SelectId((int)selected);
        else if (shown.Count > 0)
            _selectedRecord = shown[0].RecordId;
        else
            _selectedRecord = null;
    }

    private void RebuildArticles()
    {
        var previous = ArticleSelector.SelectedId;

        ArticleSelector.Clear();

        for (var i = 0; i < _articles.Count; i++)
        {
            var article = _articles[i];
            ArticleSelector.AddItem(
                Loc.GetString("is14-fine-article", ("name", article.Name), ("amount", article.Amount)), i);
        }

        if (_articles.Count == 0)
            return;

        var select = previous >= 0 && previous < _articles.Count ? previous : 0;
        ArticleSelector.SelectId(select);

        if (AmountEdit.Text.Length == 0)
            AmountEdit.Text = _articles[select].Amount.ToString();
    }

    private void RebuildLedger(List<FineRecord> fines)
    {
        FineList.RemoveAllChildren();

        if (fines.Count == 0)
        {
            FineList.AddChild(new Label
            {
                Text = Loc.GetString("is14-fine-ledger-empty"),
                FontColorOverride = Color.FromHex("#8898A8"),
            });
            return;
        }

        foreach (var fine in fines)
            FineList.AddChild(MakeFineRow(fine));
    }

    private Control MakeFineRow(FineRecord fine)
    {
        var box = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 4),
        };

        var header = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        header.AddChild(new Label
        {
            Text = fine.TargetName,
            HorizontalExpand = true,
            ClipText = true,
            FontColorOverride = Color.FromHex("#B8C4D8"),
        });

        header.AddChild(new Label
        {
            Text = Loc.GetString("is14-fine-amount", ("amount", fine.Amount)),
            FontColorOverride = StatusColor(fine),
        });

        box.AddChild(header);

        box.AddChild(new Label
        {
            Text = Loc.GetString("is14-fine-row-details",
                ("article", fine.Article),
                ("officer", fine.OfficerName),
                ("status", StatusText(fine))),
            FontColorOverride = Color.FromHex("#8898A8"),
            ClipText = true,
        });

        if (fine.Outstanding)
        {
            var voidButton = new Button
            {
                Text = Loc.GetString("is14-fine-void"),
                HorizontalAlignment = HAlignment.Left,
                Margin = new Thickness(0, 2, 0, 0),
            };

            var id = fine.Id;
            voidButton.OnPressed += _ => OnVoid?.Invoke(id);
            box.AddChild(voidButton);
        }

        return box;
    }

    private static Color StatusColor(FineRecord fine)
    {
        if (fine.Voided)
            return Color.FromHex("#8898A8");

        return fine.Paid ? Color.FromHex("#3ABB3A") : Color.FromHex("#BF4040");
    }

    private static string StatusText(FineRecord fine)
    {
        if (fine.Voided)
            return Loc.GetString("is14-fine-state-voided");

        return Loc.GetString(fine.Paid ? "is14-fine-state-paid" : "is14-fine-state-unpaid");
    }

    private void Submit()
    {
        if (_selectedRecord is not { } record)
            return;

        var articleId = ArticleSelector.SelectedId;
        if (articleId < 0 || articleId >= _articles.Count)
            return;

        if (!int.TryParse(AmountEdit.Text, out var amount) || amount <= 0)
        {
            StatusLabel.Text = Loc.GetString("is14-fine-status-bad-amount");
            return;
        }

        if (amount > _maxAmount)
        {
            StatusLabel.Text = Loc.GetString("is14-fine-status-rejected", ("max", _maxAmount));
            return;
        }

        OnIssue?.Invoke(record, _articles[articleId].PresetId, amount);
    }
}
