using Content.Shared._IS14.Economy.PaymentTerminal;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._IS14.Economy.PaymentTerminal;

[GenerateTypedNameReferences]
public sealed partial class PaymentTerminalWindow : DefaultWindow
{
    /// <summary>(amount, description)</summary>
    public event Action<int, string>? OnSetCharge;
    public event Action? OnPay;
    public event Action? OnCancel;
    public event Action? OnBindCard;

    public PaymentTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        Add10Btn.OnPressed += _ => AddAmount(10);
        Add50Btn.OnPressed += _ => AddAmount(50);
        Add100Btn.OnPressed += _ => AddAmount(100);

        SetChargeBtn.OnPressed += _ => SubmitCharge();
        AmountEdit.OnTextEntered += _ => SubmitCharge();

        PayBtn.OnPressed += _ => OnPay?.Invoke();
        CancelBtn.OnPressed += _ => OnCancel?.Invoke();
        BindBtn.OnPressed += _ => OnBindCard?.Invoke();
    }

    public void UpdateState(IS14PaymentTerminalUiState state)
    {
        RecipientLabel.Text = state.RecipientLabel;

        var hasCharge = state.PendingAmount > 0;
        PayPanel.Visible = hasCharge;
        ChargePanel.Visible = !hasCharge;

        if (hasCharge)
        {
            PendingAmountLabel.Text = Loc.GetString("is14-payterm-pending", ("amount", state.PendingAmount));
            PendingDescLabel.Text = state.PendingDescription;
            PendingDescLabel.Visible = state.PendingDescription.Length > 0;
        }
        else
        {
            BindBtn.Visible = state.CanBind;
            SetChargeBtn.Disabled = !state.HasRecipient;
        }

        if (state.Status.Length > 0)
            StatusLabel.Text = state.Status;
    }

    private void AddAmount(int delta)
    {
        int.TryParse(AmountEdit.Text, out var current);
        AmountEdit.Text = (current + delta).ToString();
    }

    private void SubmitCharge()
    {
        if (!int.TryParse(AmountEdit.Text, out var amount) || amount <= 0)
            return;

        OnSetCharge?.Invoke(amount, DescEdit.Text);
        AmountEdit.Text = string.Empty;
        DescEdit.Text = string.Empty;
    }
}
