// Licensed under IS14's EULA, see EULA.txt for more information.

using Content.Client._IS14.Controls;
using Content.Client.UserInterface.Controls;
using Content.Shared._IS14.Modular;
using Content.Shared._IS14.Modular.Behaviours;
using Content.Shared.Atmos;
using Content.Shared.Atmos.Prototypes;
using Content.Shared.Inventory;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Globalization;
using System.Linq;
using System.Numerics;

namespace Content.Client._IS14.Modular;

/// <summary>
///     The chassis readout. Deliberately knows nothing about MOD suits specifically —
///     it renders charge, complexity, shell parts and modules, so a mech can open the same
///     window once the mech rework lands.
///
///     The layout is a dashboard rather than a list: a paper doll for the shell on the left
///     with a menu that expands under whichever piece you press, the power plant and module
///     bay on the right, and the two controls a wearer actually reaches for along the bottom.
///     Every control the player can press is captioned with an icon, because this is a suit
///     panel and suit panels do not spell things out.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ModularChassisWindow : FancyWindow
{
    #region Icons

    private const string IconEject = "/Textures/Interface/VerbIcons/eject.svg.192dpi.png";
    private const string IconNo = "/Textures/_IS14/Interface/VerbIcons/no.png";
    private const string IconDeploy = "/Textures/Interface/VerbIcons/open.svg.192dpi.png";
    private const string IconRetract = "/Textures/Interface/VerbIcons/close.svg.192dpi.png";
    private const string IconSeal = "/Textures/Interface/VerbIcons/lock.svg.192dpi.png";
    private const string IconUnseal = "/Textures/Interface/VerbIcons/unlock.svg.192dpi.png";
    private const string IconPower = "/Textures/Interface/VerbIcons/Spare/poweronoff.svg.192dpi.png";
    private const string IconTakeOut = "/Textures/Interface/VerbIcons/pickup.svg.192dpi.png";
    private const string IconPutAway = "/Textures/Interface/VerbIcons/in.svg.192dpi.png";
    private const string IconZap = "/Textures/Interface/VerbIcons/zap.svg.192dpi.png";
    private const string IconPanel = "/Textures/Interface/VerbIcons/settings.svg.192dpi.png";
    private const string IconShield = "/Textures/_IS14/Interface/VerbIcons/shield.png";
    private const string IconCheck = "/Textures/_IS14/Interface/VerbIcons/check.png";
    private const string IconCross = "/Textures/_IS14/Interface/VerbIcons/cross.png";
    private const string IconHammer = "/Textures/Interface/hammer_scaled.svg.192dpi.png";

    /// <summary>Linked nodes: complexity is a budget of things wired together.</summary>
    private const string IconComplexity = "/Textures/_IS14/Interface/VerbIcons/complexity.png";

    /// <summary>A bolt, standing in for the word "watt" everywhere a draw is printed.</summary>
    private const string IconBolt = "/Textures/_IS14/Interface/VerbIcons/power.png";

    private const string IconInternals = "/Textures/Interface/VerbIcons/dot.svg.192dpi.png";

    #endregion

    public event Action? OnToggleActive;
    public event Action? OnToggleDeploy;
    public event Action<NetEntity>? OnSelectModule;
    public event Action<NetEntity>? OnEjectModule;
    public event Action? OnEjectCell;
    public event Action? OnInsertCell;
    public event Action? OnOpenHopper;
    public event Action<NetEntity, string, object?>? OnConfigureModule;
    public event Action<NetEntity>? OnTogglePart;
    public event Action<NetEntity>? OnSealPart;

    private readonly IEntityManager _entMan;
    private readonly IPrototypeManager _protos;
    private readonly SpriteSystem _sprites;
    private readonly Dictionary<string, Texture> _icons = new();

    private readonly IS14Button _deployButton;
    private readonly IS14Button _sealButton;
    private readonly IS14Button _pumpButton;
    private readonly IS14Button _valveButton;
    private readonly IS14Button _internalsButton;
    private readonly IS14Button _cellButton;
    private readonly IS14Button _insertCellButton;
    private readonly IS14Button _hopperButton;

    /// <summary>Part whose menu is expanded below the doll, if any.</summary>
    private NetEntity? _selectedPart;

    /// <summary>True when the doll's hardware tile is the one expanded.</summary>
    private bool _hardwareSelected = true;

    /// <summary>Module whose card is showing its description, if any.</summary>
    private NetEntity? _expandedModule;

    /// <summary>Last state pushed, so a click on the doll can rebuild without a round trip.</summary>
    private ModularChassisUiState? _state;

    #region Slider settling

    /// <summary>
    ///     The setting whose handle is being held right now, if any.
    ///
    ///     The suit pushes a fresh state on almost anything, charge included, and charge
    ///     changes every tick — so the module list is rebuilt constantly. Rebuilding it
    ///     under a held handle destroys the very control being dragged.
    /// </summary>
    private (NetEntity Module, string Key)? _draggedConfig;

    /// <summary>
    ///     A state that arrived while a handle was held, applied once it is let go.
    /// </summary>
    private ModularChassisUiState? _deferredState;

    /// <summary>
    ///     What the player set, kept until the suit's own state agrees. Without it the
    ///     rebuild right after release shows the old value for the round trip and the
    ///     slider visibly snaps back and then forward again.
    /// </summary>
    private readonly Dictionary<(NetEntity Module, string Key), float> _pendingConfig = new();

    /// <summary>
    ///     How many state pushes a pending value survives unconfirmed.
    ///
    ///     Acting on the setting pushes a state itself, so confirmation normally arrives
    ///     within a push or two. The count only matters when the suit clamps what it was
    ///     given and will therefore never echo it back — then the slider has to stop
    ///     insisting and show what the suit actually did.
    /// </summary>
    private const int PendingConfigLife = 5;

    private readonly Dictionary<(NetEntity Module, string Key), int> _pendingConfigAge = new();

    #endregion

    /// <summary>Slots the paper doll has a fixed place for.</summary>
    private static readonly string[] DollSlots = { "head", "gloves", "outerClothing", "shoes" };

    public ModularChassisWindow()
    {
        RobustXamlLoader.Load(this);

        _entMan = IoCManager.Resolve<IEntityManager>();
        _protos = IoCManager.Resolve<IPrototypeManager>();
        _sprites = _entMan.System<SpriteSystem>();

        Backdrop.PanelOverride = new StyleBoxFlat(IS14Palette.Backdrop);
        HeaderPanel.PanelOverride = IS14Palette.Box(IS14Palette.PanelRaised, IS14Palette.BorderBright);
        DollPanel.PanelOverride = IS14Palette.Box(IS14Palette.Panel, IS14Palette.Border);
        DetailPanel.PanelOverride = IS14Palette.Box(IS14Palette.Panel, IS14Palette.Border);
        PowerPanel.PanelOverride = IS14Palette.Box(IS14Palette.Panel, IS14Palette.Border);
        ModulesPanel.PanelOverride = IS14Palette.Box(IS14Palette.Panel, IS14Palette.Border);
        TankPanel.PanelOverride = IS14Palette.Box(IS14Palette.Panel, IS14Palette.Border);

        // Same two glyphs the per-part menu uses, so "fold this piece" and "fold
        // everything" read as the same verb at two scales.
        _deployButton = IS14Button.Make(
            UiIcon(IconDeploy),
            Loc.GetString("chassis-ui-deploy-all"),
            IS14Palette.Accent);
        _deployButton.OnPressed += _ => OnToggleDeploy?.Invoke();
        _deployButton.Margin = new Thickness(0, 0, 4, 0);

        _sealButton = IS14Button.Make(
            UiIcon(IconSeal),
            Loc.GetString("chassis-ui-activate"),
            IS14Palette.Good);
        _sealButton.OnPressed += _ => OnToggleActive?.Invoke();

        ActionsContainer.AddChild(_deployButton);
        ActionsContainer.AddChild(_sealButton);

        // The compressor and the valve are module settings underneath, but they belong on
        // the gauge: the pressure they act on is already there to read.
        _pumpButton = IS14Button.Make(
            UiIcon(IconPower),
            Loc.GetString("chassis-config-pump"),
            IS14Palette.Accent,
            iconSize: 16f,
            padding: 4f);

        _pumpButton.HorizontalExpand = true;
        _pumpButton.Margin = new Thickness(0, 0, 0, 3);
        _pumpButton.OnPressed += _ => SendTankConfig(SharedModuleGasTankSystem.PumpKey, !(_state?.TankPumpEnabled ?? false));

        _valveButton = IS14Button.Make(
            UiIcon(IconDeploy),
            Loc.GetString("chassis-ui-tank-valve"),
            IS14Palette.Warn,
            iconSize: 16f,
            padding: 4f);

        _valveButton.HorizontalExpand = true;
        _valveButton.OnPressed += _ => SendTankConfig(SharedModuleGasTankSystem.ValveKey, !(_state?.TankValveOpen ?? false));

        // The station's own internals toggle is the alert in the corner of the HUD, and it
        // still works — but a suit that only becomes a breathing rig once every piece of it
        // is closed is not something a player finds by guessing.
        _internalsButton = IS14Button.Make(
            UiIcon(IconInternals),
            Loc.GetString("chassis-ui-tank-internals"),
            IS14Palette.Good,
            iconSize: 16f,
            padding: 4f);

        _internalsButton.HorizontalExpand = true;
        _internalsButton.Margin = new Thickness(0, 0, 0, 3);
        _internalsButton.OnPressed += _ => SendTankConfig(SharedModuleGasTankSystem.InternalsKey, true);

        TankControls.AddChild(_internalsButton);
        TankControls.AddChild(_pumpButton);
        TankControls.AddChild(_valveButton);

        _cellButton = IS14Button.Make(
            UiIcon(IconEject),
            Loc.GetString("chassis-ui-eject-cell"),
            IS14Palette.Warn,
            iconSize: 16f,
            padding: 4f);

        _cellButton.HorizontalExpand = true;
        _cellButton.OnPressed += _ => OnEjectCell?.Invoke();

        _hopperButton = IS14Button.Make(
            UiIcon(IconPutAway),
            Loc.GetString("chassis-ui-hopper"),
            IS14Palette.Accent,
            iconSize: 16f,
            padding: 4f);

        _hopperButton.HorizontalExpand = true;
        _hopperButton.Margin = new Thickness(0, 3, 0, 0);
        _hopperButton.OnPressed += _ => OnOpenHopper?.Invoke();

        _insertCellButton = IS14Button.Make(
            UiIcon(IconPutAway),
            Loc.GetString("chassis-ui-insert-cell"),
            IS14Palette.Accent,
            iconSize: 16f,
            padding: 4f);

        _insertCellButton.HorizontalExpand = true;
        _insertCellButton.OnPressed += _ => OnInsertCell?.Invoke();

        CoreControls.AddChild(_cellButton);
        CoreControls.AddChild(_insertCellButton);
        CoreControls.AddChild(_hopperButton);

        ComplexityIconBox.AddChild(IS14Palette.Icon(UiIcon(IconComplexity), 16f, IS14Palette.Muted));
    }

    /// <summary>
    ///     Routes a gauge switch back to the module that owns the bottle. Nothing here is
    ///     special-cased on the suit's side — it is the same channel the module cards use.
    /// </summary>
    private void SendTankConfig(string key, bool value)
    {
        if (_state?.TankModule is { } module)
            OnConfigureModule?.Invoke(module, key, value);
    }

    /// <summary>
    ///     Points the header portrait at the chassis itself. Called once, when the interface
    ///     opens, because the state carries no handle to its own owner.
    /// </summary>
    public void SetChassis(EntityUid chassis)
    {
        ChassisIcon.SetEntity(chassis);
    }

    public void UpdateState(ModularChassisUiState state)
    {
        _state = state;

        SettlePendingConfig(state);

        UpdateHeader(state);
        UpdatePower(state);
        UpdateDoll(state);
        UpdateDetail(state);

        // Everything else redraws as usual; only the module list waits, because it is the
        // only part holding a control the player has hold of.
        if (_draggedConfig != null)
            _deferredState = state;
        else
            UpdateModules(state);

        UpdateActions(state);
    }

    /// <summary>
    ///     Drops pending values the suit has confirmed, and ages out the ones it never
    ///     will — a setting clamped on arrival comes back as a different number, and the
    ///     slider has to stop insisting on what was asked for.
    /// </summary>
    private void SettlePendingConfig(ModularChassisUiState state)
    {
        if (_pendingConfig.Count == 0)
            return;

        foreach (var module in state.Modules)
        {
            foreach (var entry in module.Config)
            {
                var id = (module.Module, entry.Key);

                if (!_pendingConfig.TryGetValue(id, out var pending))
                    continue;

                if (entry.Value is float actual && MathHelper.CloseTo(actual, pending, 0.001f))
                    Forget(id);
            }
        }

        foreach (var id in _pendingConfigAge.Keys.ToArray())
        {
            if (++_pendingConfigAge[id] > PendingConfigLife)
                Forget(id);
        }

        void Forget((NetEntity, string) id)
        {
            _pendingConfig.Remove(id);
            _pendingConfigAge.Remove(id);
        }
    }

    /// <summary>
    ///     Called when a handle is let go: the list has been standing still while it was
    ///     held, so whatever arrived meanwhile is applied now.
    /// </summary>
    private void EndConfigDrag()
    {
        _draggedConfig = null;

        if (_deferredState is not { } state)
            return;

        _deferredState = null;
        UpdateModules(state);
    }

    #region Header

    private void UpdateHeader(ModularChassisUiState state)
    {
        SuitNameLabel.Text = state.ChassisName;

        WearerLabel.Text = string.IsNullOrEmpty(state.WearerName)
            ? Loc.GetString("chassis-ui-unworn")
            : string.IsNullOrEmpty(state.WearerJob)
                ? state.WearerName
                : $"{state.WearerName} — {state.WearerJob}";

        ChipsContainer.RemoveAllChildren();

        var (stateLoc, stateColor) = state.Active
            ? ("chassis-ui-state-sealed", IS14Palette.Good)
            : state.AnyDeployed
                ? ("chassis-ui-state-deployed", IS14Palette.Accent)
                : ("chassis-ui-state-stowed", IS14Palette.Muted);

        ChipsContainer.AddChild(IS14Palette.Chip(Loc.GetString(stateLoc), stateColor));

        if (state.Malfunctioning)
            ChipsContainer.AddChild(IS14Palette.Chip(Loc.GetString("chassis-ui-malfunctioning"), IS14Palette.Bad));

        if (state.Electrified)
            ChipsContainer.AddChild(IS14Palette.Chip(Loc.GetString("chassis-ui-electrified"), IS14Palette.Bad));

        if (state.PowerCut)
            ChipsContainer.AddChild(IS14Palette.Chip(Loc.GetString("chassis-ui-power-cut"), IS14Palette.Bad));

        if (state.Overloaded)
            ChipsContainer.AddChild(IS14Palette.Chip(Loc.GetString("chassis-ui-overloaded"), IS14Palette.Warn));

        if (state.InterfaceBroken)
            ChipsContainer.AddChild(IS14Palette.Chip(Loc.GetString("chassis-ui-interface-broken"), IS14Palette.Bad));

        if (state.PanelOpen)
            ChipsContainer.AddChild(IS14Palette.Chip(Loc.GetString("chassis-ui-panel-open"), IS14Palette.Warn));
    }

    #endregion

    #region Power

    private void UpdatePower(ModularChassisUiState state)
    {
        var present = state.MaxCharge > 0f;
        var fraction = present ? Math.Clamp(state.Charge / state.MaxCharge, 0f, 1f) : 0f;

        Battery.Present = present;
        Battery.Fraction = fraction;
        Battery.Draining = present && state.Draw > 0f && fraction <= 0.4f;

        if (present)
        {
            ChargePercentLabel.Text = $"{(int) MathF.Round(fraction * 100f)}%";
            ChargePercentLabel.FontColorOverride = fraction switch
            {
                <= 0.15f => IS14Palette.Bad,
                <= 0.4f => IS14Palette.Warn,
                _ => IS14Palette.Good,
            };

            ChargeLabel.Text = Loc.GetString(
                "chassis-ui-charge-value",
                ("current", (int) MathF.Round(state.Charge)),
                ("max", (int) MathF.Round(state.MaxCharge)),
                ("draw", Num(state.Draw)));
        }
        else
        {
            ChargePercentLabel.Text = "—";
            ChargePercentLabel.FontColorOverride = IS14Palette.Bad;
            ChargeLabel.Text = NoChargeReason(state);
        }

        CoreLabel.Text = state.CoreName ?? Loc.GetString("chassis-ui-no-core");
        CoreLabel.FontColorOverride = state.CoreName == null ? IS14Palette.Bad : IS14Palette.Muted;

        UpdateCore(state);
        UpdateTank(state);

        Complexity.Used = state.UsedComplexity;
        Complexity.Max = state.MaxComplexity;
        ComplexityLabel.Text = $"{state.UsedComplexity} / {state.MaxComplexity}";
        ComplexityLabel.FontColorOverride = state.UsedComplexity >= state.MaxComplexity
            ? IS14Palette.Warn
            : IS14Palette.Muted;
    }

    /// <summary>
    ///     The two things a core can offer the panel. Both hide themselves when the
    ///     installed core has nothing of the sort — an empty row of dead buttons reads as
    ///     broken, not as "not applicable".
    /// </summary>
    /// <summary>
    ///     Why there is nothing to draw on. An empty socket and a core with its cell
    ///     pulled read identically from the battery's side and need different things done
    ///     about them, so they are not allowed to share a message.
    /// </summary>
    private static string NoChargeReason(ModularChassisUiState state)
    {
        return Loc.GetString(state.CoreName == null
            ? "chassis-ui-no-core"
            : "chassis-ui-no-cell");
    }

    private void UpdateCore(ModularChassisUiState state)
    {
        // A core that takes a cell shows exactly one of the two buttons: whichever
        // direction the slot can currently go.
        var hasCell = state.CoreCellName != null;

        _cellButton.Visible = state.CoreTakesCell && hasCell;
        _cellButton.Disabled = !state.PanelOpen;
        _cellButton.ToolTip = Loc.GetString(state.PanelOpen
            ? "chassis-ui-eject-cell-tooltip"
            : "chassis-ui-eject-needs-panel");

        if (_cellButton.Visible)
        {
            _cellButton.SetContent(
                UiIcon(state.PanelOpen ? IconEject : IconNo),
                Loc.GetString("chassis-ui-eject-cell"));
        }

        _insertCellButton.Visible = state.CoreTakesCell && !hasCell;
        _insertCellButton.Disabled = !state.PanelOpen;
        _insertCellButton.ToolTip = Loc.GetString(state.PanelOpen
            ? "chassis-ui-insert-cell-tooltip"
            : "chassis-ui-eject-needs-panel");

        if (_insertCellButton.Visible)
        {
            _insertCellButton.SetContent(
                UiIcon(state.PanelOpen ? IconPutAway : IconNo),
                Loc.GetString("chassis-ui-insert-cell"));
        }

        _hopperButton.Visible = state.CoreHasHopper;
        _hopperButton.ToolTip = Loc.GetString("chassis-ui-hopper-tooltip");
    }

    /// <summary>
    ///     The bottle. Nothing to show without an atmospheric module, so the dial reads
    ///     dead rather than pretending the suit has an empty tank.
    /// </summary>
    private void UpdateTank(ModularChassisUiState state)
    {
        Tank.Present = state.TankPresent;
        Tank.Pumping = state.TankPumping;

        var target = state.TankTargetPressure > 0f ? state.TankTargetPressure : 1f;
        Tank.Fraction = state.TankPresent ? Math.Clamp(state.TankPressure / target, 0f, 1f) : 0f;

        TankGasContainer.RemoveAllChildren();
        TankSealRow.RemoveAllChildren();

        _pumpButton.Visible = state.TankPresent;
        _valveButton.Visible = state.TankPresent;
        _internalsButton.Visible = state.TankPresent;

        if (!state.TankPresent)
        {
            TankPressureLabel.Text = Loc.GetString("chassis-ui-no-tank");
            TankPressureLabel.FontColorOverride = IS14Palette.Muted;
            TankTemperatureLabel.Text = string.Empty;
            TankContentsLabel.Text = string.Empty;
            return;
        }

        TankPressureLabel.Text = Loc.GetString("chassis-ui-tank-value", ("kpa", (int) MathF.Round(state.TankPressure)));
        TankPressureLabel.FontColorOverride = Tank.NeedleColor;

        // Celsius, because nobody sizing up a bottle thinks in kelvin. An empty bottle
        // has a temperature on paper and nothing to have it, so it does not get a reading.
        TankTemperatureLabel.Text = state.TankEmpty
            ? string.Empty
            : Loc.GetString(
                "chassis-ui-tank-temperature",
                ("celsius", (int) MathF.Round(state.TankTemperature - 273.15f)));

        TankTemperatureLabel.FontColorOverride = IS14Palette.Muted;

        UpdateTankGases(state);

        // Whether the suit is holding pressure at all, as a tick or a cross. It is the
        // precondition for both the compressor and internals, so it gets its own line
        // rather than being explained again inside every message that depends on it.
        var sealColor = state.TankCanPump ? IS14Palette.Good : IS14Palette.Bad;

        TankSealRow.AddChild(IS14Palette.Icon(
            UiIcon(state.TankCanPump ? IconCheck : IconCross),
            14f,
            sealColor));

        TankSealRow.AddChild(new Label
        {
            Text = Loc.GetString("chassis-ui-tank-seal"),
            Margin = new Thickness(4, 0, 0, 0),
            StyleClasses = { "LabelSubText" },
            FontColorOverride = sealColor,
        });

        TankSealRow.ToolTip = Loc.GetString("chassis-ui-tank-unsealed");

        TankContentsLabel.Text = string.IsNullOrEmpty(state.TankContents)
            ? Loc.GetString("chassis-ui-tank-idle")
            : state.TankContents;

        TankContentsLabel.FontColorOverride = state.TankPumping ? IS14Palette.Accent : IS14Palette.Muted;

        _pumpButton.Selected = state.TankPumping;
        _pumpButton.Disabled = !state.TankCanPump;
        _pumpButton.Accent = state.TankCanPump ? IS14Palette.Accent : IS14Palette.Muted;
        _pumpButton.ToolTip = Loc.GetString(state.TankCanPump
            ? "chassis-ui-tank-pump-tooltip"
            : "chassis-ui-tank-unsealed");

        _valveButton.Selected = state.TankValveOpen;
        _valveButton.SetContent(
            UiIcon(state.TankValveOpen ? IconRetract : IconDeploy),
            Loc.GetString(state.TankValveOpen ? "chassis-ui-tank-valve-close" : "chassis-ui-tank-valve"));

        _valveButton.ToolTip = Loc.GetString("chassis-ui-tank-valve-tooltip");

        // Breathing asks for more than the compressor does: every piece closed, and a
        // valve that is not busy emptying the bottle into the room.
        var canBreathe = state.TankCanBreathe && !state.TankValveOpen;

        _internalsButton.Selected = state.TankInternalsOn;
        _internalsButton.Disabled = !canBreathe && !state.TankInternalsOn;
        _internalsButton.Accent = canBreathe || state.TankInternalsOn ? IS14Palette.Good : IS14Palette.Muted;

        _internalsButton.SetContent(
            UiIcon(IconInternals),
            Loc.GetString(state.TankInternalsOn
                ? "chassis-ui-tank-internals-off"
                : "chassis-ui-tank-internals"));

        _internalsButton.ToolTip = Loc.GetString(canBreathe || state.TankInternalsOn
            ? "chassis-ui-tank-internals-tooltip"
            : "chassis-ui-tank-internals-needs-seal");
    }

    /// <summary>
    ///     What is actually in the bottle. Only the three largest shares are listed: a
    ///     readout that spells out four decimal places of trace argon is a readout nobody
    ///     glances at.
    /// </summary>
    private void UpdateTankGases(ModularChassisUiState state)
    {
        if (state.TankGases.Count == 0)
        {
            TankGasContainer.AddChild(new Label
            {
                Text = Loc.GetString("chassis-ui-tank-empty"),
                StyleClasses = { "LabelSubText" },
                FontColorOverride = IS14Palette.Muted,
            });

            return;
        }

        var shown = 0;
        var rest = 0f;

        foreach (var entry in state.TankGases)
        {
            if (shown >= 3 || entry.Fraction < 0.005f)
            {
                rest += entry.Fraction;
                continue;
            }

            shown++;

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            row.AddChild(new Label
            {
                Text = GasName(entry.Gas),
                StyleClasses = { "LabelSubText" },
                FontColorOverride = GasColor(entry.Gas),
                HorizontalExpand = true,
                ClipText = true,
            });

            row.AddChild(new Label
            {
                Text = Loc.GetString("chassis-ui-tank-share", ("percent", (int) MathF.Round(entry.Fraction * 100f))),
                StyleClasses = { "LabelSubText" },
                FontColorOverride = IS14Palette.Muted,
            });

            TankGasContainer.AddChild(row);
        }

        if (rest < 0.005f)
            return;

        TankGasContainer.AddChild(new Label
        {
            Text = Loc.GetString("chassis-ui-tank-rest", ("percent", (int) MathF.Round(rest * 100f))),
            StyleClasses = { "LabelSubText" },
            FontColorOverride = IS14Palette.Muted,
        });
    }

    private string GasName(Gas gas)
    {
        return _protos.TryIndex<GasPrototype>(gas.ToString(), out var proto)
            ? Loc.GetString(proto.Name)
            : gas.ToString();
    }

    private Color GasColor(Gas gas)
    {
        if (!_protos.TryIndex<GasPrototype>(gas.ToString(), out var proto)
            || string.IsNullOrEmpty(proto.Color)
            || Color.TryFromHex("#" + proto.Color) is not { } color)
        {
            return IS14Palette.Text;
        }

        // Gas colours are picked to show up against a dark tile, not against panel grey.
        return Color.InterpolateBetween(color, IS14Palette.Text, 0.35f);
    }

    #endregion

    #region Paper doll

    private void UpdateDoll(ModularChassisUiState state)
    {
        DollGrid.RemoveAllChildren();
        ExtraPartsContainer.RemoveAllChildren();

        var bySlot = new Dictionary<string, ChassisPartUiEntry>();
        var extras = new List<ChassisPartUiEntry>();

        foreach (var part in state.Parts)
        {
            if (Array.IndexOf(DollSlots, part.Slot) >= 0 && !bySlot.ContainsKey(part.Slot))
                bySlot[part.Slot] = part;
            else
                extras.Add(part);
        }

        // Row 1: head, centred over the body.
        DollGrid.AddChild(Spacer());
        DollGrid.AddChild(SlotCell(bySlot, "head"));
        DollGrid.AddChild(Spacer());

        // Row 2: gauntlets, then the core, then the chestplate. The core sits dead
        // centre because everything else on the readout hangs off it.
        DollGrid.AddChild(SlotCell(bySlot, "gloves"));
        DollGrid.AddChild(HardwareTile(state));
        DollGrid.AddChild(SlotCell(bySlot, "outerClothing"));

        // Row 3: legs.
        DollGrid.AddChild(Spacer());
        DollGrid.AddChild(SlotCell(bySlot, "shoes"));
        DollGrid.AddChild(Spacer());

        // Anything the doll has no anatomy for still has to be reachable.
        foreach (var part in extras)
        {
            var wrap = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 4, 0, 0),
            };

            wrap.AddChild(PartTile(part));
            ExtraPartsContainer.AddChild(wrap);
        }
    }

    private Control SlotCell(Dictionary<string, ChassisPartUiEntry> parts, string slot)
    {
        return parts.TryGetValue(slot, out var part) ? PartTile(part) : EmptyTile(slot);
    }

    private static Control Spacer() => new Control { MinSize = new Vector2(80, 4) };

    /// <summary>
    ///     One piece of the shell. The tile is the whole control: its frame carries the
    ///     state colour, so the doll reads as a diagram before you look at any text.
    /// </summary>
    private Control PartTile(ChassisPartUiEntry part)
    {
        var color = PartColor(part);

        var button = new IS14Button
        {
            Accent = color,
            Selected = _selectedPart == part.Part && !_hardwareSelected,
            MinSize = new Vector2(80, 88),
            ToolTip = part.Name,
            Padding = 4f,
        };

        var stack = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
        };

        stack.AddChild(new SpriteView(part.Part, _entMan)
        {
            SetSize = new Vector2(40, 40),
            OverrideDirection = Direction.South,
            HorizontalAlignment = HAlignment.Center,
        });

        stack.AddChild(new Label
        {
            Text = Loc.GetString(SlotLocId(part.Slot)),
            StyleClasses = { "LabelSubText" },
            FontColorOverride = IS14Palette.Text,
            HorizontalAlignment = HAlignment.Center,
        });

        stack.AddChild(IntegrityStrip(part));
        stack.AddChild(StateStrip(color));

        button.AddChild(stack);

        var id = part.Part;
        button.OnPressed += _ =>
        {
            _selectedPart = id;
            _hardwareSelected = false;
            Rebuild();
        };

        return button;
    }

    /// <summary>
    ///     A slot this chassis simply has no piece for.
    /// </summary>
    private static Control EmptyTile(string slot)
    {
        var panel = new PanelContainer
        {
            PanelOverride = IS14Palette.Box(IS14Palette.Backdrop, IS14Palette.Border, 1f, 4f),
            MinSize = new Vector2(80, 88),
        };

        panel.AddChild(new Label
        {
            Text = Loc.GetString(SlotLocId(slot)),
            StyleClasses = { "LabelSubText" },
            FontColorOverride = IS14Palette.Border,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        });

        return panel;
    }

    /// <summary>
    ///     The control unit's own tile — core, panel and lock hang off this one.
    /// </summary>
    private Control HardwareTile(ModularChassisUiState state)
    {
        var color = state.CoreName == null || state.PowerCut
            ? IS14Palette.Bad
            : state.PanelOpen || state.InterfaceBroken || state.Overloaded
                || state.DeployLinkCut || state.SealLinkCut
                ? IS14Palette.Warn
                : IS14Palette.Accent;

        var button = new IS14Button
        {
            Accent = color,
            Selected = _hardwareSelected,
            MinSize = new Vector2(80, 88),
            ToolTip = Loc.GetString("chassis-ui-hardware"),
            Padding = 4f,
        };

        var stack = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
        };

        // Draw the core that is actually in there. The tile used to hardcode the standard
        // one, so swapping in a plasma core changed the name underneath and nothing else —
        // and the picture is the half people read.
        if (state.Core is { } core)
        {
            stack.AddChild(new SpriteView(core, _entMan)
            {
                SetSize = new Vector2(40, 40),
                OverrideDirection = Direction.South,
            });
        }
        else
        {
            stack.AddChild(new TextureRect
            {
                Texture = Icon("/Textures/_IS14/Objects/Modsuit/construction.rsi", "core-standard"),
                Stretch = TextureRect.StretchMode.KeepCentered,
                MinSize = new Vector2(40, 40),
                ModulateSelfOverride = IS14Palette.Bad,
            });
        }

        stack.AddChild(new Label
        {
            Text = Loc.GetString("chassis-ui-hardware"),
            StyleClasses = { "LabelSubText" },
            FontColorOverride = IS14Palette.Text,
            HorizontalAlignment = HAlignment.Center,
        });

        stack.AddChild(StateStrip(color));

        button.AddChild(stack);

        button.OnPressed += _ =>
        {
            _hardwareSelected = true;
            _selectedPart = null;
            Rebuild();
        };

        return button;
    }

    private static Control StateStrip(Color color) => new PanelContainer
    {
        PanelOverride = new StyleBoxFlat(color),
        MinSize = new Vector2(48, 3),
        Margin = new Thickness(0, 3, 0, 0),
        HorizontalAlignment = HAlignment.Center,
    };

    /// <summary>
    ///     Condition under the tile, so the doll shows wear without being opened.
    /// </summary>
    private static Control IntegrityStrip(ChassisPartUiEntry part) => new ThresholdBar
    {
        Fraction = Fraction(part),
        WarnThreshold = part.ModuleThreshold,
        LowThreshold = part.UnsealThreshold,
        SetSize = new Vector2(48, 4),
        Margin = new Thickness(0, 3, 0, 0),
        HorizontalAlignment = HAlignment.Center,
    };

    /// <summary>
    ///     Battered plating reads red whatever else it is doing: a sealed piece that has
    ///     stopped carrying its modules is the state a player most needs to notice.
    /// </summary>
    private static Color PartColor(ChassisPartUiEntry part) => part.Ruptured
        ? IS14Palette.Bad
        : part.Broken
            ? IS14Palette.Warn
            : part.Sealed
                ? IS14Palette.Good
                : part.Deployed
                    ? IS14Palette.Accent
                    : IS14Palette.Muted;

    private static float Fraction(ChassisPartUiEntry part) =>
        part.MaxIntegrity > 0f ? Math.Clamp(part.Integrity / part.MaxIntegrity, 0f, 1f) : 1f;


    #endregion

    #region Expanded detail

    private void UpdateDetail(ModularChassisUiState state)
    {
        DetailContainer.RemoveAllChildren();

        if (!_hardwareSelected)
        {
            var part = state.Parts.FirstOrDefault(p => p.Part == _selectedPart);

            if (part != null)
            {
                BuildPartDetail(part, state);
                return;
            }

            // The part went away — fall back rather than leaving a blank panel.
            _hardwareSelected = true;
            _selectedPart = null;
        }

        BuildHardwareDetail(state);
    }

    private void BuildPartDetail(ChassisPartUiEntry part, ModularChassisUiState state)
    {
        DetailContainer.AddChild(IS14Palette.Heading(part.Name));

        DetailContainer.AddChild(IS14Palette.Sub(Loc.GetString(PartStateLocId(part)), PartColor(part)));
        DetailContainer.AddChild(IS14Palette.Rule());

        BuildIntegrityBlock(part);
        DetailContainer.AddChild(IS14Palette.Rule());

        var id = part.Part;

        // A sealed piece is welded shut; unseal it before anything folds away.
        var deploy = IS14Button.Make(
            UiIcon(part.Sealed ? IconNo : part.Deployed ? IconRetract : IconDeploy),
            Loc.GetString(part.Deployed ? "chassis-ui-retract" : "chassis-ui-deploy"),
            part.Deployed ? IS14Palette.Warn : IS14Palette.Accent);

        deploy.HorizontalExpand = true;
        deploy.Margin = new Thickness(0, 0, 4, 0);
        deploy.Disabled = part.Sealed;
        deploy.OnPressed += _ => OnTogglePart?.Invoke(id);

        var canSeal = part.Deployed && (part.Sealed || !part.Ruptured);

        var seal = IS14Button.Make(
            UiIcon(!canSeal ? IconNo : part.Sealed ? IconUnseal : IconSeal),
            Loc.GetString(part.Sealed ? "chassis-ui-unseal" : "chassis-ui-seal"),
            part.Sealed ? IS14Palette.Good : IS14Palette.Accent);

        seal.HorizontalExpand = true;
        seal.Selected = part.Sealed;
        seal.Disabled = !canSeal;
        seal.OnPressed += _ => OnSealPart?.Invoke(id);

        // Side by side: two verbs on one piece, and stacking them made the panel a column
        // of buttons taller than the readout it belongs to.
        var actions = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        actions.AddChild(deploy);
        actions.AddChild(seal);
        DetailContainer.AddChild(actions);

        if (part.Deployed && state.MaxCharge <= 0f)
            DetailContainer.AddChild(IS14Palette.Sub(NoChargeReason(state), IS14Palette.Bad));
    }

    /// <summary>
    ///     Plating condition, with the consequence spelled out rather than left to the
    ///     player to infer from a bar that has gone red.
    /// </summary>
    private void BuildIntegrityBlock(ChassisPartUiEntry part)
    {
        var fraction = Fraction(part);
        var bar = new ThresholdBar
        {
            Fraction = fraction,
            WarnThreshold = part.ModuleThreshold,
            LowThreshold = part.UnsealThreshold,
            MinHeight = 8,
            HorizontalExpand = true,
        };

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        var glyph = IS14Palette.Icon(UiIcon(part.Broken ? IconNo : IconShield), 16f, bar.FillColor);
        glyph.Margin = new Thickness(0, 0, 6, 0);
        header.AddChild(glyph);

        header.AddChild(new Label
        {
            Text = Loc.GetString("chassis-ui-integrity"),
            HorizontalExpand = true,
            StyleClasses = { "LabelSubText" },
        });

        header.AddChild(new Label
        {
            Text = Loc.GetString(
                "chassis-ui-integrity-value",
                ("current", (int) MathF.Round(part.Integrity)),
                ("max", (int) MathF.Round(part.MaxIntegrity))),
            FontColorOverride = bar.FillColor,
        });

        DetailContainer.AddChild(header);
        DetailContainer.AddChild(bar);

        // The two thresholds spelled out as the two things the piece is for, rather than
        // as a sentence the player has to translate back into consequences.
        DetailContainer.AddChild(StatusRow("chassis-ui-status-seal", !part.Ruptured));
        DetailContainer.AddChild(StatusRow("chassis-ui-status-modules", !part.Broken));

        if (part.Fault == ChassisPartFault.None)
            return;

        var fix = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 5, 0, 0),
        };

        var hammer = IS14Palette.Icon(UiIcon(IconHammer), 16f, IS14Palette.Accent);
        hammer.Margin = new Thickness(0, 0, 6, 0);
        fix.AddChild(hammer);

        fix.AddChild(new Label
        {
            Text = Loc.GetString(part.Fault == ChassisPartFault.Electrical
                ? "chassis-ui-fault-electrical"
                : "chassis-ui-fault-structural"),
            HorizontalExpand = true,
            StyleClasses = { "LabelSubText" },
            FontColorOverride = IS14Palette.Accent,
        });

        DetailContainer.AddChild(fix);
    }

    /// <summary>
    ///     One capability of a piece, ticked or crossed. Green means it still does this;
    ///     red means that threshold has been crossed.
    /// </summary>
    private Control StatusRow(string labelLoc, bool ok)
    {
        var color = ok ? IS14Palette.Good : IS14Palette.Bad;

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 0),
        };

        var glyph = IS14Palette.Icon(UiIcon(ok ? IconCheck : IconCross), 14f, color);
        glyph.Margin = new Thickness(0, 0, 6, 0);
        row.AddChild(glyph);

        row.AddChild(new Label
        {
            Text = Loc.GetString(labelLoc),
            HorizontalExpand = true,
            StyleClasses = { "LabelSubText" },
            FontColorOverride = color,
        });

        return row;
    }

    private void BuildHardwareDetail(ModularChassisUiState state)
    {
        DetailContainer.AddChild(IS14Palette.Heading(Loc.GetString("chassis-ui-hardware")));
        DetailContainer.AddChild(IS14Palette.Rule());

        DetailContainer.AddChild(HardwareRow(
            UiIcon(IconZap),
            "chassis-ui-hw-core",
            state.CoreName ?? Loc.GetString("chassis-ui-no-core"),
            state.CoreName == null ? IS14Palette.Bad : IS14Palette.Good));

        if (state.CoreTakesCell)
        {
            DetailContainer.AddChild(HardwareRow(
                UiIcon(state.CoreCellName != null ? IconCheck : IconCross),
                "chassis-ui-hw-cell",
                state.CoreCellName ?? Loc.GetString("chassis-ui-no-cell"),
                state.CoreCellName == null ? IS14Palette.Bad : IS14Palette.Good));
        }

        DetailContainer.AddChild(HardwareRow(
            UiIcon(IconPanel),
            "chassis-ui-hw-panel",
            Loc.GetString(state.PanelOpen ? "chassis-ui-panel-open" : "chassis-ui-panel-shut"),
            state.PanelOpen ? IS14Palette.Warn : IS14Palette.Muted));

        if (state.Locked is { } locked)
        {
            DetailContainer.AddChild(HardwareRow(
                UiIcon(locked ? IconSeal : IconUnseal),
                "chassis-ui-hw-lock",
                Loc.GetString(state.AccessWiped
                    ? "chassis-ui-lock-wiped"
                    : locked
                        ? "chassis-ui-lock-engaged"
                        : "chassis-ui-lock-open"),
                state.AccessWiped ? IS14Palette.Bad : locked ? IS14Palette.Good : IS14Palette.Warn));
        }

        // The DNA lock's own row. It used to have none, so pressing its button changed
        // nothing anybody could see and the module read as broken when it was working.
        if (state.DnaLockPresent)
        {
            DetailContainer.AddChild(HardwareRow(
                UiIcon(state.DnaLockBroken ? IconCross : state.DnaLockImprinted ? IconSeal : IconUnseal),
                "chassis-ui-hw-dna",
                Loc.GetString(state.DnaLockBroken
                    ? "chassis-ui-dna-broken"
                    : state.DnaLockImprinted
                        ? "chassis-ui-dna-imprinted"
                        : "chassis-ui-dna-blank"),
                state.DnaLockBroken ? IS14Palette.Bad : state.DnaLockImprinted ? IS14Palette.Good : IS14Palette.Warn));
        }

        DetailContainer.AddChild(HardwareRow(
            UiIcon(IconPower),
            "chassis-ui-hw-draw",
            Loc.GetString("chassis-ui-draw", ("draw", Num(state.Draw))),
            IS14Palette.Muted));

        BuildFaultList(state);
    }

    /// <summary>
    ///     Everything wrong with the suit, in one list.
    ///
    ///     These used to be rows alongside the core and the panel, each reading "fine" almost
    ///     all of the time — which is a lot of readout spent saying nothing, and it buried
    ///     the one line that mattered when something did break. A list that is empty when
    ///     the suit is healthy puts the weight back where it belongs: anything in here is a
    ///     problem, and there is nothing else to read past.
    /// </summary>
    private void BuildFaultList(ModularChassisUiState state)
    {
        DetailContainer.AddChild(IS14Palette.Rule());
        DetailContainer.AddChild(IS14Palette.Heading(Loc.GetString("chassis-ui-faults")));

        var any = false;

        void Fault(string icon, string locId, Color color)
        {
            any = true;
            DetailContainer.AddChild(FaultRow(UiIcon(icon), Loc.GetString(locId), color));
        }

        // Ordered by what a wearer should deal with first: no power at all, then the
        // circuit, then the two links, then the readout, then the shell being live.
        if (state.PowerCut)
            Fault(IconCross, "chassis-ui-fault-power-cut", IS14Palette.Bad);

        if (state.Overloaded)
            Fault(IconZap, "chassis-ui-fault-overloaded", IS14Palette.Warn);

        if (state.Malfunctioning)
            Fault(IconZap, "chassis-ui-fault-malfunctioning", IS14Palette.Bad);

        if (state.DeployLinkCut)
            Fault(IconCross, "chassis-ui-fault-link-deploy", IS14Palette.Bad);

        if (state.SealLinkCut)
            Fault(IconCross, "chassis-ui-fault-link-seal", IS14Palette.Bad);

        if (state.InterfaceBroken)
            Fault(IconCross, "chassis-ui-fault-interface", IS14Palette.Bad);

        if (state.Electrified)
            Fault(IconZap, "chassis-ui-fault-electrified", IS14Palette.Bad);

        if (state.DnaLockBroken)
            Fault(IconCross, "chassis-ui-fault-dna-broken", IS14Palette.Bad);

        if (!any)
            DetailContainer.AddChild(IS14Palette.Sub(Loc.GetString("chassis-ui-faults-none")));
    }

    /// <summary>
    ///     A fault has no label to put on the left — the fault is the whole line — so it
    ///     gets its own row rather than reusing the name/value pair above.
    /// </summary>
    private static Control FaultRow(Texture? icon, string text, Color color)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2),
        };

        var glyph = IS14Palette.Icon(icon, 16f, color);
        glyph.Margin = new Thickness(0, 0, 6, 0);
        row.AddChild(glyph);

        row.AddChild(new Label
        {
            Text = text,
            HorizontalExpand = true,
            ClipText = true,
            FontColorOverride = color,
        });

        return row;
    }

    private static Control HardwareRow(Texture? icon, string labelLoc, string value, Color color)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2),
        };

        var glyph = IS14Palette.Icon(icon, 16f, IS14Palette.Muted);
        glyph.Margin = new Thickness(0, 0, 6, 0);
        row.AddChild(glyph);

        row.AddChild(new Label
        {
            Text = Loc.GetString(labelLoc),
            MinWidth = 74,
            StyleClasses = { "LabelSubText" },
        });

        row.AddChild(new Label
        {
            Text = value,
            HorizontalExpand = true,
            ClipText = true,
            FontColorOverride = color,
        });

        return row;
    }

    #endregion

    #region Modules

    private void UpdateModules(ModularChassisUiState state)
    {
        ModulesContainer.RemoveAllChildren();

        ModulesCountLabel.Text = Loc.GetString("chassis-ui-module-count", ("count", state.Modules.Count));

        if (state.Modules.Count == 0)
        {
            ModulesContainer.AddChild(new Label
            {
                Text = Loc.GetString("chassis-ui-no-modules"),
                StyleClasses = { "LabelSubText" },
                FontColorOverride = IS14Palette.Muted,
                Margin = new Thickness(4),
            });

            return;
        }

        foreach (var module in state.Modules)
        {
            ModulesContainer.AddChild(BuildModuleCard(module, state));
        }
    }

    private Control BuildModuleCard(ChassisModuleUiEntry module, ModularChassisUiState state)
    {
        var selected = state.SelectedModule == module.Module;
        var live = module.Active || selected;
        var kindColor = KindColor(module.Kind);

        var card = new PanelContainer
        {
            PanelOverride = IS14Palette.Box(
                live ? IS14Palette.PanelRaised : IS14Palette.Backdrop,
                live ? kindColor.WithAlpha(0.7f) : IS14Palette.Border),
            Margin = new Thickness(0, 0, 0, 4),
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        // Colour rail down the left edge: kind at a glance, no reading required.
        row.AddChild(new PanelContainer
        {
            PanelOverride = new StyleBoxFlat(live ? kindColor : kindColor.WithAlpha(0.4f)),
            MinWidth = 3,
        });

        // The card body is a column, not a row. A horizontal box measures each child with
        // whatever the previous ones left over, so prose sharing a row with the buttons
        // would be handed their width too and run straight underneath them. Below the row
        // it gets the card's full width and wraps against a number that is actually true.
        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(6, 5),
        };

        var top = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        top.AddChild(BuildModuleIcon(module, state));

        var expanded = _expandedModule == module.Module;

        var text = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        header.AddChild(new Label
        {
            Text = module.Name,
            HorizontalExpand = true,
            ClipText = true,
            FontColorOverride = IS14Palette.Text,
        });

        text.AddChild(header);

        text.AddChild(BuildStatPills(module, kindColor));

        if (module.Cooldown > 0f && module.CooldownMax > 0f)
        {
            text.AddChild(new ProgressBar
            {
                MinValue = 0f,
                MaxValue = 1f,
                Value = Math.Clamp(1f - module.Cooldown / module.CooldownMax, 0f, 1f),
                MinHeight = 5,
                Margin = new Thickness(0, 3, 0, 0),
            });
        }

        // The whole text block is the expander. Making the card itself the button would
        // swallow clicks meant for the switch sitting inside it.
        var expander = new IS14Button
        {
            Accent = kindColor,
            Selected = expanded,
            HorizontalExpand = true,
            Padding = 3f,
            ToolTip = Loc.GetString("chassis-ui-module-details"),
        };

        expander.AddChild(text);

        var id = module.Module;
        expander.OnPressed += _ =>
        {
            _expandedModule = expanded ? null : id;
            Rebuild();
        };

        top.AddChild(expander);
        top.AddChild(BuildModuleControls(module, state, selected, live, kindColor));
        body.AddChild(top);

        // Descriptions have to earn their room. A bay of eight modules each explaining
        // itself in three lines is a wall of text nobody reads, so the card keeps its
        // name and its numbers and hands over the prose only when asked.
        if (expanded)
        {
            var prose = new RichTextLabel
            {
                HorizontalExpand = true,
                Margin = new Thickness(0, 4, 0, 0),
                StyleClasses = { "LabelSubText" },
                Modulate = IS14Palette.Muted,
            };

            prose.SetMessage(module.Description);
            body.AddChild(prose);

            foreach (var entry in module.Config)
            {
                if (BuildConfigControl(module.Module, entry) is { } control)
                    body.AddChild(control);
            }
        }

        row.AddChild(body);
        card.AddChild(row);
        return card;
    }

    /// <summary>
    ///     The module's own icon, with the pieces of the shell it is bolted to stacked
    ///     underneath it. There is dead space below a 32-pixel icon, and "which part does
    ///     this hang off?" is the question a dead module most often raises — so the answer
    ///     lives there, carrying the same state colour the paper doll uses.
    /// </summary>
    private Control BuildModuleIcon(ChassisModuleUiEntry module, ModularChassisUiState state)
    {
        var column = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            VerticalAlignment = VAlignment.Top,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 0, 6, 0),
        };

        var iconChip = new PanelContainer
        {
            PanelOverride = IS14Palette.Box(IS14Palette.Panel, IS14Palette.Border, 1f, 2f),
        };

        iconChip.AddChild(new SpriteView(module.Module, _entMan)
        {
            SetSize = new Vector2(32, 32),
            OverrideDirection = Direction.South,
        });

        column.AddChild(iconChip);

        var links = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 2, 0, 0),
        };

        foreach (var required in module.RequiredSlots)
        {
            foreach (var part in state.Parts)
            {
                if ((part.SlotFlag & required) == SlotFlags.NONE)
                    continue;

                links.AddChild(PartBadge(part));
            }
        }

        // Whether the module can run at all, as a tick or a cross beside the pieces it
        // hangs off — which is where the answer usually lies. The reason is on the
        // tooltip; a line of red text saying "the suit is not active" told the player
        // something they could already see and cost a whole row of the card to say it.
        var running = module.BlockReason == ModuleBlockReason.None;

        var status = IS14Palette.Icon(
            UiIcon(running ? IconCheck : IconCross),
            14f,
            running ? IS14Palette.Good : IS14Palette.Warn);

        status.Margin = new Thickness(3, 0, 0, 0);
        status.ToolTip = Loc.GetString(running ? "chassis-ui-module-ready" : BlockLocId(module.BlockReason));
        status.MouseFilter = Control.MouseFilterMode.Stop;
        links.AddChild(status);

        if (links.ChildCount > 0)
            column.AddChild(links);

        return column;
    }

    /// <summary>
    ///     One shell piece as a thumbnail: the part's own sprite over a bar in its state
    ///     colour, so a module card shows at a glance that its gauntlet is stowed or beaten in.
    /// </summary>
    private Control PartBadge(ChassisPartUiEntry part)
    {
        var color = PartColor(part);

        var wrap = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(1, 0),
            ToolTip = $"{part.Name} — {Loc.GetString(PartStateLocId(part))}",

            // Containers ignore the mouse by default, and a tooltip nobody can hover is
            // not a tooltip.
            MouseFilter = Control.MouseFilterMode.Stop,
        };

        wrap.AddChild(new SpriteView(part.Part, _entMan)
        {
            SetSize = new Vector2(22, 22),
            OverrideDirection = Direction.South,
            HorizontalAlignment = HAlignment.Center,
        });

        wrap.AddChild(new PanelContainer
        {
            PanelOverride = new StyleBoxFlat(color),
            MinSize = new Vector2(22, 2),
            HorizontalAlignment = HAlignment.Center,
        });

        return wrap;
    }

    private static string PartStateLocId(ChassisPartUiEntry part) => part.Ruptured
        ? "chassis-ui-part-ruptured"
        : part.Broken
            ? "chassis-ui-part-broken"
            : part.Sealed
                ? "chassis-ui-part-sealed"
                : part.Deployed
                    ? "chassis-ui-part-deployed"
                    : "chassis-ui-part-stowed";

    /// <summary>
    ///     The switch and the eject button, stacked at the right of a module card.
    ///     Pulling a module lives here rather than in the context menu: it belongs with
    ///     the rest of the hardware, and it needs the panel open to say so.
    /// </summary>
    private Control BuildModuleControls(
        ChassisModuleUiEntry module,
        ModularChassisUiState state,
        bool selected,
        bool live,
        Color kindColor)
    {
        var column = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(6, 0, 0, 0),
        };

        // Passive modules have nothing to switch.
        if (module.Kind != ModuleKind.Passive)
        {
            var blocked = module.BlockReason != ModuleBlockReason.None;

            var button = IS14Button.Make(
                UiIcon(blocked ? IconNo : ActionIcon(module, selected)),
                ActionText(module, selected),
                live ? IS14Palette.Good : kindColor);

            button.Selected = live;
            button.MinWidth = 116;
            button.Disabled = blocked;

            var moduleId = module.Module;
            button.OnPressed += _ => OnSelectModule?.Invoke(moduleId);
            column.AddChild(button);
        }

        if (!module.Removable)
            return column;

        // The suit answers the same question the button will ask, so a module that would
        // refuse — compression holding the suit on a belt, for one — comes up already
        // dead with the reason on hover, instead of looking pressable and then failing.
        var canEject = state.PanelOpen && module.EjectBlocked == null;

        var eject = IS14Button.Make(
            UiIcon(canEject ? IconEject : IconNo),
            Loc.GetString("chassis-ui-eject"),
            canEject ? IS14Palette.Warn : IS14Palette.Muted,
            iconSize: 16f,
            padding: 4f);

        eject.MinWidth = 116;
        eject.Disabled = !canEject;
        eject.ToolTip = Loc.GetString(
            canEject
                ? "chassis-ui-eject-tooltip"
                : state.PanelOpen
                    ? module.EjectBlocked!
                    : "chassis-ui-eject-needs-panel");

        if (module.Kind != ModuleKind.Passive)
            eject.Margin = new Thickness(0, 4, 0, 0);

        var id = module.Module;
        eject.OnPressed += _ => OnEjectModule?.Invoke(id);
        column.AddChild(eject);

        return column;
    }

    /// <summary>
    ///     Whole numbers read as whole numbers; anything else keeps one decimal. A beam
    ///     radius of "4" should not be printed as "4.0" just because the temperature
    ///     next to it wants a fraction.
    /// </summary>
    private static string FormatConfigNumber(float value)
    {
        return MathF.Abs(value - MathF.Round(value)) < 0.05f
            ? MathF.Round(value).ToString("0")
            : value.ToString("0.0");
    }

    /// <summary>
    ///     One of a module's settings. Rendered from the generic description the module
    ///     sends, so a new configurable module needs no window code at all.
    /// </summary>
    private Control? BuildConfigControl(NetEntity module, ModuleConfigEntry entry)
    {
        switch (entry.Kind)
        {
            case ModuleConfigKind.Bool:
            {
                var on = entry.Value is true;

                var button = IS14Button.Make(
                    UiIcon(on ? IconCheck : IconCross),
                    entry.Label,
                    on ? IS14Palette.Good : IS14Palette.Muted,
                    iconSize: 14f,
                    padding: 3f);

                button.Selected = on;
                button.HorizontalExpand = true;
                button.Margin = new Thickness(0, 2, 0, 0);
                button.OnPressed += _ => OnConfigureModule?.Invoke(module, entry.Key, !on);

                return button;
            }

            case ModuleConfigKind.Button:
            {
                var button = IS14Button.Make(UiIcon(IconZap), entry.Label, IS14Palette.Accent,
                    iconSize: 14f, padding: 3f);

                button.HorizontalExpand = true;
                button.Margin = new Thickness(0, 2, 0, 0);
                button.OnPressed += _ => OnConfigureModule?.Invoke(module, entry.Key, null);

                return button;
            }

            case ModuleConfigKind.Number when entry.Max > entry.Min:
            {
                var id = (module, entry.Key);

                // What the player last set wins over what the suit last said, until the
                // suit says the same thing back. Otherwise the rebuild that follows the
                // release paints the old number for a whole round trip.
                var value = _pendingConfig.TryGetValue(id, out var pending)
                    ? pending
                    : entry.Value switch
                    {
                        float f => f,
                        double d => (float) d,
                        int i => i,
                        _ => entry.Min,
                    };

                var column = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 2, 0, 0),
                };

                // The value is stamped on the row itself rather than left to a tooltip:
                // a dial nobody can read the number off is a dial you have to guess at.
                var readout = new Label
                {
                    Text = FormatConfigNumber(value),
                    FontColorOverride = IS14Palette.Accent,
                    StyleClasses = { "LabelKeyText" },
                };

                var header = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                };

                header.AddChild(new Label { Text = entry.Label, FontColorOverride = IS14Palette.Muted });
                header.AddChild(new Control { HorizontalExpand = true });
                header.AddChild(readout);
                header.AddChild(IS14Palette.Sub(
                    $" {FormatConfigNumber(entry.Min)}–{FormatConfigNumber(entry.Max)}",
                    IS14Palette.Border));

                var slider = new IS14Slider
                {
                    MinValue = entry.Min,
                    MaxValue = entry.Max,
                    Step = entry.Step,
                    Value = Math.Clamp(value, entry.Min, entry.Max),
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 2, 0, 0),
                };

                // One notch per step where the range is short enough to count them;
                // otherwise a fixed handful, purely so the eye has something to measure by.
                if (entry.Step > 0f)
                {
                    var steps = (int) MathF.Round((entry.Max - entry.Min) / entry.Step);
                    slider.Notches = steps is > 1 and <= 12 ? steps - 1 : 7;
                }

                // The readout follows the handle, but the suit is only told once the
                // player lets go. Sending on every pixel of a drag would put a message
                // on the wire per frame for a setting nobody needs applied mid-drag.
                slider.OnValueChanged += v => readout.Text = FormatConfigNumber(v);
                slider.OnGrabbed += () => _draggedConfig = id;

                slider.OnReleased += v =>
                {
                    _pendingConfig[id] = v;
                    _pendingConfigAge[id] = 0;

                    OnConfigureModule?.Invoke(module, entry.Key, v);
                    EndConfigDrag();
                };

                column.AddChild(header);
                column.AddChild(slider);

                return column;
            }

            case ModuleConfigKind.Choice when entry.Choices is { Length: > 0 }:
            {
                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 2, 0, 0),
                };

                foreach (var choice in entry.Choices)
                {
                    var picked = entry.Value as string == choice;

                    var button = IS14Button.Make(null, choice,
                        picked ? IS14Palette.Good : IS14Palette.Muted, padding: 3f);

                    button.Selected = picked;
                    button.Margin = new Thickness(0, 0, 3, 0);
                    button.OnPressed += _ => OnConfigureModule?.Invoke(module, entry.Key, choice);

                    row.AddChild(button);
                }

                return row;
            }

            default:
                return null;
        }
    }

    private Control BuildStatPills(ChassisModuleUiEntry module, Color kindColor)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 3, 0, 0),
        };

        row.AddChild(IS14Palette.IconChip(
            UiIcon(IconComplexity),
            module.Complexity.ToString(CultureInfo.InvariantCulture),
            IS14Palette.Muted,
            Loc.GetString("chassis-ui-complexity")));

        if (module.IdleDraw > 0f)
        {
            row.AddChild(IS14Palette.IconChip(
                UiIcon(IconBolt),
                Loc.GetString("chassis-ui-module-idle", ("value", Num(module.IdleDraw))),
                IS14Palette.Muted,
                Loc.GetString("chassis-ui-module-idle-tooltip")));
        }

        if (module.ActiveDraw > 0f)
        {
            row.AddChild(IS14Palette.IconChip(
                UiIcon(IconBolt),
                Loc.GetString("chassis-ui-module-active", ("value", Num(module.ActiveDraw))),
                IS14Palette.Warn,
                Loc.GetString("chassis-ui-module-active-tooltip")));
        }

        if (module.UseCost > 0f)
        {
            row.AddChild(IS14Palette.IconChip(
                UiIcon(IconBolt),
                Loc.GetString("chassis-ui-module-use", ("value", Num(module.UseCost))),
                IS14Palette.Warn,
                Loc.GetString("chassis-ui-module-use-tooltip")));
        }

        // What kind of module this is sits at the far end of the numbers rather than
        // beside the name: the name is what you look for, the kind is what you confirm.
        row.AddChild(new Control { HorizontalExpand = true });
        row.AddChild(IS14Palette.Chip(Loc.GetString(KindLocId(module.Kind)), kindColor));

        return row;
    }

    #endregion

    #region Header actions

    private void UpdateActions(ModularChassisUiState state)
    {
        _deployButton.SetContent(
            UiIcon(state.Active ? IconNo : state.AnyDeployed ? IconRetract : IconDeploy),
            Loc.GetString(state.AnyDeployed ? "chassis-ui-retract-all" : "chassis-ui-deploy-all"));

        _deployButton.Disabled = state.Active;
        _deployButton.Accent = state.AnyDeployed ? IS14Palette.Warn : IS14Palette.Accent;

        _sealButton.SetContent(
            UiIcon(!state.AnyDeployed ? IconNo : state.Active ? IconUnseal : IconSeal),
            Loc.GetString(state.Active ? "chassis-ui-deactivate" : "chassis-ui-activate"));

        _sealButton.Disabled = !state.AnyDeployed;
        _sealButton.Selected = state.Active;
    }

    #endregion

    #region Helpers

    /// <summary>
    ///     Redraws from the last known state — used when a click only changed what the
    ///     window is showing, not what the suit is doing.
    /// </summary>
    private void Rebuild()
    {
        if (_state != null)
            UpdateState(_state);
    }

    private Texture Icon(string rsi, string state)
    {
        return _sprites.Frame0(new SpriteSpecifier.Rsi(new ResPath(rsi), state));
    }

    /// <summary>
    ///     Interface icons, cached: the window rebuilds itself on every state push and
    ///     resolving the same handful of textures each time would be waste.
    /// </summary>
    private Texture UiIcon(string path)
    {
        if (_icons.TryGetValue(path, out var cached))
            return cached;

        return _icons[path] = _sprites.Frame0(new SpriteSpecifier.Texture(new ResPath(path)));
    }

    /// <summary>
    ///     Fluent prints a bare float at full binary precision — 0.15f becomes
    ///     0.150000000596046448 — so numbers reach it already formatted.
    /// </summary>
    private static string Num(float value) =>
        value.ToString("0.##", CultureInfo.InvariantCulture);

    private static string SlotLocId(string slot) => slot switch
    {
        "head" => "chassis-ui-slot-head",
        "outerClothing" => "chassis-ui-slot-chest",
        "gloves" => "chassis-ui-slot-hands",
        "shoes" => "chassis-ui-slot-feet",
        _ => "chassis-ui-slot-other",
    };

    private static string ActionText(ChassisModuleUiEntry module, bool selected)
    {
        if (module.ActionText != null)
            return Loc.GetString(module.ActionText);

        return module.Kind switch
        {
            ModuleKind.Usable => Loc.GetString("chassis-ui-module-use-button"),
            ModuleKind.Active => Loc.GetString(selected
                ? "chassis-ui-module-deselect"
                : "chassis-ui-module-select"),
            _ => Loc.GetString(module.Active
                ? "chassis-ui-module-off"
                : "chassis-ui-module-on"),
        };
    }

    private static string ActionIcon(ChassisModuleUiEntry module, bool selected)
    {
        if (module.ActionIcon != null)
            return module.ActionIcon;

        return module.Kind switch
        {
            ModuleKind.Usable => IconZap,
            ModuleKind.Active => selected ? IconPutAway : IconTakeOut,
            _ => IconPower,
        };
    }

    private static string KindLocId(ModuleKind kind) => kind switch
    {
        ModuleKind.Passive => "chassis-ui-kind-passive",
        ModuleKind.Toggleable => "chassis-ui-kind-toggleable",
        ModuleKind.Usable => "chassis-ui-kind-usable",
        ModuleKind.Active => "chassis-ui-kind-active",
        _ => "chassis-ui-kind-passive",
    };

    private static Color KindColor(ModuleKind kind) => kind switch
    {
        ModuleKind.Toggleable => IS14Palette.Accent,
        ModuleKind.Usable => IS14Palette.Warn,
        ModuleKind.Active => Color.FromHex("#E5883F"),
        _ => IS14Palette.Muted,
    };

    private static string BlockLocId(ModuleBlockReason reason) => reason switch
    {
        ModuleBlockReason.NoPower => "chassis-module-no-power",
        ModuleBlockReason.Cooldown => "chassis-module-cooldown",
        ModuleBlockReason.MissingParts => "chassis-module-missing-parts",
        ModuleBlockReason.ChassisInactive => "chassis-module-chassis-inactive",
        ModuleBlockReason.NotWorn => "chassis-module-not-worn",
        ModuleBlockReason.Incapacitated => "chassis-module-incapacitated",
        ModuleBlockReason.Malfunctioning => "chassis-module-malfunctioning",
        _ => "chassis-module-unavailable",
    };

    #endregion
}
