// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._IS14.Medical.Disease;
using Content.Shared._IS14.Medical.Organs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._IS14.Medical.Circulation;

/// <summary>
/// The patient's chart: what they have, and what it has cost them.
/// </summary>
/// <remarks>
/// Two kinds of finding in one list. A diagnosis names the illness; a faculty below full names
/// the capability it has taken away. They belong together because a doctor reads them together
/// — "ischaemia, second stage" and "pump 64%" are one sentence, and splitting them across two
/// panels would have made the reader do the join.
/// <para>
/// Its own control so it can live in the analyser's right-hand column while the trace lives in
/// the other.
/// </para>
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class DiagnosisPanel : BoxContainer
{
    [Dependency] private readonly IEntityManager _entities = default!;
    [Dependency] private readonly IPrototypeManager _protos = default!;

    private readonly List<IS14Diagnosis> _chart = new();
    private readonly List<(string Faculty, int Percent)> _faculties = new();

    private EntityUid? _target;

    /// <summary>
    /// Есть ли хоть одна находка.
    /// </summary>
    /// <remarks>
    /// Список патологий общий с апстримными состояниями, а строку «не обнаружено» дописывает
    /// апстримный код по пустоте своего контейнера. Без этого признака он писал бы её поверх
    /// наших диагнозов.
    /// </remarks>
    public bool HasEntries => _chart.Count > 0 || _faculties.Count > 0;

    public DiagnosisPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetTarget(EntityUid? target)
    {
        _target = target;
        _chart.Clear();
        _faculties.Clear();
        DiagnosisList.RemoveAllChildren();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_target is not { } target)
        {
            Content.Visible = false;
            return;
        }

        var chart = _entities.TryGetComponent<IS14DiseaseCarrierComponent>(target, out var carrier)
            ? carrier.Diagnoses
            : new List<IS14Diagnosis>();

        var faculties = ReadFaculties(target);

        Content.Visible = chart.Count > 0 || faculties.Count > 0;

        // Rebuilt only when it actually changed, so a patient with one diagnosis does not have
        // that line thrown away and recreated sixty times a second.
        if (_chart.SequenceEqual(chart) && _faculties.SequenceEqual(faculties))
            return;

        _chart.Clear();
        _chart.AddRange(chart);
        _faculties.Clear();
        _faculties.AddRange(faculties);
        DiagnosisList.RemoveAllChildren();

        foreach (var entry in chart)
        {
            DiagnosisList.AddChild(new RichTextLabel
            {
                Text = Loc.GetString(
                    "is14-analyzer-diagnosis",
                    ("disease", Loc.GetString(entry.Disease)),
                    ("stage", Loc.GetString(entry.Stage))),
            });
        }

        foreach (var (faculty, percent) in faculties)
        {
            if (!_protos.TryIndex<IS14FacultyPrototype>(faculty, out var proto))
                continue;

            DiagnosisList.AddChild(new RichTextLabel
            {
                Text = Loc.GetString(
                    "is14-analyzer-faculty",
                    ("name", Loc.GetString(proto.Name)),
                    ("percent", percent)),
            });
        }
    }

    /// <summary>
    /// Which of the body's faculties are worth mentioning, worst first.
    /// </summary>
    /// <remarks>
    /// Only the ones below full. A healthy patient must produce an empty list, or the panel
    /// would print nine lines of good news on every scan and bury the one line that matters —
    /// and the analyser would never again be able to say "nothing found".
    /// </remarks>
    private List<(string Faculty, int Percent)> ReadFaculties(EntityUid target)
    {
        var found = new List<(string Faculty, int Percent)>();

        if (!_entities.TryGetComponent<IS14FacultiesComponent>(target, out var comp))
            return found;

        foreach (var (faculty, level) in comp.Levels)
        {
            // Rounded before the comparison, so a faculty that is 99.6% of the way back does
            // not sit in the list reading "100%" and looking like a bug.
            var percent = (int) MathF.Round(Math.Clamp(level, 0f, 1f) * 100f);

            if (percent < 100)
                found.Add((faculty, percent));
        }

        found.Sort((a, b) => a.Percent != b.Percent
            ? a.Percent.CompareTo(b.Percent)
            : string.CompareOrdinal(a.Faculty, b.Faculty));

        return found;
    }
}
