// SPDX-FileCopyrightText: 2025 IS14
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._IS14.Medical.Disease;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._IS14.Medical.Circulation;

/// <summary>
/// The patient's chart: what they have, and how far along it is.
/// </summary>
/// <remarks>
/// Sits in the analyser's right-hand column with the other findings rather than under the
/// trace, because a diagnosis is a conclusion about the patient and not a reading off their
/// heart. Its own control so it can live in one column while the metrics live in the other.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class DiagnosisPanel : BoxContainer
{
    [Dependency] private readonly IEntityManager _entities = default!;

    private readonly List<IS14Diagnosis> _chart = new();

    private EntityUid? _target;

    public DiagnosisPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetTarget(EntityUid? target)
    {
        _target = target;
        _chart.Clear();
        DiagnosisList.RemoveAllChildren();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_target is not { } target
            || !_entities.TryGetComponent<IS14DiseaseCarrierComponent>(target, out var carrier))
        {
            Content.Visible = false;
            return;
        }

        var chart = carrier.Diagnoses;
        Content.Visible = chart.Count > 0;

        // Rebuilt only when it actually changed, so a patient with one diagnosis does not have
        // that line thrown away and recreated sixty times a second.
        if (_chart.SequenceEqual(chart))
            return;

        _chart.Clear();
        _chart.AddRange(chart);
        DiagnosisList.RemoveAllChildren();

        foreach (var entry in chart)
        {
            DiagnosisList.AddChild(new RichTextLabel
            {
                Text = Loc.GetString(
                    "is14-analyzer-diagnosis",
                    ("disease", Loc.GetString(entry.Disease)),
                    ("stage", Loc.GetString(entry.Stage))),
            });
        }
    }
}
