# SPDX-License-Identifier: AGPL-3.0-or-later

name: "Labels: Approved"

on:
  pull_request_review:
    types: [submitted]

jobs:
  add_label:
    if: ${{ github.event.review.state == 'APPROVED' }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    # BOT_TOKEN is used instead of GITHUB_TOKEN so the label is applied on reviews
    # of pull requests coming from forks as well.
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.BOT_TOKEN }}
        labels: "S: Одобрено"
